/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MeAssetFactory.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MeAssetFactory.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
MeAssetInstance * kd_MeAssetInstanceCreate (MeAssetFactory *af,MeFAsset *asset,MeMatrix4Ptr tm,MeBool owner,MdtWorldID world, McdSpaceID space) KD_MANGLED("MeAssetInstanceCreate");
void kd_MeAssetInstanceDestroy(MeAssetInstance *ins) KD_MANGLED("MeAssetInstanceDestroy");
MeAssetFactory * kd_MeAssetFactoryCreate(McdFrameworkID fwk) KD_MANGLED("MeAssetFactoryCreate");
void kd_MeAssetFactoryDestroy(MeAssetFactory *af) KD_MANGLED("MeAssetFactoryDestroy");
void kd_MeAssetFactorySetGeometryPostCreateCB (MeAssetFactory *af,GeometryPostCreateCB cb,void *userdata) KD_MANGLED("MeAssetFactorySetGeometryPostCreateCB");
void kd_MeAssetFactorySetModelCreateFunction(MeAssetFactory *af,ModelCreateFunc func) KD_MANGLED("MeAssetFactorySetModelCreateFunction");
void kd_MeAssetFactorySetModelPostCreateCB(MeAssetFactory *af,ModelPostCreateCB cb,void *userdata) KD_MANGLED("MeAssetFactorySetModelPostCreateCB");
void kd_MeAssetFactorySetJointCreateFunction(MeAssetFactory *af,JointCreateFunc func) KD_MANGLED("MeAssetFactorySetJointCreateFunction");
void kd_MeAssetFactorySetJointPostCreateCB(MeAssetFactory *af,JointPostCreateCB cb,void *userdata) KD_MANGLED("MeAssetFactorySetJointPostCreateCB");
McdGeometryID kd_MeAssetInstanceGetGeometry(MeAssetInstance *ins,char *name) KD_MANGLED("MeAssetInstanceGetGeometry");
McdModelID kd_MeAssetInstanceGetModel(MeAssetInstance *ins,char *name) KD_MANGLED("MeAssetInstanceGetModel");
MdtConstraintID kd_MeAssetInstanceGetJoint(MeAssetInstance *ins,char *name) KD_MANGLED("MeAssetInstanceGetJoint");
void kd_MeAssetInstanceInitGeometryIterator(MeAssetInstance *ins,MeAIGeomIt *it) KD_MANGLED("MeAssetInstanceInitGeometryIterator");
McdGeometryID kd_MeAssetInstanceGetNextGeometry(MeAIGeomIt *it) KD_MANGLED("MeAssetInstanceGetNextGeometry");
void kd_MeAssetInstanceInitModelIterator(MeAssetInstance *ins,MeAIModelIt *it) KD_MANGLED("MeAssetInstanceInitModelIterator");
McdModelID kd_MeAssetInstanceGetNextModel(MeAIModelIt *it) KD_MANGLED("MeAssetInstanceGetNextModel");
void kd_MeAssetInstanceInitJointIterator(MeAssetInstance *ins,MeAIJointIt *it) KD_MANGLED("MeAssetInstanceInitJointIterator");
MdtConstraintID kd_MeAssetInstanceGetNextJoint(MeAIJointIt *it) KD_MANGLED("MeAssetInstanceGetNextJoint");
void kd_MeAssetInstanceEnableDynamics(MeAssetInstance *ins) KD_MANGLED("MeAssetInstanceEnableDynamics");
void kd_MeAssetInstanceDisableDynamics(MeAssetInstance *ins) KD_MANGLED("MeAssetInstanceDisableDynamics");
void * kd_MeAssetInstanceGetUserData(MeAssetInstance *ins) KD_MANGLED("MeAssetInstanceGetUserData");
void kd_MeAssetInstanceSetUserData(MeAssetInstance *ins,void *userdata) KD_MANGLED("MeAssetInstanceSetUserData");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MeAssetInstanceCreate (exported as kd_MeAssetInstanceCreate, asm label "MeAssetInstanceCreate") ---- */
MeAssetInstance *
kd_MeAssetInstanceCreate
          (MeAssetFactory *af,MeFAsset *asset,MeMatrix4Ptr tm,MeBool owner,MdtWorldID world,
          McdSpaceID space)

{
  undefined1 kd_argslot_kd_alloca_iVar5 [4];

    void *kd_argslot_ffffffa4[2];
    void *kd_argslot_ffffffa8[2];
    void *kd_argslot_ffffffac[2];

    char *kd_alloca_iVar5;

  JointCreateFunc p_Var1;
  JointPostCreateCB p_Var2;
  ModelCreateFunc p_Var3;
  ModelPostCreateCB p_Var4;
  int iVar5;
  MdtConstraintID pMVar6;
  int iVar7;
  MeAssetInstance *pMVar8;
  MeHash *pMVar9;
  MeFGeometry *pMVar10;
  McdGeometryID pMVar11;
  char *__s;
  size_t sVar12;
  char *__dest;
  void *extraout_EAX = (void *)0;
  void *pvVar13;
  void *pvVar14;
  McdModelID pMVar15;
  McdModelID pMVar16;
  int iVar17;
  void *pvVar18;
  MeFGeometry *extraout_ECX = (MeFGeometry *)0;
  uint uVar19;
  undefined4 extraout_ECX_00;
  undefined4 extraout_ECX_01;
  undefined4 extraout_ECX_02;
  undefined4 extraout_ECX_03;
  undefined4 uVar20;
  undefined4 extraout_ECX_04;
  undefined4 extraout_ECX_05;
  undefined4 extraout_ECX_06;
  MeAssetFactory *pMVar21;
  undefined4 auStackY_70 [5];
  MeFGeometry *pMStack_50;
  int aiStack_4c [3];
  McdModelID model2;
  McdModelID model1;
  MdtConstraintID constraint;
  McdModelID model1_1;
  McdGeometryID geom;
  McdModelID model;
  int count;
  int i;
  char *assetName;
  MeAssetInstance *ins;
  MeFJointIt it_1;
  MeFGeometryIt it;

  auStackY_70[4] = 0x10011;
  ins = (MeMemoryAPI.create)((int)sizeof(*(MeAssetInstance *)0));
  auStackY_70[4] = 0x1001e;
  assetName = MeFAssetGetName(asset);
  ins->af = af;
  ins->asset = asset;
  ins->owner = owner;
  ins->world = world;
  ins->space = space;
  auStackY_70[4] = 0x10050;
  pMVar9 = MeHashCreate(0x11);
  ins->nameToGeometry = pMVar9;
  auStackY_70[4] = 0x10062;
  pMVar9 = MeHashCreate(0x11);
  ins->nameToModel = pMVar9;
  auStackY_70[4] = 0x10074;
  pMVar9 = MeHashCreate(0x11);
  ins->nameToJoint = pMVar9;
  auStackY_70[4] = 0x1008c;
  MeHashSetKeyFreeFunc(ins->nameToGeometry,MeMemoryAPI.destroy);
  auStackY_70[4] = 0x100a1;
  MeHashSetKeyFreeFunc(ins->nameToModel,MeMemoryAPI.destroy);
  auStackY_70[4] = 0x100b6;
  MeHashSetKeyFreeFunc(ins->nameToJoint,MeMemoryAPI.destroy);
                    
  auStackY_70[4] = 0x100c5;
  MeFAssetInitGeometryIterator(asset,&it);
  while( true ) {
    auStackY_70[4] = 0x100d0;
    pMVar10 = MeFAssetGetGeometry(&it);
    if (pMVar10 == (MeFGeometry *)0x0) break;
                    
    auStackY_70[4] = 0x100ec;
    pMStack_50 = pMVar10;
    pMVar11 = McdGMCreateGeometry(ins->af->gm,pMVar10,assetName);
    auStackY_70[4] = 0x100f6;
    McdGeometryIncrementReferenceCount(pMVar11);
    if (af->geometryPostCreateCB != (GeometryPostCreateCB)0x0) {
      auStackY_70[4] = 0x10147;
      pMStack_50 = extraout_ECX;
      (*af->geometryPostCreateCB)(pMVar11,pMVar10,af->geometryPostCreateCBUserdata);
    }
                    
    auStackY_70[4] = 0x1010c;
    __s = MeFGeometryGetName(pMVar10);
    auStackY_70[4] = 0x10116;
    sVar12 = strlen(__s);
    auStackY_70[4] = 0x10120;
    __dest = (MeMemoryAPI.create)(sVar12 + 1);
    auStackY_70[4] = 0x1012b;
    strcpy(__dest,__s);
    auStackY_70[4] = 0x1013c;
    MeHashInsert(__dest,pMVar11,ins->nameToGeometry);
  }
                    
  auStackY_70[4] = 0x10158;
  count = MeFAssetGetPartCount(asset);
  uVar19 = count * 4 + 0xfU & 0xfffffff0;
  iVar5 = -uVar19;
  *(uint *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = uVar19;
  *(uint *)(&(*kd_argslot_ffffffac)) = uVar19;
  *(int *)(&(*kd_argslot_ffffffa8)) = (kd_alloca_iVar5 = (char *)alloca((size_t)(count) * 4 + 0));
  *(MeFAsset **)(&(*kd_argslot_ffffffa4)) = asset;
  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10178;
  MeFAssetGetPartsSortedByName
            (*(void **)(&(*kd_argslot_ffffffa4)),*(void **)(&(*kd_argslot_ffffffa8)));
  i = 0;
  pvVar13 = extraout_EAX;
  if (0 < count) {
    do {
                    
      model = (McdModelID)0x0;
      *(undefined4 *)(&(*kd_argslot_ffffffa4)) = *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + i * 4);
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1031c;
      pvVar13 = MeFAssetPartGetModel(*(void **)(&(*kd_argslot_ffffffa4)));
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10326;
      pvVar14 = MeFModelGetGeometry(*(void **)(&(*kd_argslot_ffffffa4)));
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10330;
      iVar17 = MeFModelGetType(*(void **)(&(*kd_argslot_ffffffa4)));
      pMVar8 = ins;
      iVar17 = iVar17 + -1;
      if ((iVar17 == 0) || (pvVar14 == (void *)0x0)) {
        *(McdGeomMan **)(&(*kd_argslot_ffffffa4)) = af->gm;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x104fd;
        geom = McdGMGetNullGeometry(*(void **)(&(*kd_argslot_ffffffa4)));
      }
      else {
        *(int *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = iVar17;
        *(int *)(&(*kd_argslot_ffffffac)) = iVar17;
        *(MeHash **)(&(*kd_argslot_ffffffa8)) = pMVar8->nameToGeometry;
        *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10351;
        pvVar13 = MeFGeometryGetName(*(void **)(&(*kd_argslot_ffffffa4)));
        *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10359;
        geom = MeHashLookup(*(void **)(&(*kd_argslot_ffffffa4)),
                            *(void **)(&(*kd_argslot_ffffffa8)));
      }
      *(undefined4 *)(&(*kd_argslot_ffffffa4)) = *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + i * 4);
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10369;
      pvVar13 = MeFAssetPartGetName(*(void **)(&(*kd_argslot_ffffffa4)));
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10373;
      sVar12 = strlen(*(char **)(&(*kd_argslot_ffffffa4)));
      *(size_t *)(&(*kd_argslot_ffffffa4)) = sVar12 + 1;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1037d;
      pvVar14 = (MeMemoryAPI.create)(*(uint *)(&(*kd_argslot_ffffffa4)));
      *(void **)(&(*kd_argslot_ffffffa8)) = pvVar13;
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1038a;
      strcpy(*(char **)(&(*kd_argslot_ffffffa4)),*(char **)(&(*kd_argslot_ffffffa8)));
      p_Var3 = af->modelCreateFunc;
      pMVar16 = (McdModelID)0x0;
      pMVar21 = af;
      if (p_Var3 != (ModelCreateFunc)0x0) {
        *(MeMatrix4Ptr *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = tm;
        pMVar11 = geom;
        *(MdtWorldID *)(&(*kd_argslot_ffffffac)) = world;
        iVar17 = i;
        *(McdGeometryID *)(&(*kd_argslot_ffffffa8)) = pMVar11;
        pMVar21 = *(MeAssetFactory **)((kd_iptr)(kd_alloca_iVar5) + iVar17 * (int)sizeof(void *));
        *(MeAssetFactory **)(&(*kd_argslot_ffffffa4)) = pMVar21;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x104e4;
        pMVar16 = (*p_Var3)(*(MeFAssetPart **)(&(*kd_argslot_ffffffa4)),
                            *(McdGeometryID *)(&(*kd_argslot_ffffffa8)),
                            *(MdtWorldID *)(&(*kd_argslot_ffffffac)),
                            *(MeMatrix4Ptr *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0));
        model = pMVar16;
      }
      *(McdModelID *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pMVar16;
      *(McdModelID *)(&(*kd_argslot_ffffffac)) = pMVar16;
      *(McdModelID *)(&(*kd_argslot_ffffffa8)) = model;
      *(McdSpaceID *)(&(*kd_argslot_ffffffa4)) = space;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x103aa;
      McdSpaceInsertModel(*(void **)(&(*kd_argslot_ffffffa4)),*(void **)(&(*kd_argslot_ffffffa8)))
      ;
      p_Var4 = af->modelPostCreateCB;
      uVar20 = extraout_ECX_05;
      if (p_Var4 != (ModelPostCreateCB)0x0) {
        *(MeAssetFactory **)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pMVar21;
        iVar17 = i;
        *(void **)(&(*kd_argslot_ffffffac)) = af->modelPostCreateCBUserdata;
        pMVar16 = model;
        *(undefined4 *)(&(*kd_argslot_ffffffa8)) =
             *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + iVar17 * 4);
        *(McdModelID *)(&(*kd_argslot_ffffffa4)) = pMVar16;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x104c7;
        (*p_Var4)(*(McdModelID *)(&(*kd_argslot_ffffffa4)),
                  *(MeFAssetPart **)(&(*kd_argslot_ffffffa8)),*(void **)(&(*kd_argslot_ffffffac)))
        ;
        uVar20 = extraout_ECX_06;
      }
      pMVar8 = ins;
      *(undefined4 *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = uVar20;
      pMVar16 = model;
      *(MeHash **)(&(*kd_argslot_ffffffac)) = pMVar8->nameToModel;
      *(McdModelID *)(&(*kd_argslot_ffffffa8)) = pMVar16;
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x103cd;
      pvVar13 = MeHashInsert(*(void **)(&(*kd_argslot_ffffffa4)),
                             *(void **)(&(*kd_argslot_ffffffa8)),
                             *(void **)(&(*kd_argslot_ffffffac)));
      i = i + 1;
    } while (i < count);
    i = 0;
    if (0 < count) {
      do {
                    
        iVar17 = i + 1;
        aiStack_4c[2] = iVar17;
        if (iVar17 < count) {
          do {
            *(void **)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pvVar13;
            iVar7 = i;
            *(undefined4 *)(&(*kd_argslot_ffffffa8)) =
                 *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + iVar17 * 4);
            *(undefined4 *)(&(*kd_argslot_ffffffa4)) =
                 *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + iVar7 * 4);
            *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10425;
            pvVar13 = (void *)MeFAssetPartIsCollisionEnabled
                                        (*(void **)(&(*kd_argslot_ffffffa4)),
                                         *(void **)(&(*kd_argslot_ffffffa8)));
            pMVar8 = ins;
            if (pvVar13 == (void *)0x0) {
                    
              *(undefined4 *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = 0;
              iVar7 = i;
              *(undefined4 *)(&(*kd_argslot_ffffffac)) = 0;
              *(MeHash **)(&(*kd_argslot_ffffffa8)) = pMVar8->nameToModel;
              *(undefined4 *)(&(*kd_argslot_ffffffa4)) =
                   *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + iVar7 * 4);
              *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10449;
              pvVar13 = MeFAssetPartGetName(*(void **)(&(*kd_argslot_ffffffa4)));
              *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
              *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10451;
              model1_1 = MeHashLookup(*(void **)(&(*kd_argslot_ffffffa4)),
                                      *(void **)(&(*kd_argslot_ffffffa8)));
              *(MeHash **)(&(*kd_argslot_ffffffa8)) = ins->nameToModel;
              *(undefined4 *)(&(*kd_argslot_ffffffa4)) =
                   *(undefined4 *)((kd_iptr)(kd_alloca_iVar5) + iVar17 * 4);
              *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10466;
              pvVar13 = MeFAssetPartGetName(*(void **)(&(*kd_argslot_ffffffa4)));
              *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
              *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1046e;
              pvVar14 = MeHashLookup(*(void **)(&(*kd_argslot_ffffffa4)),
                                     *(void **)(&(*kd_argslot_ffffffa8)));
              pvVar13 = pvVar14;
              if ((model1_1 != (McdModelID)0x0) && (pvVar14 != (void *)0x0)) {
                *(McdModelID *)(&(*kd_argslot_ffffffa4)) = model1_1;
                *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1048a;
                pvVar18 = McdModelGetSpace(*(void **)(&(*kd_argslot_ffffffa4)));
                pvVar13 = (void *)0x0;
                if (pvVar18 != (void *)0x0) {
                  *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
                  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1049a;
                  pvVar18 = McdModelGetSpace(*(void **)(&(*kd_argslot_ffffffa4)));
                  pvVar13 = (void *)0x0;
                  if (pvVar18 != (void *)0x0) {
                    *(void **)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pvVar18;
                    *(void **)(&(*kd_argslot_ffffffac)) = pvVar18;
                    pMVar16 = model1_1;
                    *(void **)(&(*kd_argslot_ffffffa8)) = pvVar14;
                    *(McdModelID *)(&(*kd_argslot_ffffffa4)) = pMVar16;
                    *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x104ad;
                    pvVar13 = (void *)McdSpaceDisablePair(*(void **)(&(*kd_argslot_ffffffa4)),
                                                          *(void **)(&(*kd_argslot_ffffffa8)));
                  }
                }
              }
            }
            iVar17 = iVar17 + 1;
          } while (iVar17 < count);
        }
        i = aiStack_4c[2];
      } while (aiStack_4c[2] < count);
    }
  }
                    
  *(void **)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pvVar13;
  *(MeFJointIt **)(&(*kd_argslot_ffffffa8)) = &it_1;
  *(MeFAsset **)(&(*kd_argslot_ffffffa4)) = asset;
  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1019d;
  MeFAssetInitJointIterator
            (*(void **)(&(*kd_argslot_ffffffa4)),*(void **)(&(*kd_argslot_ffffffa8)));
LAB_000101a0:
  *(MeFJointIt **)(&(*kd_argslot_ffffffa4)) = &it_1;
  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x101ac;
  pvVar13 = MeFAssetGetJoint(*(void **)(&(*kd_argslot_ffffffa4)));
  if (pvVar13 == (void *)0x0) {
    return ins;
  }
  *(void **)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pvVar13;
  *(undefined4 *)(&(*kd_argslot_ffffffa8)) = 0;
  *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
  model1 = (McdModelID)0x0;
  model2 = (McdModelID)0x0;
  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x101d1;
  pvVar14 = MeFJointGetPart(*(void **)(&(*kd_argslot_ffffffa4)),*(int *)(&(*kd_argslot_ffffffa8)))
  ;
  *(undefined4 *)(&(*kd_argslot_ffffffa8)) = 1;
  *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x101dd;
  pMVar15 = MeFJointGetPart(*(void **)(&(*kd_argslot_ffffffa4)),*(int *)(&(*kd_argslot_ffffffa8)))
  ;
  pMVar8 = ins;
  pMVar16 = pMVar15;
  if (pvVar14 != (void *)0x0) {
    *(undefined4 *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = extraout_ECX_00;
    *(MeHash **)(&(*kd_argslot_ffffffa8)) = pMVar8->nameToModel;
    *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
    *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x101f5;
    pvVar14 = MeFAssetPartGetName(*(void **)(&(*kd_argslot_ffffffa4)));
    *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
    *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x101fd;
    pMVar16 = MeHashLookup(*(void **)(&(*kd_argslot_ffffffa4)),*(void **)(&(*kd_argslot_ffffffa8))
                          );
    model1 = pMVar16;
  }
  if (pMVar15 != (McdModelID)0x0) {
    *(McdModelID *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = pMVar16;
    *(McdModelID *)(&(*kd_argslot_ffffffac)) = pMVar16;
    *(MeHash **)(&(*kd_argslot_ffffffa8)) = ins->nameToModel;
    *(McdModelID *)(&(*kd_argslot_ffffffa4)) = pMVar15;
    *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10216;
    pvVar14 = MeFAssetPartGetName(*(void **)(&(*kd_argslot_ffffffa4)));
    *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
    *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1021e;
    model2 = MeHashLookup(*(void **)(&(*kd_argslot_ffffffa4)),*(void **)(&(*kd_argslot_ffffffa8)))
    ;
  }
  if (model1 == (McdModelID)0x0) goto LAB_0001023e;
  *(McdModelID *)(&(*kd_argslot_ffffffa4)) = model1;
  *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10237;
  pvVar14 = McdModelGetBody(*(void **)(&(*kd_argslot_ffffffa4)));
  uVar20 = extraout_ECX_01;
  if (pvVar14 == (void *)0x0) goto LAB_0001023e;
  goto LAB_00010260;
LAB_0001023e:
  if (model2 != (McdModelID)0x0) {
    *(McdModelID *)(&(*kd_argslot_ffffffa4)) = model2;
    *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10255;
    pvVar14 = McdModelGetBody(*(void **)(&(*kd_argslot_ffffffa4)));
    uVar20 = extraout_ECX_02;
    if (pvVar14 != (void *)0x0) {
LAB_00010260:
      pMVar15 = model1;
      pMVar16 = model2;
      p_Var1 = af->jointCreateFunc;
      if (p_Var1 != (JointCreateFunc)0x0) {
        *(MeMatrix4Ptr *)(&(*kd_argslot_ffffffa4)) = tm;
        *(McdModelID *)((kd_iptr)auStackY_70 + 0x10) = pMVar16;
        *(McdModelID *)((kd_iptr)auStackY_70 + 0xc) = pMVar15;
        *(MdtWorldID *)((kd_iptr)auStackY_70 + 8) = world;
        *(void **)((kd_iptr)auStackY_70 + 4) = pvVar13;
        *(undefined4 *)((kd_iptr)auStackY_70) = 0x102f0;
        constraint = (*p_Var1)(*(MeFJoint **)((kd_iptr)auStackY_70 + 4),
                               *(MdtWorldID *)((kd_iptr)auStackY_70 + 8),
                               *(McdModelID *)((kd_iptr)auStackY_70 + 0xc),
                               *(McdModelID *)((kd_iptr)auStackY_70 + 0x10),
                               *(MeMatrix4Ptr *)(&(*kd_argslot_ffffffa4)));
        uVar20 = extraout_ECX_04;
      }
      if (constraint != (MdtConstraintID)0x0) {
        *(MdtConstraintID *)(&(*kd_argslot_ffffffa4)) = constraint;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1027d;
        MdtConstraintEnable(*(void **)(&(*kd_argslot_ffffffa4)));
        uVar20 = extraout_ECX_03;
      }
      pvVar14 = af->jointPostCreateCBUserdata;
      if (pvVar14 != (void *)0x0) {
        *(undefined4 *)((kd_iptr)(kd_argslot_kd_alloca_iVar5) + 0x0) = uVar20;
        *(void **)(&(*kd_argslot_ffffffac)) = pvVar14;
        pMVar6 = constraint;
        *(void **)(&(*kd_argslot_ffffffa8)) = pvVar13;
        *(MdtConstraintID *)(&(*kd_argslot_ffffffa4)) = pMVar6;
        p_Var2 = af->jointPostCreateCB;
        *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x102d5;
        (*p_Var2)(*(MdtConstraintID *)(&(*kd_argslot_ffffffa4)),
                  *(MeFJoint **)(&(*kd_argslot_ffffffa8)),*(void **)(&(*kd_argslot_ffffffac)));
      }
                    
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x10293;
      pvVar13 = MeFJointGetName(*(void **)(&(*kd_argslot_ffffffa4)));
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar13;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x1029d;
      sVar12 = strlen(*(char **)(&(*kd_argslot_ffffffa4)));
      *(size_t *)(&(*kd_argslot_ffffffa4)) = sVar12 + 1;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x102a7;
      pvVar14 = (MeMemoryAPI.create)(*(uint *)(&(*kd_argslot_ffffffa4)));
      *(void **)(&(*kd_argslot_ffffffa8)) = pvVar13;
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x102b2;
      strcpy(*(char **)(&(*kd_argslot_ffffffa4)),*(char **)(&(*kd_argslot_ffffffa8)));
      pMVar6 = constraint;
      *(MeHash **)(&(*kd_argslot_ffffffac)) = ins->nameToJoint;
      *(MdtConstraintID *)(&(*kd_argslot_ffffffa8)) = pMVar6;
      *(void **)(&(*kd_argslot_ffffffa4)) = pvVar14;
      *(undefined4 *)((kd_iptr)auStackY_70 + 0x10) = 0x102c6;
      MeHashInsert(*(void **)(&(*kd_argslot_ffffffa4)),*(void **)(&(*kd_argslot_ffffffa8)),
                   *(void **)(&(*kd_argslot_ffffffac)));
    }
  }
  goto LAB_000101a0;
}

/* ---- MeAssetInstanceDestroy (exported as kd_MeAssetInstanceDestroy, asm label "MeAssetInstanceDestroy") ---- */
void kd_MeAssetInstanceDestroy(MeAssetInstance *ins)

{
  void *pvVar1;
  void *pvVar2;
  MeMatrix4Ptr tm;
  MeHashIterator it;
  
  if (ins->owner != 0) {
                    
    MeHashInitIterator(&it,ins->nameToJoint);
    while (pvVar1 = MeHashGetDatum(&it), pvVar1 != (void *)0x0) {
      MdtConstraintDisable(pvVar1);
      MdtConstraintDestroy(pvVar1);
    }
    if (ins->owner != 0) {
                    
      MeHashInitIterator(&it,ins->nameToModel);
      while (pvVar1 = MeHashGetDatum(&it), pvVar1 != (void *)0x0) {
        tm = (MeMatrix4Ptr)0x0;
        pvVar2 = McdModelGetSpace(pvVar1);
        if (pvVar2 != (void *)0x0) {
          McdSpaceRemoveModel(pvVar1);
          MstBridgeUpdateTransitions(ins->bridge,ins->space,ins->world);
        }
        pvVar2 = McdModelGetBody(pvVar1);
        if (pvVar2 == (void *)0x0) {
          tm = McdModelGetTransformPtr(pvVar1);
        }
        else {
          MdtBodyDisable(pvVar2);
          MdtBodyDestroy(pvVar2);
        }
        McdModelDestroy(pvVar1);
        if (tm != (MeMatrix4Ptr)0x0) {
          (MeMemoryAPI.destroyAligned)(tm);
        }
      }
      if (ins->owner != 0) {
                    
        MeHashInitIterator(&it,ins->nameToGeometry);
        while (pvVar1 = MeHashGetDatum(&it), pvVar1 != (void *)0x0) {
          McdGeometryDecrementReferenceCount(pvVar1);
          McdGMDestroyGeometry(ins->af->gm,pvVar1);
        }
      }
    }
  }
  MeHashDestroy(ins->nameToGeometry);
  MeHashDestroy(ins->nameToModel);
  MeHashDestroy(ins->nameToJoint);
  (MeMemoryAPI.destroy)(ins);
  return;
}

/* ---- MeAssetFactoryCreate (exported as kd_MeAssetFactoryCreate, asm label "MeAssetFactoryCreate") ---- */
MeAssetFactory * kd_MeAssetFactoryCreate(McdFrameworkID fwk)

{
  MeAssetFactory *pMVar1;
  McdGeomMan *pMVar2;

  pMVar1 = (MeMemoryAPI.create)((int)sizeof(*(MeAssetFactory *)0));
  pMVar2 = McdGMCreate(fwk);
  pMVar1->geometryPostCreateCB = (GeometryPostCreateCB)0x0;
  pMVar1->gm = pMVar2;
  pMVar1->geometryPostCreateCBUserdata = (void *)0x0;
  pMVar1->modelCreateFunc = McdModelCreateFromMeFAssetPart;
  pMVar1->modelPostCreateCB = (ModelPostCreateCB)0x0;
  pMVar1->modelPostCreateCBUserdata = (void *)0x0;
  pMVar1->jointCreateFunc = MdtConstraintCreateFromMeFJoint;
  pMVar1->jointPostCreateCB = (JointPostCreateCB)0x0;
  pMVar1->jointPostCreateCBUserdata = (void *)0x0;
  return pMVar1;
}

/* ---- MeAssetFactoryDestroy (exported as kd_MeAssetFactoryDestroy, asm label "MeAssetFactoryDestroy") ---- */
void kd_MeAssetFactoryDestroy(MeAssetFactory *af)

{
  McdGMDestroy(af->gm);
  (MeMemoryAPI.destroy)(af);
  return;
}

/* ---- MeAssetFactorySetGeometryPostCreateCB (exported as kd_MeAssetFactorySetGeometryPostCreateCB, asm label "MeAssetFactorySetGeometryPostCreateCB") ---- */
void kd_MeAssetFactorySetGeometryPostCreateCB
               (MeAssetFactory *af,GeometryPostCreateCB cb,void *userdata)

{
  af->geometryPostCreateCB = cb;
  af->geometryPostCreateCBUserdata = userdata;
  return;
}

/* ---- MeAssetFactorySetModelCreateFunction (exported as kd_MeAssetFactorySetModelCreateFunction, asm label "MeAssetFactorySetModelCreateFunction") ---- */
void kd_MeAssetFactorySetModelCreateFunction(MeAssetFactory *af,ModelCreateFunc func)

{
  af->modelCreateFunc = func;
  return;
}

/* ---- MeAssetFactorySetModelPostCreateCB (exported as kd_MeAssetFactorySetModelPostCreateCB, asm label "MeAssetFactorySetModelPostCreateCB") ---- */
void kd_MeAssetFactorySetModelPostCreateCB(MeAssetFactory *af,ModelPostCreateCB cb,void *userdata)

{
  af->modelPostCreateCB = cb;
  af->modelPostCreateCBUserdata = userdata;
  return;
}

/* ---- MeAssetFactorySetJointCreateFunction (exported as kd_MeAssetFactorySetJointCreateFunction, asm label "MeAssetFactorySetJointCreateFunction") ---- */
void kd_MeAssetFactorySetJointCreateFunction(MeAssetFactory *af,JointCreateFunc func)

{
  af->jointCreateFunc = func;
  return;
}

/* ---- MeAssetFactorySetJointPostCreateCB (exported as kd_MeAssetFactorySetJointPostCreateCB, asm label "MeAssetFactorySetJointPostCreateCB") ---- */
void kd_MeAssetFactorySetJointPostCreateCB(MeAssetFactory *af,JointPostCreateCB cb,void *userdata)

{
  af->jointPostCreateCB = cb;
  af->jointPostCreateCBUserdata = userdata;
  return;
}

/* ---- MeAssetInstanceGetGeometry (exported as kd_MeAssetInstanceGetGeometry, asm label "MeAssetInstanceGetGeometry") ---- */
McdGeometryID kd_MeAssetInstanceGetGeometry(MeAssetInstance *ins,char *name)

{
  McdGeometryID pMVar1;
  
  pMVar1 = MeHashLookup(name,ins->nameToGeometry);
  return pMVar1;
}

/* ---- MeAssetInstanceGetModel (exported as kd_MeAssetInstanceGetModel, asm label "MeAssetInstanceGetModel") ---- */
McdModelID kd_MeAssetInstanceGetModel(MeAssetInstance *ins,char *name)

{
  McdModelID pMVar1;
  
  pMVar1 = MeHashLookup(name,ins->nameToModel);
  return pMVar1;
}

/* ---- MeAssetInstanceGetJoint (exported as kd_MeAssetInstanceGetJoint, asm label "MeAssetInstanceGetJoint") ---- */
MdtConstraintID kd_MeAssetInstanceGetJoint(MeAssetInstance *ins,char *name)

{
  MdtConstraintID pMVar1;
  
  pMVar1 = MeHashLookup(name,ins->nameToJoint);
  return pMVar1;
}

/* ---- MeAssetInstanceInitGeometryIterator (exported as kd_MeAssetInstanceInitGeometryIterator, asm label "MeAssetInstanceInitGeometryIterator") ---- */
void kd_MeAssetInstanceInitGeometryIterator(MeAssetInstance *ins,MeAIGeomIt *it)

{
  MeHashInitIterator(it,ins->nameToGeometry);
  return;
}

/* ---- MeAssetInstanceGetNextGeometry (exported as kd_MeAssetInstanceGetNextGeometry, asm label "MeAssetInstanceGetNextGeometry") ---- */
McdGeometryID kd_MeAssetInstanceGetNextGeometry(MeAIGeomIt *it)

{
  McdGeometryID pMVar1;
  
  pMVar1 = MeHashGetDatum(it);
  return pMVar1;
}

/* ---- MeAssetInstanceInitModelIterator (exported as kd_MeAssetInstanceInitModelIterator, asm label "MeAssetInstanceInitModelIterator") ---- */
void kd_MeAssetInstanceInitModelIterator(MeAssetInstance *ins,MeAIModelIt *it)

{
  MeHashInitIterator(it,ins->nameToModel);
  return;
}

/* ---- MeAssetInstanceGetNextModel (exported as kd_MeAssetInstanceGetNextModel, asm label "MeAssetInstanceGetNextModel") ---- */
McdModelID kd_MeAssetInstanceGetNextModel(MeAIModelIt *it)

{
  McdModelID pMVar1;
  
  pMVar1 = MeHashGetDatum(it);
  return pMVar1;
}

/* ---- MeAssetInstanceInitJointIterator (exported as kd_MeAssetInstanceInitJointIterator, asm label "MeAssetInstanceInitJointIterator") ---- */
void kd_MeAssetInstanceInitJointIterator(MeAssetInstance *ins,MeAIJointIt *it)

{
  MeHashInitIterator(it,ins->nameToJoint);
  return;
}

/* ---- MeAssetInstanceGetNextJoint (exported as kd_MeAssetInstanceGetNextJoint, asm label "MeAssetInstanceGetNextJoint") ---- */
MdtConstraintID kd_MeAssetInstanceGetNextJoint(MeAIJointIt *it)

{
  MdtConstraintID pMVar1;
  
  pMVar1 = MeHashGetDatum(it);
  return pMVar1;
}

/* ---- MeAssetInstanceEnableDynamics (exported as kd_MeAssetInstanceEnableDynamics, asm label "MeAssetInstanceEnableDynamics") ---- */
void kd_MeAssetInstanceEnableDynamics(MeAssetInstance *ins)

{
  return;
}

/* ---- MeAssetInstanceDisableDynamics (exported as kd_MeAssetInstanceDisableDynamics, asm label "MeAssetInstanceDisableDynamics") ---- */
void kd_MeAssetInstanceDisableDynamics(MeAssetInstance *ins)

{
  return;
}

/* ---- MeAssetInstanceGetUserData (exported as kd_MeAssetInstanceGetUserData, asm label "MeAssetInstanceGetUserData") ---- */
void * kd_MeAssetInstanceGetUserData(MeAssetInstance *ins)

{
  return ins->userdata;
}

/* ---- MeAssetInstanceSetUserData (exported as kd_MeAssetInstanceSetUserData, asm label "MeAssetInstanceSetUserData") ---- */
void kd_MeAssetInstanceSetUserData(MeAssetInstance *ins,void *userdata)

{
  ins->userdata = userdata;
  return;
}
