/* Generated by karma-decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: /tmp/karmaprobe/members/libMcdPrimitives/IxBoxBox.o
 */
#include "kd_compat.h"
#include "kd_types.h"
#include <stdbool.h>

/* ---- hand-written prelude ---- */
/*  Hand-written prelude for IxBoxBox.
 *
 *  This is the per-object manual step: declare everything the original object
 *  imported, plus its file-scope statics. Everything else is generated.
 *
 *  Contract taken straight from `nm IxBoxBox.o`:
 *    exports  McdBoxBoxIntersect, McdBoxBoxSafeTime, McdBoxBoxRegisterInteraction
 *    imports  the 9 Mcd/Me symbols below (+ __gxx_personality_v0, not needed in C)
 *    statics  Vec4NegOne / Vec4One / Vec4Zero, McdBoxBoxSafeTime::maxAngle
 */
#include <McdCTypes.h>
#include <McdModel.h>
#include <McdBox.h>
#include <McdFrame.h>
#include <McdContact.h>
#include <MeMath.h>

/* --- file-scope statics ---------------------------------------------------
   In the original these were C++ globals filled by a static constructor
   (__static_initialization_and_destruction_0, which we drop). Constant data,
   so a plain C initializer is equivalent and avoids the ctor entirely. */
static const lsVec4 Vec4NegOne = {{-1.0f, -1.0f, -1.0f, -1.0f}};
static const lsVec4 Vec4One    = {{ 1.0f,  1.0f,  1.0f,  1.0f}};
static const lsVec4 Vec4Zero   = {{ 0.0f,  0.0f,  0.0f,  0.0f}};

/* Function-local static in McdBoxBoxSafeTime(); Ghidra renders it
   `McdBoxBoxSafeTime::maxAngle`, which ghidra_clean.py flattens to `__`.
   Original symbol _ZZ17McdBoxBoxSafeTimeE8maxAngle; value read out of the
   object's .data (cd cc 4c 3e = 0.2f). NEVER guess these — read them. */
static const float McdBoxBoxSafeTime__maxAngle = 0.2f;

/* --- imports --------------------------------------------------------------
   These resolve against the still-original metoolkit archives during the
   incremental substitution, and against other recovered objects later. */
extern MeMatrix4Ptr McdModelGetTransformPtr(McdModelID m);
extern MeReal       McdModelGetContactTolerance(McdModelID m);
extern McdGeometryID McdModelGetGeometry(McdModelID m);
extern MeReal      *McdModelGetLinearVelocityPtr(McdModelID m);
extern MeReal      *McdModelGetAngularVelocityPtr(McdModelID m);
extern MeReal      *McdBoxGetRadii(McdBoxID b);
extern void         McdFrameworkSetInteractions(McdFramework *f, int t1, int t2,
                                                McdInteractions *i);
extern void         MeQuaternionFromTM(MeVector4 q, const MeMatrix4 tm);

/* C++-mangled import: MovingBoxBoxIntersect(float const*, lsTransform const*,
   lsVec3 const&, float const*, lsTransform const*, lsVec3 const&, float,
   float&, lsVec3&). Declared with an asm label so C can call it directly. */
extern int MovingBoxBoxIntersect(const float *rA, const lsTransform *tA,
                                 const lsVec3 *vA,
                                 const float *rB, const lsTransform *tB,
                                 const lsVec3 *vB,
                                 float maxTime, float *outT, lsVec3 *outN)
    KD_MANGLED("_Z21MovingBoxBoxIntersectPKfPK11lsTransformRK6lsVec3S0_S3_S6_fRfRS4_");

/* ---- forward declarations ---- */
MeBool McdBoxBoxIntersect(McdModelPair *p,McdIntersectResult *result);
int McdBoxBoxSafeTime(McdModelPair *p,MeReal maxTime,McdSafeTimeResult *result);
MeBool McdBoxBoxRegisterInteraction(McdFramework *frame);
static bool McdVanillaOverlapOBBs (MeReal *outSep,lsVec3 *outN,MeReal *outPN,MeI16 *outDims,MeReal inEps,lsVec3 *inR1, lsVec3 *inR2,lsTransform *inT12);
static void BoxBoxIntersect(lsVec3 **outList,lsTransform *tAB,lsVec3 *inRA,lsVec3 *inRB,MeReal scale);
static void McdVanillaBoxEdgeBoxIntersect (lsVec3 **outList,lsTransform *tAB,lsVec3 *inRA,lsVec3 *inRB,MeReal scale);
static int McdVanillaSegmentCubeIntersect (MeReal *tInMax,MeReal *tOutMin,lsVec3 *orig,lsVec3 *disp,lsVec3 *invDisp,lsVec3 *inR, MeReal eps);

/* ---- McdBoxBoxIntersect (exported) ---- */
MeBool McdBoxBoxIntersect(McdModelPair *p,McdIntersectResult *result)

{
  McdFramework *pMVar1;
  float fVar2;
  uint uVar3;
  bool bVar4;
  float *pfVar5;
  float *pfVar6;
  undefined4 uVar7;
  undefined4 uVar8;
  lsVec3 *inR1;
  lsVec3 *inR2;
  int iVar9;
  McdContact *pMVar10;
  MeBool MVar11;
  lsVec3 *plVar12;
  uint uVar13;
  longdouble lVar14;
  longdouble lVar15;
  lsVec3 *rB;
  lsVec3 *rA;
  McdBoxID geometry2;
  lsVec3 *verts;
  MeReal separation;
  MeReal PN;
  MeI16 dims;
  lsVec3 footprint [48];
  lsVec3 normal;
  lsTransform tAB;

  pfVar5 = (float *)McdModelGetTransformPtr(p->model1);
  pfVar6 = (float *)McdModelGetTransformPtr(p->model2);
  lVar14 = (longdouble)McdModelGetContactTolerance(p->model1);
  lVar15 = (longdouble)McdModelGetContactTolerance(p->model2);
  uVar7 = McdModelGetGeometry(p->model1);
  uVar8 = McdModelGetGeometry(p->model2);
  result->touch = 0;
  result->contactCount = 0;
  inR1 = (lsVec3 *)McdBoxGetRadii(uVar7);
  inR2 = (lsVec3 *)McdBoxGetRadii(uVar8);
  tAB.row[0].v.v[0] = pfVar5[2] * pfVar6[2] + pfVar5[1] * pfVar6[1] + *pfVar5 * *pfVar6;
  tAB.row[0].v.v[1] = pfVar5[6] * pfVar6[2] + pfVar5[5] * pfVar6[1] + pfVar5[4] * *pfVar6;
  tAB.row[0].v.v[2] = pfVar5[10] * pfVar6[2] + pfVar5[9] * pfVar6[1] + pfVar5[8] * *pfVar6;
  tAB.row[1].v.v[0] = pfVar5[2] * pfVar6[6] + pfVar5[1] * pfVar6[5] + *pfVar5 * pfVar6[4];
  tAB.row[1].v.v[1] = pfVar5[6] * pfVar6[6] + pfVar5[5] * pfVar6[5] + pfVar5[4] * pfVar6[4];
  tAB.row[1].v.v[2] = pfVar5[10] * pfVar6[6] + pfVar5[9] * pfVar6[5] + pfVar5[8] * pfVar6[4];
  tAB.row[2].v.v[0] = pfVar5[2] * pfVar6[10] + pfVar5[1] * pfVar6[9] + *pfVar5 * pfVar6[8];
  tAB.row[2].v.v[1] = pfVar5[6] * pfVar6[10] + pfVar5[5] * pfVar6[9] + pfVar5[4] * pfVar6[8];
  tAB.row[2].v.v[2] = pfVar5[10] * pfVar6[10] + pfVar5[9] * pfVar6[9] + pfVar5[8] * pfVar6[8];
  normal.v[1] = pfVar6[0xd] - pfVar5[0xd];
  normal.v[2] = pfVar6[0xe] - pfVar5[0xe];
  normal.v[0] = pfVar6[0xc] - pfVar5[0xc];
  tAB.row[3].v.v[0] = normal.v[2] * pfVar5[2] + normal.v[0] * *pfVar5 + normal.v[1] * pfVar5[1];
  tAB.row[3].v.v[1] = normal.v[2] * pfVar5[6] + normal.v[0] * pfVar5[4] + normal.v[1] * pfVar5[5];
  tAB.row[3].v.v[2] = normal.v[2] * pfVar5[10] + normal.v[0] * pfVar5[8] + normal.v[1] * pfVar5[9];
  pMVar1 = p->model1->frame;
  bVar4 = McdVanillaOverlapOBBs
                    (&separation,&normal,&PN,&dims,(float)(lVar15 + (longdouble)(float)lVar14),inR1,
                     inR2,&tAB);
  MVar11 = 0;
  if (bVar4) {
    iVar9 = 0x2f;
    do {
      iVar9 = iVar9 + -0x18;
    } while (iVar9 != -1);
    plVar12 = footprint;
    verts = plVar12;
    BoxBoxIntersect(&verts,&tAB,inR1,inR2,pMVar1->mScale);
    uVar3 = ((int)verts - (int)plVar12 >> 2) * -0x55555555;
    result->contactCount = 0;
    pMVar10 = result->contacts;
    result->normal[0] = normal.v[2] * pfVar5[8] + normal.v[0] * *pfVar5 + normal.v[1] * pfVar5[4];
    result->normal[1] = normal.v[2] * pfVar5[9] + normal.v[0] * pfVar5[1] + normal.v[1] * pfVar5[5];
    result->normal[2] = normal.v[2] * pfVar5[10] + normal.v[0] * pfVar5[2] + normal.v[1] * pfVar5[6]
    ;
    uVar13 = 0;
    if (uVar3 != 0) {
      do {
                    
        fVar2 = (normal.v[2] * plVar12->v[2] +
                plVar12->v[0] * normal.v[0] + normal.v[1] * plVar12->v[1]) - PN;
        if (fVar2 < separation * 0.01) {
          pMVar10->position[0] =
               plVar12->v[0] * *pfVar5 + plVar12->v[1] * pfVar5[4] + plVar12->v[2] * pfVar5[8] +
               pfVar5[0xc];
          pMVar10->position[1] =
               pfVar5[9] * plVar12->v[2] + pfVar5[5] * plVar12->v[1] + pfVar5[1] * plVar12->v[0] +
               pfVar5[0xd];
          pMVar10->position[2] =
               pfVar5[10] * plVar12->v[2] + pfVar5[6] * plVar12->v[1] + pfVar5[2] * plVar12->v[0] +
               pfVar5[0xe];
          pMVar10->separation = fVar2;
          pMVar10->dims = dims;
          pMVar10->normal[0] = result->normal[0];
          pMVar10->normal[1] = result->normal[1];
          pMVar10->normal[2] = result->normal[2];
          result->contactCount = result->contactCount + 1;
          pMVar10 = pMVar10 + 1;
        }
        uVar13 = uVar13 + 1;
        plVar12 = plVar12 + 1;
      } while (uVar13 < uVar3);
    }
    MVar11 = 1;
    result->touch = 1;
  }
  return MVar11;
}

/* ---- McdBoxBoxSafeTime (exported) ---- */
int McdBoxBoxSafeTime(McdModelPair *p,MeReal maxTime,McdSafeTimeResult *result)

{
  int iVar1;
  int iVar2;
  float fVar3;
  float fVar4;
  float fVar5;
  float fVar6;
  float fVar7;
  float fVar8;
  float fVar9;
  float fVar10;
  float fVar11;
  float fVar12;
  float fVar13;
  lsVec3 *plVar14;
  lsVec3 *plVar15;
  float *pfVar16;
  float *pfVar17;
  MeReal *pMVar18;
  MeReal *pMVar19;
  undefined4 uVar20;
  undefined4 uVar21;
  float *pfVar22;
  float *pfVar23;
  int iVar24;
  int iVar25;
  MeReal q0q2_1;
  MeReal q0q1_1;
  MeReal q0t2;
  MeReal q3sq_1;
  MeReal q1sq_1;
  MeReal q1q2;
  MeReal q0q2;
  MeReal q0q1;
  MeReal q3sq;
  MeReal q2sq;
  MeReal q1sq;
  int bIsect;
  MeReal DeltaTime;
  MeReal *ext1;
  MeReal *ext0;
  MeMatrix4Ptr tm1Ptr;
  MeMatrix4Ptr tm0Ptr;
  lsVec3 *W1;
  lsVec3 *W0;
  lsVec3 *V1;
  lsVec3 *V0;
  MeReal T;
  MeReal q1 [4];
  MeReal q0 [4];
  MeReal DqOverDt1 [4];
  MeReal DqOverDt0 [4];
  MeReal tm1i [4] [4];
  MeReal tm0i [4] [4];
  lsVec3 P;

  result->pair = p;
  result->time = maxTime;
  plVar14 = (lsVec3 *)McdModelGetLinearVelocityPtr(p->model1);
  plVar15 = (lsVec3 *)McdModelGetLinearVelocityPtr(p->model2);
  pfVar16 = (float *)McdModelGetAngularVelocityPtr(p->model1);
  pfVar17 = (float *)McdModelGetAngularVelocityPtr(p->model2);
  if ((((plVar14 != (lsVec3 *)0x0) && (plVar15 != (lsVec3 *)0x0)) && (pfVar16 != (float *)0x0)) &&
     (pfVar17 != (float *)0x0)) {
    pMVar18 = (MeReal *)McdModelGetTransformPtr(p->model1);
    pMVar19 = (MeReal *)McdModelGetTransformPtr(p->model2);
    uVar20 = McdModelGetGeometry(p->model1);
    uVar21 = McdModelGetGeometry(p->model2);
    pfVar22 = (float *)McdBoxGetRadii(uVar20);
    pfVar23 = (float *)McdBoxGetRadii(uVar21);
                    
    iVar2 = (int)ROUND(((SQRT(pfVar17[2] * pfVar17[2] +
                              pfVar17[1] * pfVar17[1] + *pfVar17 * *pfVar17) +
                        SQRT(pfVar16[2] * pfVar16[2] + pfVar16[1] * pfVar16[1] + *pfVar16 * *pfVar16
                            )) * maxTime) / McdBoxBoxSafeTime__maxAngle);
    iVar1 = iVar2 + 1;
    fVar3 = maxTime / (float)iVar1;
    tm0i[0][0] = *pMVar18;
    tm0i[0][1] = pMVar18[1];
    tm0i[0][2] = pMVar18[2];
    tm0i[0][3] = pMVar18[3];
    tm0i[1][0] = pMVar18[4];
    tm0i[1][1] = pMVar18[5];
    tm0i[1][2] = pMVar18[6];
    tm0i[1][3] = pMVar18[7];
    tm0i[2][0] = pMVar18[8];
    tm0i[2][1] = pMVar18[9];
    tm0i[2][2] = pMVar18[10];
    tm0i[2][3] = pMVar18[0xb];
    tm0i[3][0] = pMVar18[0xc];
    tm0i[3][1] = pMVar18[0xd];
    tm0i[3][2] = pMVar18[0xe];
    tm0i[3][3] = pMVar18[0xf];
    tm1i[0][0] = *pMVar19;
    tm1i[0][1] = pMVar19[1];
    tm1i[0][2] = pMVar19[2];
    tm1i[0][3] = pMVar19[3];
    tm1i[1][0] = pMVar19[4];
    tm1i[1][1] = pMVar19[5];
    tm1i[1][2] = pMVar19[6];
    tm1i[1][3] = pMVar19[7];
    tm1i[2][0] = pMVar19[8];
    tm1i[2][1] = pMVar19[9];
    tm1i[2][2] = pMVar19[10];
    tm1i[2][3] = pMVar19[0xb];
    tm1i[3][0] = pMVar19[0xc];
    tm1i[3][1] = pMVar19[0xd];
    tm1i[3][2] = pMVar19[0xe];
    tm1i[3][3] = pMVar19[0xf];
    MeQuaternionFromTM(q0,tm0i);
    iVar25 = 0;
    MeQuaternionFromTM(q1,tm1i);
    if (0 < iVar1) {
      do {
        iVar24 = MovingBoxBoxIntersect
                           (pfVar22,(lsTransform *)tm0i,plVar14,pfVar23,(lsTransform *)tm1i,plVar15,
                            fVar3,&T,&P);
        if (iVar24 != 0) {
          result->time = (float)iVar25 * fVar3 + T + 1e-06;
          return 1;
        }
        if (iVar25 < iVar2) {
                    
          fVar4 = ((-q0[1] * *pfVar16 - q0[2] * pfVar16[1]) - q0[3] * pfVar16[2]) * 0.5 * fVar3 +
                  q0[0];
          fVar7 = q1[0] + ((-q1[1] * *pfVar17 - q1[2] * pfVar17[1]) - q1[3] * pfVar17[2]) * 0.5 *
                          fVar3;
          fVar10 = q0[1] + fVar3 * ((q0[3] * pfVar16[1] + q0[0] * *pfVar16) - q0[2] * pfVar16[2]) *
                                   0.5;
          fVar11 = q1[1] + fVar3 * ((q1[3] * pfVar17[1] + q1[0] * *pfVar17) - q1[2] * pfVar17[2]) *
                                   0.5;
          fVar8 = q1[2] + (-q1[3] * *pfVar17 + q1[0] * pfVar17[1] + q1[1] * pfVar17[2]) * 0.5 *
                          fVar3;
          fVar6 = fVar3 * (q0[1] * pfVar16[2] + q0[0] * pfVar16[1] + -q0[3] * *pfVar16) * 0.5 +
                  q0[2];
          fVar12 = q0[3] + fVar3 * (q0[0] * pfVar16[2] + (q0[2] * *pfVar16 - q0[1] * pfVar16[1])) *
                                   0.5;
          fVar9 = q1[3] + ((q1[2] * *pfVar17 - q1[1] * pfVar17[1]) + q1[0] * pfVar17[2]) * 0.5 *
                          fVar3;
                    
          fVar5 = 1.0 / SQRT(fVar12 * fVar12 + fVar6 * fVar6 + fVar10 * fVar10 + fVar4 * fVar4);
                    
          fVar13 = 1.0 / SQRT(fVar9 * fVar9 + fVar8 * fVar8 + fVar11 * fVar11 + fVar7 * fVar7);
          q1[0] = fVar7 * fVar13;
          q1[2] = fVar8 * fVar13;
          q0[2] = fVar6 * fVar5;
          q0[1] = fVar10 * fVar5;
          q0[0] = fVar4 * fVar5;
          q0[3] = fVar5 * fVar12;
          q1[1] = fVar11 * fVar13;
          q1[3] = fVar13 * fVar9;
                    
          fVar4 = q0[0] + q0[0];
          fVar10 = q0[3] * q0[3];
                    
          fVar8 = q0[2] * q0[2];
          fVar7 = (q0[1] + q0[1]) * q0[3];
          fVar5 = (q0[1] + q0[1]) * q0[2];
          fVar6 = (q0[2] + q0[2]) * q0[3];
          tm0i[0][0] = ((q0[1] * q0[1] + q0[0] * q0[0]) - fVar8) - fVar10;
          fVar9 = q0[0] * q0[0] - q0[1] * q0[1];
          tm0i[1][0] = fVar5 - fVar4 * q0[3];
          tm0i[0][1] = fVar4 * q0[3] + fVar5;
          tm0i[2][0] = fVar4 * q0[2] + fVar7;
          tm0i[0][2] = fVar7 - fVar4 * q0[2];
          tm0i[1][1] = (fVar8 + fVar9) - fVar10;
          tm0i[2][2] = (fVar9 - fVar8) + fVar10;
          tm0i[2][1] = fVar6 - q0[1] * fVar4;
          tm0i[1][2] = fVar6 + q0[1] * fVar4;
          fVar9 = q1[0] + q1[0];
          fVar10 = q1[3] * q1[3];
          fVar4 = q1[2] * q1[2];
          fVar5 = (q1[1] + q1[1]) * q1[2];
          fVar7 = q1[0] * q1[0] - q1[1] * q1[1];
          tm1i[0][0] = ((q1[1] * q1[1] + q1[0] * q1[0]) - fVar4) - fVar10;
          fVar6 = (q1[1] + q1[1]) * q1[3];
          fVar8 = (q1[2] + q1[2]) * q1[3];
          tm1i[0][1] = fVar5 + fVar9 * q1[3];
          tm1i[1][0] = fVar5 - fVar9 * q1[3];
          tm1i[2][0] = fVar9 * q1[2] + fVar6;
          tm1i[0][2] = fVar6 - fVar9 * q1[2];
          tm1i[1][1] = (fVar7 + fVar4) - fVar10;
          tm1i[2][2] = (fVar7 - fVar4) + fVar10;
          tm1i[2][1] = fVar8 - fVar9 * q1[1];
          tm1i[1][2] = fVar8 + fVar9 * q1[1];
          tm0i[3][0] = fVar3 * plVar14->v[0] + tm0i[3][0];
          tm1i[3][0] = fVar3 * plVar15->v[0] + tm1i[3][0];
          tm0i[3][1] = fVar3 * plVar14->v[1] + tm0i[3][1];
          tm1i[3][1] = fVar3 * plVar15->v[1] + tm1i[3][1];
          tm0i[3][2] = fVar3 * plVar14->v[2] + tm0i[3][2];
          tm1i[3][2] = fVar3 * plVar15->v[2] + tm1i[3][2];
        }
        iVar25 = iVar25 + 1;
      } while (iVar25 < iVar1);
    }
  }
  return 0;
}

/* ---- McdBoxBoxRegisterInteraction (exported) ---- */
MeBool McdBoxBoxRegisterInteraction(McdFramework *frame)

{
  McdInteractions interactions;
  
  interactions.helloFn = (McdHelloFn)0x0;
  interactions.goodbyeFn = (McdGoodbyeFn)0x0;
  interactions.intersectFn = McdBoxBoxIntersect;
  interactions.safetimeFn = McdBoxBoxSafeTime;
  interactions.cull = 1;
  interactions.warned = 0;
  McdFrameworkSetInteractions(frame,2,2,&interactions);
  return 1;
}

/* ---- McdVanillaOverlapOBBs (static) ---- */
static bool McdVanillaOverlapOBBs
               (MeReal *outSep,lsVec3 *outN,MeReal *outPN,MeI16 *outDims,MeReal inEps,lsVec3 *inR1,
               lsVec3 *inR2,lsTransform *inT12)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  float fVar5;
  float fVar6;
  float fVar7;
  float fVar8;
  float fVar9;
  uint uVar10;
  MeReal MVar11;
  bool bVar12;
  byte bVar13;
  ushort uVar14;
  uint uVar15;
  lsTransformRow *plVar16;
  uint uVar17;
  int iVar18;
  int iVar19;
  lsTransformRow *plVar20;
  uint uVar21;
  sbyte local_d8;
  int j;
  MeReal nRLen;
  MeU8 normInfo;
  MeReal saveNormD;
  MeReal PN;
  MeReal maxSeparation;
  lsVec3 outVec;
  lsTransform arot;

                    
  plVar16 = inT12->row + 3;
  maxSeparation = -3.4028235e+38;
  saveNormD = 1.0;
  nRLen = 1.0;
  normInfo = '\x0f';
  arot.row[0].v.v[0] = ABS(inT12->row[0].v.v[0]);
  arot.row[0].v.v[1] = ABS(inT12->row[0].v.v[1]);
  arot.row[0].v.v[2] = ABS(inT12->row[0].v.v[2]);
  arot.row[1].v.v[0] = ABS(inT12->row[1].v.v[0]);
  arot.row[1].v.v[1] = ABS(inT12->row[1].v.v[1]);
  arot.row[1].v.v[2] = ABS(inT12->row[1].v.v[2]);
  arot.row[2].v.v[0] = ABS(inT12->row[2].v.v[0]);
  arot.row[2].v.v[1] = ABS(inT12->row[2].v.v[1]);
  arot.row[2].v.v[2] = ABS(inT12->row[2].v.v[2]);
  fVar1 = inR2->v[0];
  fVar2 = inR2->v[1];
  fVar3 = inR2->v[2];
  fVar6 = inT12->row[3].v.v[0];
  fVar4 = ABS(fVar6) -
          (arot.row[0].v.v[0] * fVar1 + inR1->v[0] + arot.row[1].v.v[0] * fVar2 +
          arot.row[2].v.v[0] * fVar3);
  if (fVar4 <= -3.4028235e+38) {
LAB_000110bd:
    fVar6 = inT12->row[3].v.v[1];
    fVar4 = ABS(fVar6) -
            (fVar3 * arot.row[2].v.v[1] +
            fVar2 * arot.row[1].v.v[1] + fVar1 * arot.row[0].v.v[1] + inR1->v[1]);
    if (maxSeparation < fVar4) {
      PN = -inR1->v[1] - fVar4;
      normInfo = '\r';
      saveNormD = fVar6;
      maxSeparation = fVar4;
      if (inEps < fVar4) goto LAB_00011840;
    }
    fVar6 = inT12->row[3].v.v[2];
    fVar1 = ABS(fVar6) -
            (fVar1 * arot.row[0].v.v[2] + inR1->v[2] + fVar2 * arot.row[1].v.v[2] +
            fVar3 * arot.row[2].v.v[2]);
    if (maxSeparation < fVar1) {
      PN = -inR1->v[2] - fVar1;
      normInfo = '\x0e';
      saveNormD = fVar6;
      maxSeparation = fVar1;
      if (inEps < fVar1) goto LAB_00011840;
    }
                    
    fVar1 = inR1->v[0];
    fVar2 = inR1->v[1];
    fVar3 = inR1->v[2];
    fVar6 = (plVar16->v).v[0];
    fVar4 = inT12->row[3].v.v[1];
    fVar5 = inT12->row[3].v.v[2];
    fVar9 = fVar5 * inT12->row[0].v.v[2] +
            fVar4 * inT12->row[0].v.v[1] + fVar6 * inT12->row[0].v.v[0];
    fVar8 = ABS(fVar9);
    fVar7 = fVar8 - (fVar1 * arot.row[0].v.v[0] + inR2->v[0] + fVar2 * arot.row[0].v.v[1] +
                    fVar3 * arot.row[0].v.v[2]);
    if (maxSeparation < fVar7) {
      PN = inR2->v[0] - fVar8;
      normInfo = '\x03';
      saveNormD = fVar9;
      maxSeparation = fVar7;
      if (inEps < fVar7) goto LAB_00011840;
    }
    iVar18 = 1;
    do {
      plVar20 = inT12->row + iVar18;
      fVar7 = fVar5 * (plVar20->v).v[2] + fVar4 * (plVar20->v).v[1] + fVar6 * (plVar20->v).v[0];
      fVar8 = ABS(fVar7);
      fVar9 = fVar8 - (fVar3 * arot.row[iVar18].v.v[2] +
                      fVar1 * arot.row[iVar18].v.v[0] + inR2->v[iVar18] +
                      fVar2 * arot.row[iVar18].v.v[1]);
      if (maxSeparation < fVar9) {
        PN = inR2->v[iVar18] - fVar8;
        normInfo = (char)iVar18 * '\x04' | 3;
        saveNormD = fVar7;
        maxSeparation = fVar9;
        if (inEps < fVar9) goto LAB_00011840;
      }
      plVar20 = inT12->row + iVar18 + 1;
      fVar7 = fVar5 * (plVar20->v).v[2] + fVar4 * (plVar20->v).v[1] + fVar6 * (plVar20->v).v[0];
      fVar8 = ABS(fVar7);
      fVar9 = fVar8 - (fVar1 * arot.row[iVar18 + 1].v.v[0] + inR2->v[iVar18 + 1] +
                       fVar2 * arot.row[iVar18 + 1].v.v[1] + fVar3 * arot.row[iVar18 + 1].v.v[2]);
      if (maxSeparation < fVar9) {
        PN = inR2->v[iVar18 + 1] - fVar8;
        normInfo = (char)iVar18 * '\x04' + 4U | 3;
        saveNormD = fVar7;
        maxSeparation = fVar9;
        if (inEps < fVar9) goto LAB_00011840;
      }
      iVar18 = iVar18 + 2;
    } while (iVar18 < 3);
    j = 0;
    fVar1 = maxSeparation + inEps;
    do {
                    
      uVar17 = 1 << ((byte)j & 0x1f) & 3;
      local_d8 = (sbyte)uVar17;
      uVar15 = 1 << local_d8 & 3;
      iVar19 = 0;
      iVar18 = 0;
      do {
                    
        fVar2 = *(float *)((int)inT12->row[j].v.v + iVar18);
        fVar2 = 1.0 - fVar2 * fVar2;
        if (1e-06 < fVar2) {
                    
          uVar21 = 1 << ((byte)iVar19 & 0x1f) & 3;
          local_d8 = (sbyte)uVar21;
          uVar10 = 1 << local_d8 & 3;
          fVar4 = *(float *)((int)arot.row[uVar17].v.v + iVar18) * inR2->v[uVar15] +
                  *(float *)((int)arot.row[uVar15].v.v + iVar18) * inR2->v[uVar17];
          fVar5 = inT12->row[j].v.v[uVar21] * (plVar16->v).v[uVar10] -
                  inT12->row[j].v.v[uVar10] * (plVar16->v).v[uVar21];
          fVar3 = ABS(fVar5);
          fVar6 = (fVar3 - (arot.row[j].v.v[uVar10] * inR1->v[uVar21] +
                           arot.row[j].v.v[uVar21] * inR1->v[uVar10])) - fVar4;
                    
          fVar2 = SQRT(fVar2);
          if (inEps * fVar2 < fVar6) {
            return false;
          }
          if (fVar1 * fVar2 < fVar6) {
            nRLen = 1.0 / fVar2;
            normInfo = (byte)(j << 2) | (byte)iVar19;
            fVar1 = fVar6 * nRLen;
            PN = nRLen * (fVar4 - fVar3);
            saveNormD = fVar5;
            maxSeparation = fVar1;
          }
        }
        iVar19 = iVar19 + 1;
        iVar18 = iVar18 + 4;
      } while (iVar19 < 3);
      j = j + 1;
    } while (j < 3);
    *outSep = maxSeparation;
    *outPN = PN;
    bVar13 = normInfo & 0xc;
    if (bVar13 == 0xc) {
                    
      uVar15 = normInfo & 3;
      uVar14 = (ushort)(arot.row[0].v.v[uVar15] < 0.0001);
      if (arot.row[1].v.v[uVar15] < 0.0001) {
        uVar14 = uVar14 + 1;
      }
      if (arot.row[2].v.v[uVar15] < 0.0001) {
        uVar14 = uVar14 + 1;
      }
      MVar11 = 1.0;
      outN->v[0] = 0.0;
      outN->v[1] = 0.0;
      outN->v[2] = 0.0;
      if (0.0 <= saveNormD) {
        MVar11 = -1.0;
      }
      outN->v[uVar15] = MVar11;
      *outDims = uVar14 << 8 | 2;
    }
    else if ((normInfo & 3) == 3) {
                    
      bVar13 = bVar13 >> 2;
      uVar14 = (ushort)(arot.row[(char)bVar13].v.v[0] < 0.0001);
      if (arot.row[(char)bVar13].v.v[1] < 0.0001) {
        uVar14 = uVar14 + 1;
      }
      if (arot.row[(char)bVar13].v.v[2] < 0.0001) {
        uVar14 = uVar14 + 1;
      }
      if (saveNormD <= 0.0) {
        plVar16 = inT12->row + (char)bVar13;
        outVec.v[0] = (plVar16->v).v[0];
        outVec.v[1] = (plVar16->v).v[1];
        MVar11 = (plVar16->v).v[2];
      }
      else {
        plVar16 = inT12->row + (char)bVar13;
        outVec.v[0] = -(plVar16->v).v[0];
        outVec.v[1] = -(plVar16->v).v[1];
        MVar11 = -(plVar16->v).v[2];
      }
      outN->v[0] = outVec.v[0];
      outN->v[1] = outVec.v[1];
      outN->v[2] = MVar11;
      *outDims = uVar14 | 0x200;
    }
    else {
      if (0.0 <= saveNormD) {
        uVar17 = 1 << (sbyte)(normInfo & 3) & 3;
        outVec.v[normInfo & 3] = 0.0;
        uVar15 = 1 << (sbyte)uVar17 & 3;
        outVec.v[uVar17] = inT12->row[0].v.v[(normInfo & 0xc) + uVar15];
        MVar11 = -inT12->row[0].v.v[(normInfo & 0xc) + uVar17];
      }
      else {
                    
        uVar17 = 1 << (normInfo & 3) & 3;
        uVar15 = 1 << (sbyte)uVar17 & 3;
        outVec.v[normInfo & 0xffffff03] = 0.0;
        outVec.v[uVar17] = -inT12->row[bVar13 >> 2].v.v[uVar15];
        MVar11 = inT12->row[bVar13 >> 2].v.v[uVar17];
      }
      outVec.v[uVar15] = MVar11;
      outN->v[0] = outVec.v[0];
      outN->v[1] = outVec.v[1];
      outN->v[0] = outVec.v[0] * nRLen;
      outN->v[1] = outVec.v[1] * nRLen;
      outN->v[2] = outVec.v[2] * nRLen;
      *outDims = 0x101;
    }
    bVar12 = true;
  }
  else {
    PN = -inR1->v[0] - fVar4;
    normInfo = '\f';
    saveNormD = fVar6;
    maxSeparation = fVar4;
    if (fVar4 <= inEps) goto LAB_000110bd;
LAB_00011840:
    bVar12 = false;
  }
  return bVar12;
}

/* ---- BoxBoxIntersect (static) ---- */
static void BoxBoxIntersect(lsVec3 **outList,lsTransform *tAB,lsVec3 *inRA,lsVec3 *inRB,MeReal scale)

{
  lsVec3 *plVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  lsVec3 *plVar5;
  lsVec3 *bVert;
  lsVec3 bVertList [24];
  lsTransform tBA;
  
  McdVanillaBoxEdgeBoxIntersect(outList,tAB,inRA,inRB,scale);
  tBA.row[0].v.v[0] = tAB->row[0].v.v[0];
                    
  plVar5 = bVertList;
  tBA.row[0].v.v[1] = tAB->row[1].v.v[0];
  tBA.row[0].v.v[2] = tAB->row[2].v.v[0];
  tBA.row[1].v.v[0] = tAB->row[0].v.v[1];
  tBA.row[1].v.v[1] = tAB->row[1].v.v[1];
  tBA.row[1].v.v[2] = tAB->row[2].v.v[1];
  tBA.row[2].v.v[0] = tAB->row[0].v.v[2];
  tBA.row[2].v.v[1] = tAB->row[1].v.v[2];
  tBA.row[2].v.v[2] = tAB->row[2].v.v[2];
  fVar2 = -tAB->row[3].v.v[1];
  fVar4 = -tAB->row[3].v.v[0];
  fVar3 = -tAB->row[3].v.v[2];
  tBA.row[3].v.v[0] =
       tBA.row[0].v.v[0] * fVar4 + tBA.row[1].v.v[0] * fVar2 + tBA.row[2].v.v[0] * fVar3;
  tBA.row[3].v.v[1] =
       tBA.row[1].v.v[1] * fVar2 + tBA.row[0].v.v[1] * fVar4 + tBA.row[2].v.v[1] * fVar3;
  tBA.row[3].v.v[2] =
       fVar3 * tAB->row[2].v.v[2] + fVar4 * tAB->row[2].v.v[0] + fVar2 * tAB->row[2].v.v[1];
  bVert = plVar5;
  McdVanillaBoxEdgeBoxIntersect(&bVert,&tBA,inRB,inRA,scale);
  for (; plVar5 != bVert; plVar5 = plVar5 + 1) {
    plVar1 = *outList;
    *outList = plVar1 + 1;
    plVar1->v[0] = tAB->row[2].v.v[0] * plVar5->v[2] +
                   tAB->row[1].v.v[0] * plVar5->v[1] + tAB->row[0].v.v[0] * plVar5->v[0] +
                   tAB->row[3].v.v[0];
    plVar1->v[1] = tAB->row[2].v.v[1] * plVar5->v[2] +
                   tAB->row[1].v.v[1] * plVar5->v[1] + tAB->row[0].v.v[1] * plVar5->v[0] +
                   tAB->row[3].v.v[1];
    plVar1->v[2] = tAB->row[2].v.v[2] * plVar5->v[2] +
                   tAB->row[1].v.v[2] * plVar5->v[1] + tAB->row[0].v.v[2] * plVar5->v[0] +
                   tAB->row[3].v.v[2];
  }
  return;
}

/* ---- McdVanillaBoxEdgeBoxIntersect (static) ---- */
static void McdVanillaBoxEdgeBoxIntersect
               (lsVec3 **outList,lsTransform *tAB,lsVec3 *inRA,lsVec3 *inRB,MeReal scale)

{
  lsTransformRow *plVar1;
  float fVar2;
  lsVec3 *plVar3;
  int iVar4;
  MeReal tOut_11;
  MeReal tIn_11;
  MeReal tOut_10;
  MeReal tIn_10;
  MeReal tOut_9;
  MeReal tIn_9;
  MeReal tOut_8;
  MeReal tIn_8;
  MeReal tOut_7;
  MeReal tIn_7;
  MeReal tOut_6;
  MeReal tIn_6;
  MeReal tOut_5;
  MeReal tIn_5;
  MeReal tOut_4;
  MeReal tIn_4;
  MeReal tOut_3;
  MeReal tIn_3;
  MeReal tOut_2;
  MeReal tIn_2;
  MeReal tOut_1;
  MeReal tIn_1;
  MeReal tOut;
  MeReal tIn;
  lsVec3 x;
  lsVec3 invD2;
  lsVec3 invD1;
  lsVec3 invD0;
  lsVec3 d2;
  lsVec3 d1;
  lsVec3 d0;
  
  fVar2 = inRB->v[0];
  d0.v[0] = tAB->row[0].v.v[0] * fVar2;
  d0.v[1] = tAB->row[0].v.v[1] * fVar2;
  d0.v[2] = fVar2 * tAB->row[0].v.v[2];
  fVar2 = inRB->v[1];
  d1.v[1] = tAB->row[1].v.v[1] * fVar2;
  d1.v[2] = tAB->row[1].v.v[2] * fVar2;
  d1.v[0] = fVar2 * tAB->row[1].v.v[0];
  fVar2 = inRB->v[2];
  d2.v[0] = tAB->row[2].v.v[0] * fVar2;
  d2.v[1] = tAB->row[2].v.v[1] * fVar2;
  d2.v[2] = fVar2 * tAB->row[2].v.v[2];
  invD0.v[0] = 0.0;
  if (d0.v[0] != 0.0) {
    invD0.v[0] = 1.0 / d0.v[0];
  }
  invD0.v[1] = 0.0;
  if (d0.v[1] != 0.0) {
    invD0.v[1] = 1.0 / d0.v[1];
  }
  invD0.v[2] = 0.0;
  if (d0.v[2] != 0.0) {
    invD0.v[2] = 1.0 / d0.v[2];
  }
  invD1.v[0] = 0.0;
  if (d1.v[0] != 0.0) {
    invD1.v[0] = 1.0 / d1.v[0];
  }
  invD1.v[1] = 0.0;
  if (d1.v[1] != 0.0) {
    invD1.v[1] = 1.0 / d1.v[1];
  }
  invD1.v[2] = 0.0;
  if (d1.v[2] != 0.0) {
    invD1.v[2] = 1.0 / d1.v[2];
  }
  invD2.v[0] = 0.0;
  if (d2.v[0] != 0.0) {
    invD2.v[0] = 1.0 / d2.v[0];
  }
  invD2.v[1] = 0.0;
  if (d2.v[1] != 0.0) {
    invD2.v[1] = 1.0 / d2.v[1];
  }
  invD2.v[2] = 0.0;
  if (d2.v[2] != 0.0) {
    invD2.v[2] = 1.0 / d2.v[2];
  }
                    
  plVar1 = tAB->row + 3;
  x.v[0] = d1.v[0] + tAB->row[3].v.v[0] + d2.v[0];
  x.v[1] = d2.v[1] + d1.v[1] + tAB->row[3].v.v[1];
  x.v[2] = d1.v[2] + tAB->row[3].v.v[2] + d2.v[2];
  tIn = -1.0;
  tOut = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn,&tOut,&x,&d0,&invD0,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn) && (tIn < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn * d0.v[0] + x.v[0];
      plVar3->v[1] = tIn * d0.v[1] + x.v[1];
      plVar3->v[2] = tIn * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut) && (tOut < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut * d0.v[0] + x.v[0];
      plVar3->v[1] = tOut * d0.v[1] + x.v[1];
      plVar3->v[2] = tOut * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = (tAB->row[3].v.v[2] - d1.v[2]) + d2.v[2];
                    
  x.v[0] = ((plVar1->v).v[0] - d1.v[0]) + d2.v[0];
  x.v[1] = (tAB->row[3].v.v[1] - d1.v[1]) + d2.v[1];
  tIn_1 = -1.0;
  tOut_1 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_1,&tOut_1,&x,&d0,&invD0,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_1) && (tIn_1 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_1 * d0.v[0] + x.v[0];
      plVar3->v[1] = tIn_1 * d0.v[1] + x.v[1];
      plVar3->v[2] = tIn_1 * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_1) && (tOut_1 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_1 * d0.v[0] + x.v[0];
      plVar3->v[1] = tOut_1 * d0.v[1] + x.v[1];
      plVar3->v[2] = tOut_1 * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = (d1.v[2] + tAB->row[3].v.v[2]) - d2.v[2];
                    
  x.v[0] = (d1.v[0] + (plVar1->v).v[0]) - d2.v[0];
  x.v[1] = (d1.v[1] + tAB->row[3].v.v[1]) - d2.v[1];
  tIn_2 = -1.0;
  tOut_2 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_2,&tOut_2,&x,&d0,&invD0,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_2) && (tIn_2 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_2 * d0.v[0] + x.v[0];
      plVar3->v[1] = tIn_2 * d0.v[1] + x.v[1];
      plVar3->v[2] = tIn_2 * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_2) && (tOut_2 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_2 * d0.v[0] + x.v[0];
      plVar3->v[1] = tOut_2 * d0.v[1] + x.v[1];
      plVar3->v[2] = tOut_2 * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = (tAB->row[3].v.v[2] - d1.v[2]) - d2.v[2];
                    
  x.v[0] = ((plVar1->v).v[0] - d1.v[0]) - d2.v[0];
  x.v[1] = (tAB->row[3].v.v[1] - d1.v[1]) - d2.v[1];
  tIn_3 = -1.0;
  tOut_3 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_3,&tOut_3,&x,&d0,&invD0,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_3) && (tIn_3 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_3 * d0.v[0] + x.v[0];
      plVar3->v[1] = tIn_3 * d0.v[1] + x.v[1];
      plVar3->v[2] = tIn_3 * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_3) && (tOut_3 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_3 * d0.v[0] + x.v[0];
      plVar3->v[1] = tOut_3 * d0.v[1] + x.v[1];
      plVar3->v[2] = tOut_3 * d0.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = d0.v[2] + tAB->row[3].v.v[2] + d2.v[2];
                    
  x.v[0] = d0.v[0] + (plVar1->v).v[0] + d2.v[0];
  x.v[1] = d0.v[1] + tAB->row[3].v.v[1] + d2.v[1];
  tIn_4 = -1.0;
  tOut_4 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_4,&tOut_4,&x,&d1,&invD1,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_4) && (tIn_4 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_4 * d1.v[0] + x.v[0];
      plVar3->v[1] = tIn_4 * d1.v[1] + x.v[1];
      plVar3->v[2] = tIn_4 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_4) && (tOut_4 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_4 * d1.v[0] + x.v[0];
      plVar3->v[1] = tOut_4 * d1.v[1] + x.v[1];
      plVar3->v[2] = tOut_4 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = (tAB->row[3].v.v[2] - d0.v[2]) + d2.v[2];
                    
  x.v[0] = ((plVar1->v).v[0] - d0.v[0]) + d2.v[0];
  x.v[1] = (tAB->row[3].v.v[1] - d0.v[1]) + d2.v[1];
  tIn_5 = -1.0;
  tOut_5 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_5,&tOut_5,&x,&d1,&invD1,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_5) && (tIn_5 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_5 * d1.v[0] + x.v[0];
      plVar3->v[1] = tIn_5 * d1.v[1] + x.v[1];
      plVar3->v[2] = tIn_5 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_5) && (tOut_5 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_5 * d1.v[0] + x.v[0];
      plVar3->v[1] = tOut_5 * d1.v[1] + x.v[1];
      plVar3->v[2] = tOut_5 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = (d0.v[2] + tAB->row[3].v.v[2]) - d2.v[2];
                    
  x.v[0] = (d0.v[0] + (plVar1->v).v[0]) - d2.v[0];
  x.v[1] = (d0.v[1] + tAB->row[3].v.v[1]) - d2.v[1];
  tIn_6 = -1.0;
  tOut_6 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_6,&tOut_6,&x,&d1,&invD1,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_6) && (tIn_6 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_6 * d1.v[0] + x.v[0];
      plVar3->v[1] = tIn_6 * d1.v[1] + x.v[1];
      plVar3->v[2] = tIn_6 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_6) && (tOut_6 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_6 * d1.v[0] + x.v[0];
      plVar3->v[1] = tOut_6 * d1.v[1] + x.v[1];
      plVar3->v[2] = tOut_6 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = (tAB->row[3].v.v[2] - d0.v[2]) - d2.v[2];
                    
  x.v[0] = ((plVar1->v).v[0] - d0.v[0]) - d2.v[0];
  x.v[1] = (tAB->row[3].v.v[1] - d0.v[1]) - d2.v[1];
  tIn_7 = -1.0;
  tOut_7 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_7,&tOut_7,&x,&d1,&invD1,inRA,scale * 1e-06);
  if (iVar4 != 0) {
    if ((-1.0 < tIn_7) && (tIn_7 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tIn_7 * d1.v[0] + x.v[0];
      plVar3->v[1] = tIn_7 * d1.v[1] + x.v[1];
      plVar3->v[2] = tIn_7 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
    if ((-1.0 < tOut_7) && (tOut_7 < 1.0)) {
      plVar3 = *outList;
      plVar3->v[0] = tOut_7 * d1.v[0] + x.v[0];
      plVar3->v[1] = tOut_7 * d1.v[1] + x.v[1];
      plVar3->v[2] = tOut_7 * d1.v[2] + x.v[2];
      *outList = *outList + 1;
    }
  }
  x.v[2] = d0.v[2] + tAB->row[3].v.v[2] + d1.v[2];
                    
  x.v[0] = d0.v[0] + (plVar1->v).v[0] + d1.v[0];
  fVar2 = scale * 1e-06;
  x.v[1] = d0.v[1] + tAB->row[3].v.v[1] + d1.v[1];
  tIn_8 = -1.0;
  tOut_8 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_8,&tOut_8,&x,&d2,&invD2,inRA,fVar2);
  if (iVar4 != 0) {
    plVar3 = *outList;
    plVar3->v[0] = tIn_8 * d2.v[0] + x.v[0];
    plVar3->v[1] = tIn_8 * d2.v[1] + x.v[1];
    plVar3->v[2] = tIn_8 * d2.v[2] + x.v[2];
    plVar3 = *outList;
    *outList = plVar3 + 1;
    plVar3[1].v[0] = tOut_8 * d2.v[0] + x.v[0];
    plVar3[1].v[1] = tOut_8 * d2.v[1] + x.v[1];
    plVar3[1].v[2] = tOut_8 * d2.v[2] + x.v[2];
    *outList = *outList + 1;
  }
                    
  x.v[0] = ((plVar1->v).v[0] - d0.v[0]) + d1.v[0];
  x.v[1] = (tAB->row[3].v.v[1] - d0.v[1]) + d1.v[1];
  x.v[2] = (tAB->row[3].v.v[2] - d0.v[2]) + d1.v[2];
  tIn_9 = -1.0;
  tOut_9 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_9,&tOut_9,&x,&d2,&invD2,inRA,fVar2);
  if (iVar4 != 0) {
    plVar3 = *outList;
    plVar3->v[0] = tIn_9 * d2.v[0] + x.v[0];
    plVar3->v[1] = tIn_9 * d2.v[1] + x.v[1];
    plVar3->v[2] = tIn_9 * d2.v[2] + x.v[2];
    plVar3 = *outList;
    *outList = plVar3 + 1;
    plVar3[1].v[0] = tOut_9 * d2.v[0] + x.v[0];
    plVar3[1].v[1] = tOut_9 * d2.v[1] + x.v[1];
    plVar3[1].v[2] = tOut_9 * d2.v[2] + x.v[2];
    *outList = *outList + 1;
  }
                    
  x.v[0] = (d0.v[0] + (plVar1->v).v[0]) - d1.v[0];
  x.v[1] = (d0.v[1] + tAB->row[3].v.v[1]) - d1.v[1];
  x.v[2] = (d0.v[2] + tAB->row[3].v.v[2]) - d1.v[2];
  tIn_10 = -1.0;
  tOut_10 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_10,&tOut_10,&x,&d2,&invD2,inRA,fVar2);
  if (iVar4 != 0) {
    plVar3 = *outList;
    plVar3->v[0] = tIn_10 * d2.v[0] + x.v[0];
    plVar3->v[1] = tIn_10 * d2.v[1] + x.v[1];
    plVar3->v[2] = tIn_10 * d2.v[2] + x.v[2];
    plVar3 = *outList;
    *outList = plVar3 + 1;
    plVar3[1].v[0] = tOut_10 * d2.v[0] + x.v[0];
    plVar3[1].v[1] = tOut_10 * d2.v[1] + x.v[1];
    plVar3[1].v[2] = tOut_10 * d2.v[2] + x.v[2];
    *outList = *outList + 1;
  }
                    
  x.v[0] = ((plVar1->v).v[0] - d0.v[0]) - d1.v[0];
  x.v[1] = (tAB->row[3].v.v[1] - d0.v[1]) - d1.v[1];
  x.v[2] = (tAB->row[3].v.v[2] - d0.v[2]) - d1.v[2];
  tIn_11 = -1.0;
  tOut_11 = 1.0;
  iVar4 = McdVanillaSegmentCubeIntersect(&tIn_11,&tOut_11,&x,&d2,&invD2,inRA,fVar2);
  if (iVar4 != 0) {
    plVar3 = *outList;
    plVar3->v[0] = tIn_11 * d2.v[0] + x.v[0];
    plVar3->v[1] = tIn_11 * d2.v[1] + x.v[1];
    plVar3->v[2] = tIn_11 * d2.v[2] + x.v[2];
    plVar3 = *outList;
    *outList = plVar3 + 1;
    plVar3[1].v[0] = tOut_11 * d2.v[0] + x.v[0];
    plVar3[1].v[1] = tOut_11 * d2.v[1] + x.v[1];
    plVar3[1].v[2] = tOut_11 * d2.v[2] + x.v[2];
    *outList = *outList + 1;
  }
  return;
}

/* ---- McdVanillaSegmentCubeIntersect (static) ---- */
static int McdVanillaSegmentCubeIntersect
              (MeReal *tInMax,MeReal *tOutMin,lsVec3 *orig,lsVec3 *disp,lsVec3 *invDisp,lsVec3 *inR,
              MeReal eps)

{
  float fVar1;
  float fVar2;
  float fVar3;

  if (eps <= ABS(disp->v[0])) {
    fVar1 = orig->v[0] * invDisp->v[0];
    fVar2 = ABS(invDisp->v[0]) * inR->v[0];
    fVar3 = -fVar1 - fVar2;
    fVar2 = fVar2 - fVar1;
    if (*tInMax < fVar3) {
      *tInMax = fVar3;
    }
    fVar1 = *tOutMin;
    if (fVar2 < fVar1) {
      *tOutMin = fVar2;
      fVar1 = fVar2;
    }
    if (fVar1 < *tInMax) {
      return 0;
    }
  }
  else if (inR->v[0] < ABS(orig->v[0])) {
    return 0;
  }
  if (eps <= ABS(disp->v[1])) {
    fVar1 = orig->v[1] * invDisp->v[1];
    fVar2 = ABS(invDisp->v[1]) * inR->v[1];
    fVar3 = -fVar1 - fVar2;
    fVar2 = fVar2 - fVar1;
    if (*tInMax < fVar3) {
      *tInMax = fVar3;
    }
    fVar1 = *tOutMin;
    if (fVar2 < fVar1) {
      *tOutMin = fVar2;
      fVar1 = fVar2;
    }
    if (fVar1 < *tInMax) {
      return 0;
    }
  }
  else if (inR->v[1] < ABS(orig->v[1])) {
    return 0;
  }
  if (eps <= ABS(disp->v[2])) {
    fVar1 = orig->v[2] * invDisp->v[2];
    fVar2 = ABS(invDisp->v[2]) * inR->v[2];
    fVar3 = -fVar1 - fVar2;
    fVar2 = fVar2 - fVar1;
    if (*tInMax < fVar3) {
      *tInMax = fVar3;
    }
    fVar1 = *tOutMin;
    if (fVar2 < fVar1) {
      *tOutMin = fVar2;
      fVar1 = fVar2;
    }
    if (fVar1 < *tInMax) {
      return 0;
    }
  }
  else if (inR->v[2] < ABS(orig->v[2])) {
    return 0;
  }
  return 1;
}
