/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MeDict.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MeDict.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
MeDictNode * kd_MeDictLookup(MeDict *dict,void *key) KD_MANGLED("MeDictLookup");
MeDictNode * kd_MeDictLowerBound(MeDict *dict,void *key) KD_MANGLED("MeDictLowerBound");
MeDictNode * kd_MeDictUpperBound(MeDict *dict,void *key) KD_MANGLED("MeDictUpperBound");
void kd_MeDictInsert(MeDict *dict,MeDictNode *node,void *key) KD_MANGLED("MeDictInsert");
MeDictNode * kd_MeDictDelete(MeDict *dict,MeDictNode *delete) KD_MANGLED("MeDictDelete");
MeDictNode * kd_MeDictNext(MeDict *dict,MeDictNode *curr) KD_MANGLED("MeDictNext");
void kd_MeDictLoadEnd(MeDictLoad *load) KD_MANGLED("MeDictLoadEnd");
void kd_MeDictMerge(MeDict *dest,MeDict *source) KD_MANGLED("MeDictMerge");
MeDict * kd_MeDictCreate(ulong maxcount,MeDictCompareFn comp) KD_MANGLED("MeDictCreate");
void kd_MeDictSetAllocator(MeDict *dict,MeDictAllocFn al,MeDictFreeFn fr,void *context) KD_MANGLED("MeDictSetAllocator");
void kd_MeDictDestroy(MeDict *dict) KD_MANGLED("MeDictDestroy");
void kd_MeDictFreeNodes(MeDict *dict) KD_MANGLED("MeDictFreeNodes");
void kd_MeDictFree(MeDict *dict) KD_MANGLED("MeDictFree");
MeDict * kd_MeDictInit(MeDict *dict,ulong maxcount,MeDictCompareFn comp) KD_MANGLED("MeDictInit");
void kd_MeDictInitLike(MeDict *dict,MeDict *template) KD_MANGLED("MeDictInitLike");
int kd_MeDictVerify(MeDict *dict) KD_MANGLED("MeDictVerify");
int kd_MeDictSimilar(MeDict *left,MeDict *right) KD_MANGLED("MeDictSimilar");
int kd_MeDictAllocInsert(MeDict *dict,void *key,void *data) KD_MANGLED("MeDictAllocInsert");
void kd_MeDictDeleteFree(MeDict *dict,MeDictNode *node) KD_MANGLED("MeDictDeleteFree");
MeDictNode * kd_MeDictFirst(MeDict *dict) KD_MANGLED("MeDictFirst");
MeDictNode * kd_MeDictLast(MeDict *dict) KD_MANGLED("MeDictLast");
MeDictNode * kd_MeDictPrev(MeDict *dict,MeDictNode *curr) KD_MANGLED("MeDictPrev");
void kd_MeDictAllowDupes(MeDict *dict) KD_MANGLED("MeDictAllowDupes");
ulong kd_MeDictCount(MeDict *dict) KD_MANGLED("MeDictCount");
int kd_MeDictIsEmpty(MeDict *dict) KD_MANGLED("MeDictIsEmpty");
int kd_MeDictIsFull(MeDict *dict) KD_MANGLED("MeDictIsFull");
int kd_MeDictContains(MeDict *dict,MeDictNode *node) KD_MANGLED("MeDictContains");
MeDictNode * kd_MeDictNodeCreate(void *data) KD_MANGLED("MeDictNodeCreate");
MeDictNode * kd_MeDictNodeInit(MeDictNode *dnode,void *data) KD_MANGLED("MeDictNodeInit");
void kd_MeDictNodeDestroy(MeDictNode *dnode) KD_MANGLED("MeDictNodeDestroy");
void * kd_MeDictNodeGet(MeDictNode *dnode) KD_MANGLED("MeDictNodeGet");
void * kd_MeDictNodeGetkey(MeDictNode *dnode) KD_MANGLED("MeDictNodeGetkey");
void kd_MeDictNodePut(MeDictNode *dnode,void *data) KD_MANGLED("MeDictNodePut");
int kd_MeDictNodeIsInADict(MeDictNode *dnode) KD_MANGLED("MeDictNodeIsInADict");
void kd_MeDictProcess(MeDict *dict,void *context,MeDictProcessFn function) KD_MANGLED("MeDictProcess");
void kd_MeDictLoadBegin(MeDictLoad *load,MeDict *dict) KD_MANGLED("MeDictLoadBegin");
void kd_MeDictLoadNext(MeDictLoad *load,MeDictNode *newnode,void *key) KD_MANGLED("MeDictLoadNext");
static MeDictNode * dnode_alloc(void *context);
static void dnode_free(MeDictNode *node,void *context);
static void free_nodes(MeDict *dict,MeDictNode *node,MeDictNode *nil);
static int verify_bintree(MeDict *dict);
static uint verify_redblack(MeDictNode *nil,MeDictNode *root);
static ulong verify_node_count(MeDictNode *nil,MeDictNode *root);
static int verify_dict_has_node(MeDictNode *nil,MeDictNode *root,MeDictNode *node);

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MeDictLookup (exported as kd_MeDictLookup, asm label "MeDictLookup") ---- */
MeDictNode * kd_MeDictLookup(MeDict *dict,void *key)

{
  MeDict *pMVar1;
  MeDict *pMVar2;
  int iVar3;
  MeDictNode *saved;

  pMVar2 = (MeDict *)(dict->nilnode).left;
  while( true ) {
    while( true ) {
      if (pMVar2 == dict) {
        return (MeDictNode *)0x0;
      }
      iVar3 = (*dict->compare)(key,(pMVar2->nilnode).key);
      if (-1 < (int)iVar3) break;
      pMVar2 = (MeDict *)(pMVar2->nilnode).left;
    }
    if ((int)iVar3 < 1) break;
    pMVar2 = (MeDict *)(pMVar2->nilnode).right;
  }
  if (dict->dupes == 0) {
    return &pMVar2->nilnode;
  }
  do {
    pMVar1 = pMVar2;
    pMVar2 = (MeDict *)(pMVar1->nilnode).left;
    while( true ) {
      if (pMVar2 == dict) {
        return &pMVar1->nilnode;
      }
      iVar3 = (*dict->compare)(key,(pMVar2->nilnode).key);
      if ((int)iVar3 == 0) break;
      pMVar2 = (MeDict *)(pMVar2->nilnode).right;
    }
  } while( true );
}

/* ---- MeDictLowerBound (exported as kd_MeDictLowerBound, asm label "MeDictLowerBound") ---- */
MeDictNode * kd_MeDictLowerBound(MeDict *dict,void *key)

{
  MeDict *pMVar1;
  MeDict *pMVar2;
  int iVar3;

  pMVar1 = (MeDict *)0x0;
  pMVar2 = (MeDict *)(dict->nilnode).left;
  while( true ) {
    while( true ) {
      if (pMVar2 == dict) {
        return &pMVar1->nilnode;
      }
                    
      iVar3 = (*dict->compare)(key,(pMVar2->nilnode).key);
      if (iVar3 < 1) break;
      pMVar2 = (MeDict *)(pMVar2->nilnode).right;
    }
    if ((-1 < iVar3) && (dict->dupes == 0)) break;
    pMVar1 = pMVar2;
    pMVar2 = (MeDict *)(pMVar2->nilnode).left;
  }
  return &pMVar2->nilnode;
}

/* ---- MeDictUpperBound (exported as kd_MeDictUpperBound, asm label "MeDictUpperBound") ---- */
MeDictNode * kd_MeDictUpperBound(MeDict *dict,void *key)

{
  MeDict *pMVar1;
  MeDict *pMVar2;
  int iVar3;

  pMVar2 = (MeDict *)0x0;
  pMVar1 = (MeDict *)(dict->nilnode).left;
  while( true ) {
    while( true ) {
      if (pMVar1 == dict) {
        return &pMVar2->nilnode;
      }
                    
      iVar3 = (*dict->compare)(key,(pMVar1->nilnode).key);
      if (-1 < iVar3) break;
      pMVar1 = (MeDict *)(pMVar1->nilnode).left;
    }
    if ((iVar3 < 1) && (dict->dupes == 0)) break;
    pMVar2 = pMVar1;
    pMVar1 = (MeDict *)(pMVar1->nilnode).right;
  }
  return &pMVar1->nilnode;
}

/* ---- MeDictInsert (exported as kd_MeDictInsert, asm label "MeDictInsert") ---- */
void kd_MeDictInsert(MeDict *dict,MeDictNode *node,void *key)

{
  MeDict *pMVar1;
  MeDictColor MVar2;
  MeDictNode *pMVar3;
  int iVar4;
  MeDict *pMVar5;
  MeDict *pMVar6;
  MeDict *pMVar7;

  iVar4 = -1;
  pMVar1 = (MeDict *)(dict->nilnode).left;
  node->key = key;
  pMVar7 = dict;
  while (pMVar1 != dict) {
    iVar4 = (*dict->compare)(key,(pMVar1->nilnode).key);
    pMVar7 = pMVar1;
    if (iVar4 < 0) {
      pMVar1 = (MeDict *)(pMVar1->nilnode).left;
    }
    else {
      pMVar1 = (MeDict *)(pMVar1->nilnode).right;
    }
  }
  if (iVar4 < 0) {
    (pMVar7->nilnode).left = node;
  }
  else {
    (pMVar7->nilnode).right = node;
  }
  node->parent = &pMVar7->nilnode;
  node->left = &dict->nilnode;
  node->right = &dict->nilnode;
  dict->nodecount = dict->nodecount + 1;
  node->color = kMeDictColorRed;
  MVar2 = (pMVar7->nilnode).color;
  do {
    if (MVar2 != kMeDictColorRed) {
LAB_000101e7:
      ((dict->nilnode).left)->color = kMeDictColorBlack;
      return;
    }
    pMVar1 = (MeDict *)(pMVar7->nilnode).parent;
    pMVar6 = (MeDict *)(pMVar1->nilnode).left;
    if (pMVar7 == pMVar6) {
      pMVar5 = (MeDict *)(pMVar1->nilnode).right;
      if ((pMVar5->nilnode).color != kMeDictColorRed) {
        if ((MeDict *)node == (MeDict *)(pMVar7->nilnode).right) {
                    
          pMVar3 = (((MeDict *)node)->nilnode).left;
          (pMVar7->nilnode).right = pMVar3;
          pMVar3->parent = &pMVar7->nilnode;
          pMVar3 = (pMVar7->nilnode).parent;
          (((MeDict *)node)->nilnode).parent = pMVar3;
          if (pMVar7 == (MeDict *)pMVar3->left) {
            pMVar3->left = node;
          }
          else {
            pMVar3->right = node;
          }
          (((MeDict *)node)->nilnode).left = &pMVar7->nilnode;
          (pMVar7->nilnode).parent = node;
          pMVar6 = (MeDict *)(pMVar1->nilnode).left;
          pMVar7 = (MeDict *)node;
        }
        (pMVar7->nilnode).color = kMeDictColorBlack;
                    
        pMVar3 = (pMVar6->nilnode).right;
        (pMVar1->nilnode).color = kMeDictColorRed;
        pMVar3->parent = (MeDictNode *)pMVar1;
        (pMVar1->nilnode).left = pMVar3;
        pMVar3 = (pMVar1->nilnode).parent;
        (pMVar6->nilnode).parent = pMVar3;
        if (pMVar1 == (MeDict *)pMVar3->right) {
          pMVar3->right = &pMVar6->nilnode;
        }
        else {
          pMVar3->left = &pMVar6->nilnode;
        }
        (pMVar6->nilnode).right = (MeDictNode *)pMVar1;
        goto LAB_00010224;
      }
    }
    else {
      pMVar5 = pMVar6;
      if ((pMVar6->nilnode).color != kMeDictColorRed) {
        if ((MeDict *)node == (MeDict *)(pMVar7->nilnode).left) {
                    
          pMVar3 = (((MeDict *)node)->nilnode).right;
          (pMVar7->nilnode).left = pMVar3;
          pMVar3->parent = &pMVar7->nilnode;
          pMVar3 = (pMVar7->nilnode).parent;
          (((MeDict *)node)->nilnode).parent = pMVar3;
          if (pMVar7 == (MeDict *)pMVar3->right) {
            pMVar3->right = node;
          }
          else {
            pMVar3->left = node;
          }
          (((MeDict *)node)->nilnode).right = &pMVar7->nilnode;
          (pMVar7->nilnode).parent = node;
          pMVar7 = (MeDict *)node;
        }
                    
        pMVar6 = (MeDict *)(pMVar1->nilnode).right;
        (pMVar7->nilnode).color = kMeDictColorBlack;
        pMVar3 = (pMVar6->nilnode).left;
        (pMVar1->nilnode).color = kMeDictColorRed;
        pMVar3->parent = (MeDictNode *)pMVar1;
        (pMVar1->nilnode).right = pMVar3;
        pMVar3 = (pMVar1->nilnode).parent;
        (pMVar6->nilnode).parent = pMVar3;
        if (pMVar1 == (MeDict *)pMVar3->left) {
          pMVar3->left = (MeDictNode *)pMVar6;
        }
        else {
          pMVar3->right = (MeDictNode *)pMVar6;
        }
        (pMVar6->nilnode).left = (MeDictNode *)pMVar1;
LAB_00010224:
        (pMVar1->nilnode).parent = &pMVar6->nilnode;
        goto LAB_000101e7;
      }
    }
    (pMVar7->nilnode).color = kMeDictColorBlack;
    pMVar7 = (MeDict *)(pMVar1->nilnode).parent;
    (pMVar5->nilnode).color = kMeDictColorBlack;
    (pMVar1->nilnode).color = kMeDictColorRed;
    MVar2 = (pMVar7->nilnode).color;
    node = (MeDictNode *)pMVar1;
  } while( true );
}

/* ---- MeDictDelete (exported as kd_MeDictDelete, asm label "MeDictDelete") ---- */
MeDictNode * kd_MeDictDelete(MeDict *dict,MeDictNode *delete)

{
  MeDictColor MVar1;
  MeDictNode *pMVar2;
  MeDictNode *pMVar3;
  MeDictNode *pMVar4;
  MeDictNode *pMVar5;
  MeDictNode *child;

  pMVar4 = delete->parent;
  child = delete->left;
  if ((MeDict *)child == dict) {
LAB_000105a7:
    child = delete->right;
  }
  else {
    if ((MeDict *)delete->right != dict) {
                    
      pMVar3 = kd_MeDictNext(dict,delete);
      pMVar5 = pMVar3->parent;
      child = pMVar3->right;
      MVar1 = pMVar3->color;
      pMVar2 = pMVar5->left;
      child->parent = pMVar5;
      if (pMVar2 == pMVar3) {
        pMVar5->left = child;
      }
      else {
        pMVar5->right = child;
      }
      pMVar5 = delete->left;
      pMVar2 = delete->right;
      pMVar3->parent = pMVar4;
      pMVar3->left = pMVar5;
      pMVar5->parent = pMVar3;
      pMVar3->color = delete->color;
      pMVar3->right = pMVar2;
      pMVar2->parent = pMVar3;
      delete->color = MVar1;
      if (pMVar4->left == delete) {
        pMVar4->left = pMVar3;
      }
      else {
        pMVar4->right = pMVar3;
      }
      goto LAB_0001034a;
    }
    if ((MeDict *)child == dict) goto LAB_000105a7;
  }
  pMVar5 = pMVar4->left;
  child->parent = pMVar4;
  if (delete == pMVar5) {
    pMVar4->left = child;
  }
  else {
    pMVar4->right = child;
  }
LAB_0001034a:
  delete->parent = (MeDictNode *)0x0;
  delete->right = (MeDictNode *)0x0;
  delete->left = (MeDictNode *)0x0;
  dict->nodecount = dict->nodecount - 1;
  if (delete->color == kMeDictColorBlack) {
                    
    pMVar4 = (dict->nilnode).left;
    pMVar4->color = kMeDictColorRed;
    if (child->color == kMeDictColorBlack) {
      do {
        pMVar4 = child->parent;
        pMVar5 = pMVar4->left;
        if (child == pMVar5) {
          pMVar5 = pMVar4->right;
          if (pMVar5->color == kMeDictColorRed) {
                    
            pMVar2 = pMVar5->left;
            pMVar5->color = kMeDictColorBlack;
            pMVar2->parent = pMVar4;
            pMVar4->right = pMVar2;
            pMVar2 = pMVar4->parent;
            pMVar4->color = kMeDictColorRed;
            pMVar5->parent = pMVar2;
            if (pMVar4 == pMVar2->left) {
              pMVar2->left = pMVar5;
            }
            else {
              pMVar2->right = pMVar5;
            }
            pMVar5->left = pMVar4;
            pMVar4->parent = pMVar5;
            pMVar5 = pMVar4->right;
          }
          pMVar2 = pMVar5->left;
          if (pMVar2->color == kMeDictColorBlack) {
            pMVar3 = pMVar5->right;
            if (pMVar3->color == kMeDictColorBlack) goto LAB_000103fd;
          }
          else {
            pMVar3 = pMVar5->right;
          }
          if (pMVar3->color == kMeDictColorBlack) {
                    
            pMVar3 = pMVar2->right;
            pMVar2->color = kMeDictColorBlack;
            pMVar3->parent = pMVar5;
            pMVar5->left = pMVar3;
            pMVar3 = pMVar5->parent;
            pMVar5->color = kMeDictColorRed;
            pMVar2->parent = pMVar3;
            if (pMVar5 == pMVar3->right) {
              pMVar3->right = pMVar2;
            }
            else {
              pMVar3->left = pMVar2;
            }
            pMVar2->right = pMVar5;
            pMVar5->parent = pMVar2;
            pMVar5 = pMVar4->right;
            pMVar3 = pMVar5->right;
          }
          pMVar5->color = pMVar4->color;
                    
          pMVar2 = pMVar5->left;
          pMVar3->color = kMeDictColorBlack;
          pMVar2->parent = pMVar4;
          pMVar4->right = pMVar2;
          pMVar2 = pMVar4->parent;
          pMVar4->color = kMeDictColorBlack;
          pMVar5->parent = pMVar2;
          if (pMVar4 == pMVar2->left) {
            pMVar2->left = pMVar5;
          }
          else {
            pMVar2->right = pMVar5;
          }
          pMVar5->left = pMVar4;
          pMVar4->parent = pMVar5;
          break;
        }
        if (pMVar5->color == kMeDictColorRed) {
                    
          pMVar2 = pMVar5->right;
          pMVar5->color = kMeDictColorBlack;
          pMVar2->parent = pMVar4;
          pMVar4->left = pMVar2;
          pMVar2 = pMVar4->parent;
          pMVar4->color = kMeDictColorRed;
          pMVar5->parent = pMVar2;
          if (pMVar4 == pMVar2->right) {
            pMVar2->right = pMVar5;
          }
          else {
            pMVar2->left = pMVar5;
          }
          pMVar5->right = pMVar4;
          pMVar4->parent = pMVar5;
          pMVar5 = pMVar4->left;
        }
        pMVar2 = pMVar5->right;
        if (pMVar2->color != kMeDictColorBlack) {
          pMVar3 = pMVar5->left;
LAB_00010417:
          if (pMVar3->color == kMeDictColorBlack) {
                    
            pMVar3 = pMVar2->left;
            pMVar2->color = kMeDictColorBlack;
            pMVar3->parent = pMVar5;
            pMVar5->right = pMVar3;
            pMVar3 = pMVar5->parent;
            pMVar5->color = kMeDictColorRed;
            pMVar2->parent = pMVar3;
            if (pMVar5 == pMVar3->left) {
              pMVar3->left = pMVar2;
            }
            else {
              pMVar3->right = pMVar2;
            }
            pMVar2->left = pMVar5;
            pMVar5->parent = pMVar2;
            pMVar5 = pMVar4->left;
            pMVar3 = pMVar5->left;
          }
          pMVar5->color = pMVar4->color;
          pMVar3->color = kMeDictColorBlack;
                    
          pMVar5 = pMVar4->left;
          pMVar4->color = kMeDictColorBlack;
          pMVar2 = pMVar5->right;
          pMVar4->left = pMVar2;
          pMVar2->parent = pMVar4;
          pMVar2 = pMVar4->parent;
          pMVar5->parent = pMVar2;
          if (pMVar4 == pMVar2->right) {
            pMVar2->right = pMVar5;
          }
          else {
            pMVar2->left = pMVar5;
          }
          pMVar5->right = pMVar4;
          pMVar4->parent = pMVar5;
          pMVar4 = (dict->nilnode).left;
          goto LAB_0001038a;
        }
        pMVar3 = pMVar5->left;
        if (pMVar3->color != kMeDictColorBlack) goto LAB_00010417;
LAB_000103fd:
        pMVar5->color = kMeDictColorRed;
        child = pMVar4;
      } while (pMVar4->color == kMeDictColorBlack);
      pMVar4 = (dict->nilnode).left;
    }
LAB_0001038a:
    child->color = kMeDictColorBlack;
    pMVar4->color = kMeDictColorBlack;
  }
  return delete;
}

/* ---- MeDictNext (exported as kd_MeDictNext, asm label "MeDictNext") ---- */
MeDictNode * kd_MeDictNext(MeDict *dict,MeDictNode *curr)

{
  MeDict *pMVar1;
  MeDict *pMVar2;
  bool bVar3;

  pMVar1 = (MeDict *)curr->right;
  if (pMVar1 == dict) {
    pMVar1 = (MeDict *)curr->parent;
    if (pMVar1 != dict) {
      pMVar2 = pMVar1;
      if (curr == (pMVar1->nilnode).right) {
        do {
          pMVar1 = (MeDict *)(pMVar2->nilnode).parent;
          if (pMVar1 == dict) goto LAB_000105e4;
          bVar3 = pMVar2 == (MeDict *)(pMVar1->nilnode).right;
          pMVar2 = pMVar1;
        } while (bVar3);
      }
      if (pMVar1 != dict) {
        return &pMVar1->nilnode;
      }
    }
LAB_000105e4:
    pMVar1 = (MeDict *)0x0;
  }
  else {
    for (pMVar2 = (MeDict *)(pMVar1->nilnode).left; pMVar2 != dict;
        pMVar2 = (MeDict *)(pMVar2->nilnode).left) {
      pMVar1 = pMVar2;
    }
  }
  return &pMVar1->nilnode;
}

/* ---- MeDictLoadEnd (exported as kd_MeDictLoadEnd, asm label "MeDictLoadEnd") ---- */
void kd_MeDictLoadEnd(MeDictLoad *load)

{
  MeDict *pMVar1;
  MeDict *pMVar2;
  MeDictNode *pMVar3;
  MeDict *pMVar4;
  MeDict *pMVar5;
  uint uVar6;
  int iVar7;
  MeDictColor MVar8;
  MeDictNode **ppMVar9;
  MeDict *pMVar10;
  uint baselevel;
  ulong botrowcount;
  MeDict *dict;
  MeDictNode *tree [64];
  
  pMVar1 = load->dictptr;
  ppMVar9 = tree;
                    
  for (iVar7 = 0x40; iVar7 != 0; iVar7 = iVar7 + -1) {
    *ppMVar9 = (MeDictNode *)0x0;
    ppMVar9 = ppMVar9 + 1;
  }
  pMVar10 = (MeDict *)0x0;
  uVar6 = 0xffffffff;
  baselevel = 0;
  do {
    uVar6 = uVar6 >> 1;
    if (uVar6 < pMVar1->nodecount) break;
  } while (uVar6 != 0);
  botrowcount = pMVar1->nodecount - uVar6;
  MVar8 = kMeDictColorRed;
  pMVar4 = (MeDict *)(load->nilnode).left;
  pMVar5 = (MeDict *)tree[0];
  do {
    while( true ) {
      if (pMVar4 == (MeDict *)&load->nilnode) {
        if (pMVar10 == (MeDict *)0x0) {
          pMVar10 = pMVar1;
        }
        uVar6 = 0;
        do {
          if (tree[uVar6] != (MeDictNode *)0x0) {
            tree[uVar6]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[uVar6];
            pMVar10 = (MeDict *)tree[uVar6];
          }
          iVar7 = uVar6 + 1;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          iVar7 = uVar6 + 2;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          iVar7 = uVar6 + 3;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          iVar7 = uVar6 + 4;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          iVar7 = uVar6 + 5;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          iVar7 = uVar6 + 6;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          iVar7 = uVar6 + 7;
          if (tree[iVar7] != (MeDictNode *)0x0) {
            tree[iVar7]->right = &pMVar10->nilnode;
            (pMVar10->nilnode).parent = tree[iVar7];
            pMVar10 = (MeDict *)tree[iVar7];
          }
          uVar6 = uVar6 + 8;
        } while (uVar6 < 0x40);
        (pMVar10->nilnode).parent = &pMVar1->nilnode;
        (pMVar1->nilnode).color = kMeDictColorBlack;
        (pMVar1->nilnode).right = &pMVar1->nilnode;
        (pMVar1->nilnode).left = &pMVar10->nilnode;
        (pMVar10->nilnode).color = kMeDictColorBlack;
        return;
      }
      pMVar2 = (MeDict *)(pMVar4->nilnode).left;
      tree[0] = &pMVar5->nilnode;
      if (pMVar10 == (MeDict *)0x0) break;
LAB_0001066a:
      (pMVar4->nilnode).left = &pMVar10->nilnode;
      (pMVar10->nilnode).parent = &pMVar4->nilnode;
      (pMVar4->nilnode).color = MVar8 + kMeDictColorBlack & kMeDictColorBlack;
      tree[MVar8] = &pMVar4->nilnode;
      pMVar10 = (MeDict *)0x0;
      MVar8 = baselevel;
      pMVar4 = pMVar2;
      pMVar5 = (MeDict *)tree[0];
    }
    botrowcount = botrowcount - 1;
    if (botrowcount == 0xffffffff) {
      MVar8 = kMeDictColorBlack;
      baselevel = 1;
      if (pMVar5 != (MeDict *)0x0) {
        tree[0] = (MeDictNode *)0x0;
        (pMVar5->nilnode).right = &pMVar1->nilnode;
        pMVar10 = pMVar5;
        pMVar3 = tree[1];
        while (pMVar3 != (MeDictNode *)0x0) {
          pMVar3->right = &pMVar10->nilnode;
          (pMVar10->nilnode).parent = tree[MVar8];
          pMVar10 = (MeDict *)tree[MVar8];
          tree[MVar8] = (MeDictNode *)0x0;
          MVar8 = MVar8 + kMeDictColorBlack;
          pMVar3 = tree[MVar8];
        }
        goto LAB_000107f8;
      }
    }
    else {
LAB_000107f8:
      if (pMVar10 != (MeDict *)0x0) goto LAB_0001066a;
    }
    (pMVar4->nilnode).left = &pMVar1->nilnode;
    (pMVar4->nilnode).right = &pMVar1->nilnode;
    (pMVar4->nilnode).color = MVar8 & kMeDictColorBlack;
    pMVar3 = tree[MVar8];
    pMVar10 = pMVar4;
    while (pMVar4 = pMVar2, pMVar5 = (MeDict *)tree[0], pMVar3 != (MeDictNode *)0x0) {
      pMVar3->right = &pMVar10->nilnode;
      (pMVar10->nilnode).parent = tree[MVar8];
      pMVar10 = (MeDict *)tree[MVar8];
      tree[MVar8] = (MeDictNode *)0x0;
      MVar8 = MVar8 + kMeDictColorBlack;
      pMVar3 = tree[MVar8];
    }
  } while( true );
}

/* ---- MeDictMerge (exported as kd_MeDictMerge, asm label "MeDictMerge") ---- */
void kd_MeDictMerge(MeDict *dest,MeDict *source)

{
  MeDictNode *pMVar1;
  MeDictNode **ppMVar2;
  int iVar3;
  MeDict *pMVar4;
  MeDict *pMVar5;
  MeDict *curr;
  MeDictLoad load;

                    
  curr = (MeDict *)(dest->nilnode).left;
  if (curr == dest) {
LAB_000109de:
    curr = (MeDict *)0x0;
  }
  else {
    for (pMVar5 = (MeDict *)(curr->nilnode).left; pMVar5 != dest;
        pMVar5 = (MeDict *)(pMVar5->nilnode).left) {
      curr = pMVar5;
    }
    if (curr == dest) goto LAB_000109de;
  }
                    
  pMVar5 = (MeDict *)(source->nilnode).left;
  if (pMVar5 != source) {
    for (pMVar4 = (MeDict *)(pMVar5->nilnode).left; pMVar4 != source;
        pMVar4 = (MeDict *)(pMVar4->nilnode).left) {
      pMVar5 = pMVar4;
    }
    if (pMVar5 != source) goto LAB_0001091b;
  }
  pMVar5 = (MeDict *)0x0;
LAB_0001091b:
  if (source != dest) {
    pMVar1 = &load.nilnode;
    dest->nodecount = 0;
    load.dictptr = dest;
    load.nilnode.left = pMVar1;
    load.nilnode.right = pMVar1;
    while( true ) {
      while (curr != (MeDict *)0x0) {
        if ((pMVar5 != (MeDict *)0x0) &&
           (iVar3 = (*dest->compare)((curr->nilnode).key,(pMVar5->nilnode).key), -1 < iVar3))
        goto LAB_0001095f;
                    
        pMVar4 = (MeDict *)kd_MeDictNext(dest,&curr->nilnode);
        ppMVar2 = &(load.nilnode.right)->left;
        load.nilnode.right = &curr->nilnode;
                    
        *ppMVar2 = &curr->nilnode;
        (curr->nilnode).left = pMVar1;
        (load.dictptr)->nodecount = (load.dictptr)->nodecount + 1;
        curr = pMVar4;
      }
      if (pMVar5 == (MeDict *)0x0) break;
LAB_0001095f:
                    
      pMVar4 = (MeDict *)kd_MeDictNext(source,&pMVar5->nilnode);
      ppMVar2 = &(load.nilnode.right)->left;
      load.nilnode.right = &pMVar5->nilnode;
                    
      *ppMVar2 = &pMVar5->nilnode;
      (pMVar5->nilnode).left = pMVar1;
      (load.dictptr)->nodecount = (load.dictptr)->nodecount + 1;
      pMVar5 = pMVar4;
    }
    source->nodecount = 0;
    (source->nilnode).left = &source->nilnode;
    (source->nilnode).right = &source->nilnode;
    (source->nilnode).parent = &source->nilnode;
    kd_MeDictLoadEnd(&load);
  }
  return;
}

/* ---- MeDictCreate (exported as kd_MeDictCreate, asm label "MeDictCreate") ---- */
MeDict * kd_MeDictCreate(ulong maxcount,MeDictCompareFn comp)

{
  MeDict *pMVar1;

  pMVar1 = (MeMemoryAPI.create)((int)sizeof(*(MeDict *)0));
  if (pMVar1 != (MeDict *)0x0) {
    pMVar1->compare = comp;
    pMVar1->allocnode = dnode_alloc;
    pMVar1->freenode = dnode_free;
    pMVar1->context = (void *)0x0;
    pMVar1->nodecount = 0;
    (pMVar1->nilnode).left = &pMVar1->nilnode;
    pMVar1->maxcount = maxcount;
    (pMVar1->nilnode).right = &pMVar1->nilnode;
    (pMVar1->nilnode).parent = &pMVar1->nilnode;
    (pMVar1->nilnode).color = kMeDictColorBlack;
    pMVar1->dupes = 0;
  }
  return pMVar1;
}

/* ---- MeDictSetAllocator (exported as kd_MeDictSetAllocator, asm label "MeDictSetAllocator") ---- */
void kd_MeDictSetAllocator(MeDict *dict,MeDictAllocFn al,MeDictFreeFn fr,void *context)

{
  if (al == (MeDictAllocFn)0x0) {
    al = dnode_alloc;
  }
  dict->allocnode = al;
  if (fr == (MeDictFreeFn)0x0) {
    fr = dnode_free;
  }
  dict->freenode = fr;
  dict->context = context;
  return;
}

/* ---- MeDictDestroy (exported as kd_MeDictDestroy, asm label "MeDictDestroy") ---- */
void kd_MeDictDestroy(MeDict *dict)

{
  (MeMemoryAPI.destroy)(dict);
  return;
}

/* ---- MeDictFreeNodes (exported as kd_MeDictFreeNodes, asm label "MeDictFreeNodes") ---- */
void kd_MeDictFreeNodes(MeDict *dict)

{
  MeDict *pMVar1;

  pMVar1 = (MeDict *)(dict->nilnode).left;
  if (pMVar1 != dict) {
    free_nodes(dict,(pMVar1->nilnode).left,&dict->nilnode);
    free_nodes(dict,(pMVar1->nilnode).right,&dict->nilnode);
    (*dict->freenode)((MeDictNode *)pMVar1,dict->context);
  }
  dict->nodecount = 0;
  (dict->nilnode).left = &dict->nilnode;
  (dict->nilnode).right = &dict->nilnode;
  return;
}

/* ---- MeDictFree (exported as kd_MeDictFree, asm label "MeDictFree") ---- */
void kd_MeDictFree(MeDict *dict)

{
  MeDict *pMVar1;
  MeDict *pMVar2;

  pMVar1 = (MeDict *)(dict->nilnode).left;
  if (pMVar1 != dict) {
    pMVar2 = (MeDict *)(pMVar1->nilnode).left;
    if (pMVar2 != dict) {
      free_nodes(dict,(pMVar2->nilnode).left,&dict->nilnode);
      free_nodes(dict,(pMVar2->nilnode).right,&dict->nilnode);
      (*dict->freenode)((MeDictNode *)pMVar2,dict->context);
    }
    pMVar2 = (MeDict *)(pMVar1->nilnode).right;
    if (pMVar2 != dict) {
      free_nodes(dict,(pMVar2->nilnode).left,&dict->nilnode);
      free_nodes(dict,(pMVar2->nilnode).right,&dict->nilnode);
      (*dict->freenode)((MeDictNode *)pMVar2,dict->context);
    }
    (*dict->freenode)((MeDictNode *)pMVar1,dict->context);
  }
  dict->nodecount = 0;
  (dict->nilnode).left = &dict->nilnode;
  (dict->nilnode).right = &dict->nilnode;
  return;
}

/* ---- MeDictInit (exported as kd_MeDictInit, asm label "MeDictInit") ---- */
MeDict * kd_MeDictInit(MeDict *dict,ulong maxcount,MeDictCompareFn comp)

{
  dict->compare = comp;
  dict->allocnode = dnode_alloc;
  dict->freenode = dnode_free;
  dict->context = (void *)0x0;
  dict->nodecount = 0;
  (dict->nilnode).left = &dict->nilnode;
  dict->maxcount = maxcount;
  (dict->nilnode).right = &dict->nilnode;
  (dict->nilnode).parent = &dict->nilnode;
  (dict->nilnode).color = kMeDictColorBlack;
  dict->dupes = 0;
  return dict;
}

/* ---- MeDictInitLike (exported as kd_MeDictInitLike, asm label "MeDictInitLike") ---- */
void kd_MeDictInitLike(MeDict *dict,MeDict *template)

{
  MeDictCompareFn p_Var1;
  int iVar2;
  
  p_Var1 = template->compare;
  (dict->nilnode).left = &dict->nilnode;
  dict->compare = p_Var1;
  dict->allocnode = template->allocnode;
  dict->freenode = template->freenode;
  dict->context = template->context;
  dict->maxcount = template->maxcount;
  iVar2 = template->dupes;
  dict->nodecount = 0;
  (dict->nilnode).right = &dict->nilnode;
  (dict->nilnode).parent = &dict->nilnode;
  (dict->nilnode).color = kMeDictColorBlack;
  dict->dupes = iVar2;
  return;
}

/* ---- MeDictVerify (exported as kd_MeDictVerify, asm label "MeDictVerify") ---- */
int kd_MeDictVerify(MeDict *dict)

{
  MeDict *pMVar1;
  MeDictColor MVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  ulong uVar6;
  ulong uVar7;
  uint uVar8;

  pMVar1 = (MeDict *)(dict->nilnode).left;
  if (((((pMVar1->nilnode).color != kMeDictColorBlack) ||
       ((dict->nilnode).color != kMeDictColorBlack)) || ((MeDict *)(dict->nilnode).right != dict))
     || ((MeDict *)(pMVar1->nilnode).parent != dict)) {
    return 0;
  }
  iVar3 = verify_bintree(dict);
  if (iVar3 == 0) {
    return 0;
  }
                    
  if (pMVar1 == dict) {
    uVar8 = 1;
    goto LAB_00010ca4;
  }
  uVar4 = verify_redblack(&dict->nilnode,(pMVar1->nilnode).left);
  uVar5 = verify_redblack(&dict->nilnode,(pMVar1->nilnode).right);
  if ((uVar4 != 0) && (uVar5 != 0)) {
    uVar8 = 0;
    if (uVar4 != uVar5) goto LAB_00010ca4;
    MVar2 = (pMVar1->nilnode).color;
    if (MVar2 != kMeDictColorRed) {
      uVar8 = uVar4 + 1 & (MVar2 != kMeDictColorBlack) - 1;
      goto LAB_00010ca4;
    }
    if (((pMVar1->nilnode).left)->color == kMeDictColorBlack) {
      uVar8 = (((pMVar1->nilnode).right)->color != kMeDictColorBlack) - 1 & uVar4;
      goto LAB_00010ca4;
    }
  }
  uVar8 = 0;
LAB_00010ca4:
  uVar4 = 0;
  if (uVar8 != 0) {
    uVar6 = 0;
    if (pMVar1 != dict) {
      uVar6 = verify_node_count(&dict->nilnode,(pMVar1->nilnode).left);
      uVar7 = verify_node_count(&dict->nilnode,(pMVar1->nilnode).right);
      uVar6 = uVar7 + 1 + uVar6;
    }
    uVar4 = (uint)(uVar6 == dict->nodecount);
  }
  return uVar4;
}

/* ---- MeDictSimilar (exported as kd_MeDictSimilar, asm label "MeDictSimilar") ---- */
int kd_MeDictSimilar(MeDict *left,MeDict *right)

{
  uint uVar1;
  
  if ((((left->compare == right->compare) && (left->allocnode == right->allocnode)) &&
      (left->freenode == right->freenode)) && (left->context == right->context)) {
    uVar1 = (uint)(left->dupes == right->dupes);
  }
  else {
    uVar1 = 0;
  }
  return uVar1;
}

/* ---- MeDictAllocInsert (exported as kd_MeDictAllocInsert, asm label "MeDictAllocInsert") ---- */
int kd_MeDictAllocInsert(MeDict *dict,void *key,void *data)

{
  MeDictNode *node;

  node = (*dict->allocnode)(dict->context);
  if (node != (MeDictNode *)0x0) {
    node->left = (MeDictNode *)0x0;
    node->data = data;
    node->parent = (MeDictNode *)0x0;
    node->right = (MeDictNode *)0x0;
    kd_MeDictInsert(dict,node,key);
  }
  return (uint)(node != (MeDictNode *)0x0);
}

/* ---- MeDictDeleteFree (exported as kd_MeDictDeleteFree, asm label "MeDictDeleteFree") ---- */
void kd_MeDictDeleteFree(MeDict *dict,MeDictNode *node)

{
  kd_MeDictDelete(dict,node);
  (*dict->freenode)(node,dict->context);
  return;
}

/* ---- MeDictFirst (exported as kd_MeDictFirst, asm label "MeDictFirst") ---- */
MeDictNode * kd_MeDictFirst(MeDict *dict)

{
  MeDict *pMVar1;
  MeDict *pMVar2;

  pMVar1 = (MeDict *)(dict->nilnode).left;
  if (pMVar1 != dict) {
    for (pMVar2 = (MeDict *)(pMVar1->nilnode).left; pMVar2 != dict;
        pMVar2 = (MeDict *)(pMVar2->nilnode).left) {
      pMVar1 = pMVar2;
    }
    if (pMVar1 != dict) {
      return &pMVar1->nilnode;
    }
  }
  return (MeDictNode *)0x0;
}

/* ---- MeDictLast (exported as kd_MeDictLast, asm label "MeDictLast") ---- */
MeDictNode * kd_MeDictLast(MeDict *dict)

{
  MeDict *pMVar1;
  MeDict *pMVar2;

  pMVar1 = (MeDict *)(dict->nilnode).left;
  if (pMVar1 != dict) {
    for (pMVar2 = (MeDict *)(pMVar1->nilnode).right; pMVar2 != dict;
        pMVar2 = (MeDict *)(pMVar2->nilnode).right) {
      pMVar1 = pMVar2;
    }
    if (pMVar1 != dict) {
      return &pMVar1->nilnode;
    }
  }
  return (MeDictNode *)0x0;
}

/* ---- MeDictPrev (exported as kd_MeDictPrev, asm label "MeDictPrev") ---- */
MeDictNode * kd_MeDictPrev(MeDict *dict,MeDictNode *curr)

{
  MeDict *pMVar1;
  MeDict *pMVar2;
  bool bVar3;

  pMVar1 = (MeDict *)curr->left;
  if (pMVar1 == dict) {
    pMVar1 = (MeDict *)curr->parent;
    if (pMVar1 != dict) {
      pMVar2 = pMVar1;
      if (curr == (pMVar1->nilnode).left) {
        do {
          pMVar1 = (MeDict *)(pMVar2->nilnode).parent;
          if (pMVar1 == dict) goto LAB_00010e94;
          bVar3 = pMVar2 == (MeDict *)(pMVar1->nilnode).left;
          pMVar2 = pMVar1;
        } while (bVar3);
      }
      if (pMVar1 != dict) {
        return &pMVar1->nilnode;
      }
    }
LAB_00010e94:
    pMVar1 = (MeDict *)0x0;
  }
  else {
    for (pMVar2 = (MeDict *)(pMVar1->nilnode).right; pMVar2 != dict;
        pMVar2 = (MeDict *)(pMVar2->nilnode).right) {
      pMVar1 = pMVar2;
    }
  }
  return &pMVar1->nilnode;
}

/* ---- MeDictAllowDupes (exported as kd_MeDictAllowDupes, asm label "MeDictAllowDupes") ---- */
void kd_MeDictAllowDupes(MeDict *dict)

{
  dict->dupes = 1;
  return;
}

/* ---- MeDictCount (exported as kd_MeDictCount, asm label "MeDictCount") ---- */
ulong kd_MeDictCount(MeDict *dict)

{
  return dict->nodecount;
}

/* ---- MeDictIsEmpty (exported as kd_MeDictIsEmpty, asm label "MeDictIsEmpty") ---- */
int kd_MeDictIsEmpty(MeDict *dict)

{
  return (uint)(dict->nodecount == 0);
}

/* ---- MeDictIsFull (exported as kd_MeDictIsFull, asm label "MeDictIsFull") ---- */
int kd_MeDictIsFull(MeDict *dict)

{
  return (uint)(dict->nodecount == dict->maxcount);
}

/* ---- MeDictContains (exported as kd_MeDictContains, asm label "MeDictContains") ---- */
int kd_MeDictContains(MeDict *dict,MeDictNode *node)

{
  MeDict *pMVar1;
  int iVar2;
  int local_14;
  
  pMVar1 = (MeDict *)(dict->nilnode).left;
  if (pMVar1 == dict) {
    local_14 = 0;
  }
  else {
    local_14 = 0;
    if (((pMVar1 == (MeDict *)node) ||
        (iVar2 = verify_dict_has_node(&dict->nilnode,(pMVar1->nilnode).left,node), iVar2 != 0)) ||
       (iVar2 = verify_dict_has_node(&dict->nilnode,(pMVar1->nilnode).right,node), iVar2 != 0)) {
      local_14 = 1;
    }
  }
  return local_14;
}

/* ---- MeDictNodeCreate (exported as kd_MeDictNodeCreate, asm label "MeDictNodeCreate") ---- */
MeDictNode * kd_MeDictNodeCreate(void *data)

{
  MeDictNode *pMVar1;

  pMVar1 = (MeMemoryAPI.create)((int)sizeof(*(MeDictNode *)0));
  if (pMVar1 != (MeDictNode *)0x0) {
    pMVar1->left = (MeDictNode *)0x0;
    pMVar1->data = data;
    pMVar1->parent = (MeDictNode *)0x0;
    pMVar1->right = (MeDictNode *)0x0;
  }
  return pMVar1;
}

/* ---- MeDictNodeInit (exported as kd_MeDictNodeInit, asm label "MeDictNodeInit") ---- */
MeDictNode * kd_MeDictNodeInit(MeDictNode *dnode,void *data)

{
  dnode->data = data;
  dnode->left = (MeDictNode *)0x0;
  dnode->parent = (MeDictNode *)0x0;
  dnode->right = (MeDictNode *)0x0;
  return dnode;
}

/* ---- MeDictNodeDestroy (exported as kd_MeDictNodeDestroy, asm label "MeDictNodeDestroy") ---- */
void kd_MeDictNodeDestroy(MeDictNode *dnode)

{
  (MeMemoryAPI.destroy)(dnode);
  return;
}

/* ---- MeDictNodeGet (exported as kd_MeDictNodeGet, asm label "MeDictNodeGet") ---- */
void * kd_MeDictNodeGet(MeDictNode *dnode)

{
  return dnode->data;
}

/* ---- MeDictNodeGetkey (exported as kd_MeDictNodeGetkey, asm label "MeDictNodeGetkey") ---- */
void * kd_MeDictNodeGetkey(MeDictNode *dnode)

{
  return dnode->key;
}

/* ---- MeDictNodePut (exported as kd_MeDictNodePut, asm label "MeDictNodePut") ---- */
void kd_MeDictNodePut(MeDictNode *dnode,void *data)

{
  dnode->data = data;
  return;
}

/* ---- MeDictNodeIsInADict (exported as kd_MeDictNodeIsInADict, asm label "MeDictNodeIsInADict") ---- */
int kd_MeDictNodeIsInADict(MeDictNode *dnode)

{
  int iVar1;
  
  iVar1 = 0;
  if (((dnode->parent != (MeDictNode *)0x0) && (dnode->left != (MeDictNode *)0x0)) &&
     (dnode->right != (MeDictNode *)0x0)) {
    iVar1 = 1;
  }
  return iVar1;
}

/* ---- MeDictProcess (exported as kd_MeDictProcess, asm label "MeDictProcess") ---- */
void kd_MeDictProcess(MeDict *dict,void *context,MeDictProcessFn function)

{
  MeDict *pMVar1;
  MeDict *curr;

                    
  curr = (MeDict *)(dict->nilnode).left;
  if (curr != dict) {
    for (pMVar1 = (MeDict *)(curr->nilnode).left; pMVar1 != dict;
        pMVar1 = (MeDict *)(pMVar1->nilnode).left) {
      curr = pMVar1;
    }
    if (curr != dict) goto joined_r0x0001109a;
  }
  curr = (MeDict *)0x0;
joined_r0x0001109a:
  while (curr != (MeDict *)0x0) {
    pMVar1 = (MeDict *)kd_MeDictNext(dict,&curr->nilnode);
    (*function)(dict,&curr->nilnode,context);
    curr = pMVar1;
  }
  return;
}

/* ---- MeDictLoadBegin (exported as kd_MeDictLoadBegin, asm label "MeDictLoadBegin") ---- */
void kd_MeDictLoadBegin(MeDictLoad *load,MeDict *dict)

{
  load->dictptr = dict;
  (load->nilnode).left = &load->nilnode;
  (load->nilnode).right = &load->nilnode;
  return;
}

/* ---- MeDictLoadNext (exported as kd_MeDictLoadNext, asm label "MeDictLoadNext") ---- */
void kd_MeDictLoadNext(MeDictLoad *load,MeDictNode *newnode,void *key)

{
  MeDict *pMVar1;
  MeDictNode *pMVar2;

  pMVar1 = load->dictptr;
  newnode->key = key;
  pMVar2 = (load->nilnode).right;
  (load->nilnode).right = newnode;
  pMVar2->left = newnode;
  newnode->left = &load->nilnode;
  pMVar1->nodecount = pMVar1->nodecount + 1;
  return;
}

/* ---- dnode_alloc (static) ---- */
static MeDictNode * dnode_alloc(void *context)

{
  MeDictNode *pMVar1;
  
  pMVar1 = (MeMemoryAPI.create)((int)sizeof(*(MeDictNode *)0));
  return pMVar1;
}

/* ---- dnode_free (static) ---- */
static void dnode_free(MeDictNode *node,void *context)

{
  (MeMemoryAPI.destroy)(node);
  return;
}

/* ---- free_nodes (static) ---- */
static void free_nodes(MeDict *dict,MeDictNode *node,MeDictNode *nil)

{
  if (node != nil) {
    free_nodes(dict,node->left,nil);
    free_nodes(dict,node->right,nil);
    (*dict->freenode)(node,dict->context);
  }
  return;
}

/* ---- verify_bintree (static) ---- */
static int verify_bintree(MeDict *dict)

{
  MeDict *pMVar1;
  int iVar2;
  MeDict *curr;

                    
  curr = (MeDict *)(dict->nilnode).left;
  if (curr != dict) {
    for (pMVar1 = (MeDict *)(curr->nilnode).left; pMVar1 != dict;
        pMVar1 = (MeDict *)(pMVar1->nilnode).left) {
      curr = pMVar1;
    }
    if (curr != dict) goto LAB_000111e2;
  }
  curr = (MeDict *)0x0;
LAB_000111e2:
  if (dict->dupes == 0) {
    do {
      if (curr == (MeDict *)0x0) {
        return 1;
      }
      pMVar1 = (MeDict *)kd_MeDictNext(dict,&curr->nilnode);
      if (pMVar1 == (MeDict *)0x0) {
        return 1;
      }
      iVar2 = (*dict->compare)((curr->nilnode).key,(pMVar1->nilnode).key);
      curr = pMVar1;
    } while (iVar2 < 0);
  }
  else {
    do {
      if ((curr == (MeDict *)0x0) ||
         (pMVar1 = (MeDict *)kd_MeDictNext(dict,&curr->nilnode), pMVar1 == (MeDict *)0x0)) {
        return 1;
      }
      iVar2 = (*dict->compare)((curr->nilnode).key,(pMVar1->nilnode).key);
      curr = pMVar1;
    } while (iVar2 < 1);
  }
  return 0;
}

/* ---- verify_redblack (static) ---- */
static uint verify_redblack(MeDictNode *nil,MeDictNode *root)

{
  uint uVar1;
  uint uVar2;

  if (root == nil) {
    return 1;
  }
  uVar1 = verify_redblack(nil,root->left);
  uVar2 = verify_redblack(nil,root->right);
  if ((uVar1 != 0) && (uVar2 != 0)) {
    if (uVar1 != uVar2) {
      return 0;
    }
    if (root->color != kMeDictColorRed) {
      return uVar1 + 1 & (root->color != kMeDictColorBlack) - 1;
    }
    if (root->left->color == kMeDictColorBlack) {
      return (root->right->color != kMeDictColorBlack) - 1 & uVar1;
    }
  }
  return 0;
}

/* ---- verify_node_count (static) ---- */
static ulong verify_node_count(MeDictNode *nil,MeDictNode *root)

{
  ulong uVar1;
  ulong uVar2;
  
  uVar1 = 0;
  if (root != nil) {
    uVar1 = verify_node_count(nil,root->left);
    uVar2 = verify_node_count(nil,root->right);
    uVar1 = uVar2 + 1 + uVar1;
  }
  return uVar1;
}

/* ---- verify_dict_has_node (static) ---- */
static int verify_dict_has_node(MeDictNode *nil,MeDictNode *root,MeDictNode *node)

{
  int iVar1;
  int local_14;
  
  if (root == nil) {
    local_14 = 0;
  }
  else {
    local_14 = 0;
    if (((root == node) || (iVar1 = verify_dict_has_node(nil,root->left,node), iVar1 != 0)) ||
       (iVar1 = verify_dict_has_node(nil,root->right,node), iVar1 != 0)) {
      local_14 = 1;
    }
  }
  return local_14;
}
