/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MeProfile_linux.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MeProfile_linux.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- imports needing an explicit declaration --- */
/* clockSpeed */
/* 8 bytes, defined in MeProfile.o; type from its DWARF */
extern MeI64 clockSpeed;

/* frameTime */
/* 24 bytes, defined in MeProfile.o; type from its DWARF */
extern MeProfileTimerResult frameTime;

/* ---- forward declarations ---- */
void kd_MeProfileGetTimerValue(MeProfileTimerResult *result) KD_MANGLED("MeProfileGetTimerValue");
int kd_MeProfileStartHardwareTimer(MeProfileTimerMode *mode) KD_MANGLED("MeProfileStartHardwareTimer");
int kd_MeProfileStopHardwareTimer(void) KD_MANGLED("MeProfileStopHardwareTimer");
int kd_MeProfileCreateHardwareTimer(MeProfileTimerMode mode) KD_MANGLED("MeProfileCreateHardwareTimer");
int kd_MeProfileDestroyHardwareTimer(void) KD_MANGLED("MeProfileDestroyHardwareTimer");
void kd_GetOutputInfo(void) KD_MANGLED("GetOutputInfo");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MeProfileGetTimerValue (exported as kd_MeProfileGetTimerValue, asm label "MeProfileGetTimerValue") ---- */
void kd_MeProfileGetTimerValue(MeProfileTimerResult *result)

{
  undefined8 uVar1;

  uVar1 = rdtsc();
  *(int *)&result->cpuCycles = (int)uVar1;
  *(int *)((kd_iptr)&result->cpuCycles + 4) = (int)((ulonglong)uVar1 >> 0x20);
  *(undefined4 *)&result->count0 = 0;
  *(undefined4 *)((kd_iptr)&result->count0 + 4) = 0;
  *(undefined4 *)&result->count1 = 0;
  *(undefined4 *)((kd_iptr)&result->count1 + 4) = 0;
  return;
}

/* ---- MeProfileStartHardwareTimer (exported as kd_MeProfileStartHardwareTimer, asm label "MeProfileStartHardwareTimer") ---- */
int kd_MeProfileStartHardwareTimer(MeProfileTimerMode *mode)

{
  undefined8 uVar1;

  uVar1 = rdtsc();
  *(int *)&frameTime = (int)uVar1;
  (*(int *)((char *)&frameTime + 0x4)) = (int)((ulonglong)uVar1 >> 0x20);
  (*(int *)((char *)&frameTime + 0x8)) = 0;
  (*(int *)((char *)&frameTime + 0xc)) = 0;
  (*(int *)((char *)&frameTime + 0x10)) = 0;
  (*(int *)((char *)&frameTime + 0x14)) = 0;
  return 0;
}

/* ---- MeProfileStopHardwareTimer (exported as kd_MeProfileStopHardwareTimer, asm label "MeProfileStopHardwareTimer") ---- */
int kd_MeProfileStopHardwareTimer(void)

{
  return 0;
}

/* ---- MeProfileCreateHardwareTimer (exported as kd_MeProfileCreateHardwareTimer, asm label "MeProfileCreateHardwareTimer") ---- */
int kd_MeProfileCreateHardwareTimer(MeProfileTimerMode mode)

{
  *mode.count0Label = "N.A.";
  *mode.count1Label = "N.A.";
  return 0;
}

/* ---- MeProfileDestroyHardwareTimer (exported as kd_MeProfileDestroyHardwareTimer, asm label "MeProfileDestroyHardwareTimer") ---- */
int kd_MeProfileDestroyHardwareTimer(void)

{
  return 0;
}

/* ---- GetOutputInfo (exported as kd_GetOutputInfo, asm label "GetOutputInfo") ---- */
void kd_GetOutputInfo(void)

{
  undefined8 uVar1;
  undefined8 uVar2;
  timeval t;
  MeProfileTimerResult finish;
  MeProfileTimerResult start;
  
  t.tv_sec = 1;
  t.tv_usec = 0;
                    
  uVar1 = rdtsc();
  select(0,(fd_set *)0x0,(fd_set *)0x0,(fd_set *)0x0,(timeval *)&t);
                    
  uVar2 = rdtsc();
  clockSpeed = (uint)uVar2 - (uint)uVar1;
  (*(int *)((char *)&clockSpeed + 0x4)) =
       ((int)((ulonglong)uVar2 >> 0x20) - (int)((ulonglong)uVar1 >> 0x20)) -
       (uint)((uint)uVar2 < (uint)uVar1);
  return;
}
