/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MeSimpleFile.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MeSimpleFile.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
char * kd_MeLoadWholeFileHandle(int handle,int *size) KD_MANGLED("MeLoadWholeFileHandle");
void kd_MeSaveWholeFileHandle(int handle,char *data,int size) KD_MANGLED("MeSaveWholeFileHandle");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MeLoadWholeFileHandle (exported as kd_MeLoadWholeFileHandle, asm label "MeLoadWholeFileHandle") ---- */
char * kd_MeLoadWholeFileHandle(int handle,int *size)

{
  uint uVar1;
  char *pcVar2;
  uint uVar3;
  void *destination;

  uVar1 = MeLseek(handle,0,2);
  pcVar2 = (MeMemoryAPI.create)(uVar1);
  MeInfo(0x27,"Reading: file size %d bytes");
  MeLseek(handle,0,0);
  uVar3 = MeRead(handle,pcVar2,uVar1);
  if (uVar3 != uVar1) {
    MeWarning(0,"MeLoadWholeFile bad length: size: %d, read: %d");
  }
  MeClose(handle);
  *size = uVar3;
  return pcVar2;
}

/* ---- MeSaveWholeFileHandle (exported as kd_MeSaveWholeFileHandle, asm label "MeSaveWholeFileHandle") ---- */
void kd_MeSaveWholeFileHandle(int handle,char *data,int size)

{
  MeInfo(0x27,"MeSaveWholeFile: file size %d bytes");
  MeWrite(handle,data,size);
  return;
}
