/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/IxSphereSphere.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for IxSphereSphere.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
int kd_McdSphereSphereIntersect(McdModelPair *p,McdIntersectResult *result) KD_MANGLED("McdSphereSphereIntersect");
int kd_McdSphereSphereSafeTime(McdModelPair *p,MeReal maxTime,McdSafeTimeResult *result) KD_MANGLED("McdSphereSphereSafeTime");
MeBool kd_McdSphereSphereRegisterInteraction(McdFramework *frame) KD_MANGLED("McdSphereSphereRegisterInteraction");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- McdSphereSphereIntersect (exported as kd_McdSphereSphereIntersect, asm label "McdSphereSphereIntersect") ---- */
int kd_McdSphereSphereIntersect(McdModelPair *p,McdIntersectResult *result)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  McdContact *pMVar5;
  float fVar6;
  float fVar7;
  void *pvVar8;
  void *pvVar9;
  void *pvVar10;
  void *pvVar11;
  int iVar12;
  float fVar13;
  float fVar14;
  float fVar15;
  float fVar16;
  MeReal rA;
  MeReal eps;
  lsTransform *tA;
  lsVec3 normal;

  pvVar8 = McdModelGetTransformPtr(p->model1);
  pvVar9 = McdModelGetTransformPtr(p->model2);
  fVar13 = McdModelGetContactTolerance(p->model1);
  fVar14 = McdModelGetContactTolerance(p->model2);
  pvVar10 = McdModelGetGeometry(p->model1);
  pvVar11 = McdModelGetGeometry(p->model2);
  result->contactCount = 0;
  result->touch = 0;
  fVar15 = McdSphereGetRadius(pvVar10);
  fVar16 = McdSphereGetRadius(pvVar11);
  fVar1 = fVar15 + fVar16;
  fVar7 = *(float *)((kd_iptr)pvVar8 + 0x30) - *(float *)((kd_iptr)pvVar9 + 0x30);
  fVar4 = *(float *)((kd_iptr)pvVar8 + 0x34) - *(float *)((kd_iptr)pvVar9 + 0x34);
  fVar3 = *(float *)((kd_iptr)pvVar8 + 0x38) - *(float *)((kd_iptr)pvVar9 + 0x38);
  fVar2 = fVar7 * fVar7 + fVar4 * fVar4 + fVar3 * fVar3;
  fVar6 = 0.0;
  if (fVar2 == 0.0) {
    normal.v[0] = 0.0;
    normal.v[1] = 0.0;
    normal.v[2] = 1.0;
  }
  else {
    fVar2 = SQRT(fVar2);
    if (fVar2 != 0.0) {
      fVar6 = 1.0 / fVar2;
    }
    normal.v[0] = fVar7 * fVar6;
    normal.v[1] = fVar4 * fVar6;
    normal.v[2] = fVar6 * fVar3;
  }
  iVar12 = 0;
  if (fVar2 - fVar1 <= fVar14 + fVar13) {
    if (result->contactMaxCount < 1) {
      result->contactCount = 0;
    }
    else {
                    
      fVar6 = 0.0;
      result->contacts->dims = 0x303;
      pMVar5 = result->contacts;
      pMVar5->normal[0] = normal.v[0];
      pMVar5->normal[1] = normal.v[1];
      pMVar5->normal[2] = normal.v[2];
      result->contacts->separation = fVar2 - fVar1;
      if (fVar1 != 0.0) {
        fVar6 = 1.0 / fVar1;
      }
      fVar16 = fVar16 * fVar6;
      pMVar5 = result->contacts;
      fVar6 = fVar6 * fVar15;
      fVar1 = *(float *)((kd_iptr)pvVar8 + 0x34);
      fVar2 = *(float *)((kd_iptr)pvVar8 + 0x38);
      fVar3 = *(float *)((kd_iptr)pvVar9 + 0x34);
      fVar4 = *(float *)((kd_iptr)pvVar9 + 0x38);
      pMVar5->position[0] =
           fVar16 * *(float *)((kd_iptr)pvVar8 + 0x30) + fVar6 * *(float *)((kd_iptr)pvVar9 + 0x30);
      pMVar5->position[1] = fVar16 * fVar1 + fVar6 * fVar3;
      pMVar5->position[2] = fVar16 * fVar2 + fVar6 * fVar4;
      result->normal[0] = normal.v[0];
      result->normal[1] = normal.v[1];
      result->normal[2] = normal.v[2];
      result->contactCount = 1;
    }
    iVar12 = 1;
    result->touch = 1;
  }
  return iVar12;
}

/* ---- McdSphereSphereSafeTime (exported as kd_McdSphereSphereSafeTime, asm label "McdSphereSphereSafeTime") ---- */
int kd_McdSphereSphereSafeTime(McdModelPair *p,MeReal maxTime,McdSafeTimeResult *result)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  float fVar5;
  float fVar6;
  float fVar7;
  float fVar8;
  float fVar9;
  float fVar10;
  float fVar11;
  float fVar12;
  float *pfVar13;
  void *pvVar14;
  float *pfVar15;
  void *pvVar16;
  int iVar17;
  float fVar18;
  float fVar19;
  MeReal radS1;
  McdSphereID geometry2;
  lsVec3 velocity;
  lsVec3 pose;
  lsVec3 posS2;
  lsVec3 posS1;
  lsVec3 velS2;
  lsVec3 velS1;

  result->pair = p;
  result->time = maxTime;
  pfVar13 = McdModelGetLinearVelocityPtr(p->model1);
  pvVar14 = McdModelGetTransformPtr(p->model1);
  pfVar15 = McdModelGetLinearVelocityPtr(p->model2);
  pvVar16 = McdModelGetTransformPtr(p->model2);
  fVar1 = *(float *)((kd_iptr)pvVar14 + 0x30);
  fVar2 = *(float *)((kd_iptr)pvVar14 + 0x34);
  fVar3 = *(float *)((kd_iptr)pvVar14 + 0x38);
  fVar4 = *(float *)((kd_iptr)pvVar16 + 0x30);
  fVar5 = *(float *)((kd_iptr)pvVar16 + 0x34);
  fVar6 = *(float *)((kd_iptr)pvVar16 + 0x38);
  fVar7 = *pfVar13;
  fVar8 = pfVar13[1];
  fVar9 = pfVar13[2];
  fVar10 = *pfVar15;
  fVar11 = pfVar15[1];
  fVar12 = pfVar15[2];
  pvVar14 = McdModelGetGeometry(p->model1);
  pvVar16 = McdModelGetGeometry(p->model2);
  fVar18 = McdSphereGetRadius(pvVar14);
  fVar19 = McdSphereGetRadius(pvVar16);
  fVar10 = fVar10 - fVar7;
  fVar11 = fVar11 - fVar8;
  fVar4 = fVar4 - fVar1;
  fVar5 = fVar5 - fVar2;
  fVar6 = fVar6 - fVar3;
  fVar12 = fVar12 - fVar9;
  iVar17 = 0;
  if (0.001 <= SQRT(fVar10 * fVar10 + fVar11 * fVar11 + fVar12 * fVar12) * maxTime) {
    if (0.0 <= fVar4 * fVar10 + fVar5 * fVar11 + fVar6 * fVar12) {
                    
      result->time = (fVar19 - (SQRT(fVar6 * fVar6 + fVar5 * fVar5 + fVar4 * fVar4) - fVar18)) /
                     SQRT(fVar12 * fVar12 + fVar10 * fVar10 + fVar11 * fVar11);
      iVar17 = 0;
    }
    else {
                    
      iVar17 = 1;
      result->time = ((SQRT(fVar6 * fVar6 + fVar5 * fVar5 + fVar4 * fVar4) - fVar18) - fVar19) /
                     SQRT(fVar12 * fVar12 + fVar11 * fVar11 + fVar10 * fVar10);
    }
  }
  return iVar17;
}

/* ---- McdSphereSphereRegisterInteraction (exported as kd_McdSphereSphereRegisterInteraction, asm label "McdSphereSphereRegisterInteraction") ---- */
MeBool kd_McdSphereSphereRegisterInteraction(McdFramework *frame)

{
  McdInteractions interactions;
  
  interactions.helloFn = (McdHelloFn)0x0;
  interactions.goodbyeFn = (McdGoodbyeFn)0x0;
  interactions.intersectFn = kd_McdSphereSphereIntersect;
  interactions.safetimeFn = kd_McdSphereSphereSafeTime;
  interactions.cull = 0;
  interactions.warned = 0;
  McdFrameworkSetInteractions(frame,1,1,&interactions);
  return 1;
}
