/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/McdPlane.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for McdPlane.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- file-scope statics --- */
/* _ZZ17McdPlaneDebugDrawE4warn  (.data+0x0, 4 bytes) */
/* bytes exact; type from this object's DWARF */
static unsigned char McdPlaneDebugDraw__warn_kdbytes[4] = { 0x01, 0x00, 0x00, 0x00 };
#define McdPlaneDebugDraw__warn (*(int *)(void *)McdPlaneDebugDraw__warn_kdbytes)

/* ---- forward declarations ---- */
MeI16 kd_McdPlaneGetTypeId(void) KD_MANGLED("McdPlaneGetTypeId");
void kd_McdPlaneRegisterType(McdFramework *frame) KD_MANGLED("McdPlaneRegisterType");
McdPlaneID kd_McdPlaneCreate(McdFramework *frame) KD_MANGLED("McdPlaneCreate");
void kd_McdPlaneDestroy(McdGeometryID g) KD_MANGLED("McdPlaneDestroy");
void kd_McdPlaneUpdateAABB(McdGeometryInstanceID ins,MeMatrix4Ptr finalTM,MeBool tight) KD_MANGLED("McdPlaneUpdateAABB");
void kd_McdPlaneGetBSphere(McdGeometry *g,MeReal *center,MeReal *radius) KD_MANGLED("McdPlaneGetBSphere");
void kd_McdPlaneMaximumPoint(McdGeometryInstanceID ins,MeReal *inDir,MeReal *outPoint) KD_MANGLED("McdPlaneMaximumPoint");
MeI16 kd_McdPlaneGetMassProperties(McdGeometry *g,MeVector4 *relTM,MeVector3 *m,MeReal *volume) KD_MANGLED("McdPlaneGetMassProperties");
void kd_McdPlaneGetNormal(McdGeometry *g,MeReal (*_tm) [4],MeReal *_normal) KD_MANGLED("McdPlaneGetNormal");
MeReal kd_McdPlaneGetDistanceToPoint(McdGeometry *g,MeReal (*_tm) [4],MeReal *point) KD_MANGLED("McdPlaneGetDistanceToPoint");
void kd_McdPlaneDebugDraw(McdGeometryID geom,MeReal (*tm) [4],MeReal *colour) KD_MANGLED("McdPlaneDebugDraw");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- McdPlaneGetTypeId (exported as kd_McdPlaneGetTypeId, asm label "McdPlaneGetTypeId") ---- */
MeI16 kd_McdPlaneGetTypeId(void)

{
  return 3;
}

/* ---- McdPlaneRegisterType (exported as kd_McdPlaneRegisterType, asm label "McdPlaneRegisterType") ---- */
void kd_McdPlaneRegisterType(McdFramework *frame)

{
  McdFrameworkRegisterGeometryType
            (frame,3,"McdPlane",kd_McdPlaneDestroy,kd_McdPlaneUpdateAABB,kd_McdPlaneGetBSphere,
             kd_McdPlaneMaximumPoint,kd_McdPlaneGetMassProperties,kd_McdPlaneDebugDraw);
  return;
}

/* ---- McdPlaneCreate (exported as kd_McdPlaneCreate, asm label "McdPlaneCreate") ---- */
McdPlaneID kd_McdPlaneCreate(McdFramework *frame)

{
  McdPlaneID pMVar1;

  pMVar1 = (MeMemoryAPI.createAligned)((int)sizeof(*(McdPlaneID)0),0x10);
  if (pMVar1 != (McdPlaneID)0x0) {
    McdGeometryInit(pMVar1,frame,3);
  }
  return pMVar1;
}

/* ---- McdPlaneDestroy (exported as kd_McdPlaneDestroy, asm label "McdPlaneDestroy") ---- */
void kd_McdPlaneDestroy(McdGeometryID g)

{
  McdGeometryDeinit(g);
  return;
}

/* ---- McdPlaneUpdateAABB (exported as kd_McdPlaneUpdateAABB, asm label "McdPlaneUpdateAABB") ---- */
void kd_McdPlaneUpdateAABB(McdGeometryInstanceID ins,MeMatrix4Ptr finalTM,MeBool tight)

{
  void *pvVar1;
  MeMatrix4Ptr tm;
  MeReal max [3];
  MeReal min [3];

  pvVar1 = McdGeometryInstanceGetTransformPtr(ins);
  ins->min[0] = -3.4028235e+38;
  ins->min[1] = -3.4028235e+38;
  ins->min[2] = -3.4028235e+38;
  ins->max[0] = 3.4028235e+38;
  ins->max[1] = 3.4028235e+38;
  ins->max[2] = 3.4028235e+38;
  if (*(float *)((kd_iptr)pvVar1 + 0x20) <= 0.9999995) {
    if (-0.9999995 <= *(float *)((kd_iptr)pvVar1 + 0x20)) {
      if (*(float *)((kd_iptr)pvVar1 + 0x24) <= 0.9999995) {
        if (-0.9999995 <= *(float *)((kd_iptr)pvVar1 + 0x24)) {
          if (*(float *)((kd_iptr)pvVar1 + 0x28) <= 0.9999995) {
            if (*(float *)((kd_iptr)pvVar1 + 0x28) < -0.9999995) {
              ins->min[2] = *(MeReal *)((kd_iptr)pvVar1 + 0x38);
            }
          }
          else {
            ins->max[2] = *(MeReal *)((kd_iptr)pvVar1 + 0x38);
          }
        }
        else {
          ins->min[1] = *(MeReal *)((kd_iptr)pvVar1 + 0x34);
        }
      }
      else {
        ins->max[1] = *(MeReal *)((kd_iptr)pvVar1 + 0x34);
      }
    }
    else {
      ins->min[0] = *(MeReal *)((kd_iptr)pvVar1 + 0x30);
    }
  }
  else {
    ins->max[0] = *(MeReal *)((kd_iptr)pvVar1 + 0x30);
  }
  if (finalTM != (MeMatrix4Ptr)0x0) {
                    
    min[0] = -3.4028235e+38;
    min[1] = -3.4028235e+38;
    min[2] = -3.4028235e+38;
    max[0] = 3.4028235e+38;
    max[1] = 3.4028235e+38;
    max[2] = 3.4028235e+38;
    if (finalTM[2][0] <= 0.9999995) {
      if (-0.9999995 <= finalTM[2][0]) {
        if (finalTM[2][1] <= 0.9999995) {
          if (-0.9999995 <= finalTM[2][1]) {
            if (finalTM[2][2] <= 0.9999995) {
              if (finalTM[2][2] < -0.9999995) {
                min[2] = finalTM[3][2];
              }
            }
            else {
              max[2] = finalTM[3][2];
            }
          }
          else {
            min[1] = finalTM[3][1];
          }
        }
        else {
          max[1] = finalTM[3][1];
        }
      }
      else {
        min[0] = finalTM[3][0];
      }
    }
    else {
      max[0] = finalTM[3][0];
    }
    if (ins->min[0] < min[0]) {
      min[0] = ins->min[0];
    }
    ins->min[0] = min[0];
    if (ins->min[1] < min[1]) {
      min[1] = ins->min[1];
    }
    ins->min[1] = min[1];
    if (ins->min[2] < min[2]) {
      min[2] = ins->min[2];
    }
    ins->min[2] = min[2];
    if (max[0] < ins->max[0]) {
      max[0] = ins->max[0];
    }
    ins->max[0] = max[0];
    if (max[1] < ins->max[1]) {
      max[1] = ins->max[1];
    }
    ins->max[1] = max[1];
    if (max[2] < ins->max[2]) {
      max[2] = ins->max[2];
    }
    ins->max[2] = max[2];
  }
  return;
}

/* ---- McdPlaneGetBSphere (exported as kd_McdPlaneGetBSphere, asm label "McdPlaneGetBSphere") ---- */
void kd_McdPlaneGetBSphere(McdGeometry *g,MeReal *center,MeReal *radius)

{
  center[2] = 0.0;
  center[1] = 0.0;
  *center = 0.0;
  *radius = 3.4028235e+38;
  return;
}

/* ---- McdPlaneMaximumPoint (exported as kd_McdPlaneMaximumPoint, asm label "McdPlaneMaximumPoint") ---- */
void kd_McdPlaneMaximumPoint(McdGeometryInstanceID ins,MeReal *inDir,MeReal *outPoint)

{
  float fVar1;
  float fVar2;
  void *pvVar3;

  pvVar3 = McdGeometryInstanceGetTransformPtr(ins);
  if (inDir[2] * *(float *)((kd_iptr)pvVar3 + 0x28) +
      inDir[1] * *(float *)((kd_iptr)pvVar3 + 0x24) + *inDir * *(float *)((kd_iptr)pvVar3 + 0x20) <
      0.9999995) {
    fVar1 = inDir[1];
    fVar2 = inDir[2];
    *outPoint = *inDir * 3.4028235e+38;
    outPoint[1] = fVar1 * 3.4028235e+38;
    outPoint[2] = fVar2 * 3.4028235e+38;
  }
  else {
    *outPoint = *(MeReal *)((kd_iptr)pvVar3 + 0x30);
    outPoint[1] = *(MeReal *)((kd_iptr)pvVar3 + 0x34);
    outPoint[2] = *(MeReal *)((kd_iptr)pvVar3 + 0x38);
  }
  return;
}

/* ---- McdPlaneGetMassProperties (exported as kd_McdPlaneGetMassProperties, asm label "McdPlaneGetMassProperties") ---- */
MeI16 kd_McdPlaneGetMassProperties(McdGeometry *g,MeVector4 *relTM,MeVector3 *m,MeReal *volume)

{
  (*m)[0] = 1.0;
  m[1][1] = 1.0;
  m[2][2] = 1.0;
  (*m)[1] = 0.0;
  (*m)[2] = 0.0;
  m[1][0] = 0.0;
  m[1][2] = 0.0;
  m[2][0] = 0.0;
  m[2][1] = 0.0;
  (*relTM)[0] = 1.0;
  (*relTM)[1] = 0.0;
  (*relTM)[2] = 0.0;
  (*relTM)[3] = 0.0;
  relTM[1][0] = 0.0;
  relTM[1][1] = 1.0;
  relTM[1][2] = 0.0;
  relTM[1][3] = 0.0;
  relTM[2][0] = 0.0;
  relTM[2][1] = 0.0;
  relTM[2][2] = 1.0;
  relTM[2][3] = 0.0;
  relTM[3][0] = 0.0;
  relTM[3][1] = 0.0;
  relTM[3][2] = 0.0;
  relTM[3][3] = 1.0;
  return 0;
}

/* ---- McdPlaneGetNormal (exported as kd_McdPlaneGetNormal, asm label "McdPlaneGetNormal") ---- */
void kd_McdPlaneGetNormal(McdGeometry *g,MeReal (*_tm) [4],MeReal *_normal)

{
                    
  if (_tm == (MeReal (*) [4])0x0) {
    *_normal = 0.0;
    _normal[1] = 0.0;
    _normal[2] = 1.0;
  }
  else {
    *_normal = _tm[2][0];
    _normal[1] = _tm[2][1];
    _normal[2] = _tm[2][2];
  }
  return;
}

/* ---- McdPlaneGetDistanceToPoint (exported as kd_McdPlaneGetDistanceToPoint, asm label "McdPlaneGetDistanceToPoint") ---- */
MeReal kd_McdPlaneGetDistanceToPoint(McdGeometry *g,MeReal (*_tm) [4],MeReal *point)

{
  lsVec3 disp;
  lsVec3 normal;
  
  kd_McdPlaneGetNormal(g,_tm,normal.v);
  disp.v[0] = *point;
  disp.v[1] = point[1];
  disp.v[2] = point[2];
  if (_tm != (MeReal (*) [4])0x0) {
    disp.v[0] = disp.v[0] - _tm[3][0];
    disp.v[1] = disp.v[1] - _tm[3][1];
    disp.v[2] = disp.v[2] - _tm[3][2];
  }
  return normal.v[2] * disp.v[2] + normal.v[1] * disp.v[1] + normal.v[0] * disp.v[0];
}

/* ---- McdPlaneDebugDraw (exported as kd_McdPlaneDebugDraw, asm label "McdPlaneDebugDraw") ---- */
void kd_McdPlaneDebugDraw(McdGeometryID geom,MeReal (*tm) [4],MeReal *colour)

{
  if (McdPlaneDebugDraw__warn != 0) {
    MeWarning(0,"McdPlaneDebugDraw: Don\'t know how to draw a plane!");
  }
  McdPlaneDebugDraw__warn = 0;
  return;
}
