/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MdtContact.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MdtContact.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- imports needing an explicit declaration --- */
/* BaseConstraintCreate */
extern void * BaseConstraintCreate(void *);

/* BaseConstraintReset */
extern void BaseConstraintReset(void *);

/* BaseConstraintSetAxis */
extern void BaseConstraintSetAxis(void *, float, float, float);

/* BaseConstraintSetBodies */
extern void BaseConstraintSetBodies(void *, void *, void *);

/* ---- forward declarations ---- */
MdtContactID kd_MdtContactCreate(MdtWorldID w) KD_MANGLED("MdtContactCreate");
void kd_MdtContactReset(MdtContactID c) KD_MANGLED("MdtContactReset");
MdtConstraintID kd_MdtContactQuaConstraint(MdtContactID c) KD_MANGLED("MdtContactQuaConstraint");
MdtContactID kd_MdtConstraintDCastContact(MdtConstraintID c) KD_MANGLED("MdtConstraintDCastContact");
void kd_MdtContactGetPosition(MdtContactID c,MeReal *v) KD_MANGLED("MdtContactGetPosition");
void kd_MdtContactGetNormal(MdtContactID c,MeReal *v) KD_MANGLED("MdtContactGetNormal");
MeReal kd_MdtContactGetPenetration(MdtContactID c) KD_MANGLED("MdtContactGetPenetration");
void kd_MdtContactGetDirection(MdtContactID c,MeReal *v) KD_MANGLED("MdtContactGetDirection");
void kd_MdtContactGetWorldVelocity(MdtContactID c,MeReal *v) KD_MANGLED("MdtContactGetWorldVelocity");
MdtContactParamsID kd_MdtContactGetParams(MdtContactID c) KD_MANGLED("MdtContactGetParams");
MdtContactID kd_MdtContactGetNext(MdtContactID c) KD_MANGLED("MdtContactGetNext");
MdtContactGroupID kd_MdtContactGetContactGroup(MdtContactID c) KD_MANGLED("MdtContactGetContactGroup");
void kd_MdtContactGetRelativeVelocity(MdtContactID c,MeReal *v) KD_MANGLED("MdtContactGetRelativeVelocity");
void kd_MdtContactSetPosition(MdtContactID c,MeReal x,MeReal y,MeReal z) KD_MANGLED("MdtContactSetPosition");
void kd_MdtContactSetNormal(MdtContactID c,MeReal x,MeReal y,MeReal z) KD_MANGLED("MdtContactSetNormal");
void kd_MdtContactSetPenetration(MdtContactID c,MeReal p) KD_MANGLED("MdtContactSetPenetration");
void kd_MdtContactSetParams(MdtContactID c,MdtContactParamsID p) KD_MANGLED("MdtContactSetParams");
void kd_MdtContactSetNext(MdtContactID c,MdtContactID nc) KD_MANGLED("MdtContactSetNext");
void kd_MdtContactSetDirection(MdtContactID c,MeReal x,MeReal y,MeReal z) KD_MANGLED("MdtContactSetDirection");
void kd_MdtContactSetWorldVelocity(MdtContactID c,MeReal x,MeReal y,MeReal z) KD_MANGLED("MdtContactSetWorldVelocity");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */
/* --- exported data symbols --- */
/* MdtContactInvalidID — EXPORTED .rodata symbol, 4 zero bytes */
/* type from its DWARF; the bytes are all zero, so this is byte-exact */
const struct MdtContact *kd_MdtContactInvalidID KD_MANGLED("MdtContactInvalidID");


/* ---- MdtContactCreate (exported as kd_MdtContactCreate, asm label "MdtContactCreate") ---- */
MdtContactID kd_MdtContactCreate(MdtWorldID w)

{
  MdtContactID pMVar1;
  int iVar2;
  MdtContactID pMVar3;

  pMVar1 = BaseConstraintCreate(w);
  pMVar3 = (MdtContactID)0x0;
  if (pMVar1 != (MdtContactID)0x0) {
                    
    (pMVar1->head).tag = 4;
    (pMVar1->head).bclFunction = MdtBclAddContact;
    (pMVar1->head).maxRows = 3;
    pMVar1->nextContact = (MdtContactID)0x0;
    pMVar1->prevContact = (MdtContactID)0x0;
    (pMVar1->head).setBodyFunc = BaseConstraintSetBodies;
    (pMVar1->head).setAxisFunc = BaseConstraintSetAxis;
    iVar2 = MdtConstraintIsEnabled(pMVar1);
    if (iVar2 != 0) {
      MdtConstraintDisable(pMVar1);
    }
    pMVar1->penetration = 0.0;
    pMVar1->cpos[0] = 0.0;
    pMVar1->normal[0] = 0.0;
    pMVar1->worldVel[0] = 0.0;
    pMVar1->cpos[1] = 0.0;
    pMVar1->direction[1] = 0.0;
    pMVar1->worldVel[1] = 0.0;
    pMVar1->cpos[2] = 0.0;
    pMVar1->normal[2] = 0.0;
    pMVar1->direction[2] = 0.0;
    pMVar1->worldVel[2] = 0.0;
    pMVar1->direction[0] = 1.0;
    pMVar1->normal[1] = 1.0;
    pMVar1->nextContact = (MdtContactID)0x0;
    pMVar1->prevContact = (MdtContactID)0x0;
    pMVar1->contactGroup = (MdtContactGroupID)0x0;
    pMVar1->importance = 3.4028235e+38;
    MdtContactParamsReset(&pMVar1->params);
    BaseConstraintReset(pMVar1);
    pMVar3 = pMVar1;
  }
  return pMVar3;
}

/* ---- MdtContactReset (exported as kd_MdtContactReset, asm label "MdtContactReset") ---- */
void kd_MdtContactReset(MdtContactID c)

{
  int iVar1;

  iVar1 = MdtConstraintIsEnabled(c);
  if (iVar1 != 0) {
    MdtConstraintDisable(c);
  }
  c->penetration = 0.0;
  c->cpos[0] = 0.0;
  c->normal[0] = 0.0;
  c->worldVel[0] = 0.0;
  c->cpos[1] = 0.0;
  c->direction[1] = 0.0;
  c->worldVel[1] = 0.0;
  c->cpos[2] = 0.0;
  c->normal[2] = 0.0;
  c->direction[2] = 0.0;
  c->worldVel[2] = 0.0;
  c->direction[0] = 1.0;
  c->normal[1] = 1.0;
  c->nextContact = (MdtContactID)0x0;
  c->prevContact = (MdtContactID)0x0;
  c->contactGroup = (MdtContactGroupID)0x0;
  c->importance = 3.4028235e+38;
  MdtContactParamsReset(&c->params);
  BaseConstraintReset(c);
  return;
}

/* ---- MdtContactQuaConstraint (exported as kd_MdtContactQuaConstraint, asm label "MdtContactQuaConstraint") ---- */
MdtConstraintID kd_MdtContactQuaConstraint(MdtContactID c)

{
  return (MdtConstraintID)c;
}

/* ---- MdtConstraintDCastContact (exported as kd_MdtConstraintDCastContact, asm label "MdtConstraintDCastContact") ---- */
MdtContactID kd_MdtConstraintDCastContact(MdtConstraintID c)

{
  return (MdtContactID)(((c->head).tag != 4) - 1 & (kd_uptr)c);
}

/* ---- MdtContactGetPosition (exported as kd_MdtContactGetPosition, asm label "MdtContactGetPosition") ---- */
void kd_MdtContactGetPosition(MdtContactID c,MeReal *v)

{
  *v = c->cpos[0];
  v[1] = c->cpos[1];
  v[2] = c->cpos[2];
  return;
}

/* ---- MdtContactGetNormal (exported as kd_MdtContactGetNormal, asm label "MdtContactGetNormal") ---- */
void kd_MdtContactGetNormal(MdtContactID c,MeReal *v)

{
  *v = c->normal[0];
  v[1] = c->normal[1];
  v[2] = c->normal[2];
  return;
}

/* ---- MdtContactGetPenetration (exported as kd_MdtContactGetPenetration, asm label "MdtContactGetPenetration") ---- */
MeReal kd_MdtContactGetPenetration(MdtContactID c)

{
  return c->penetration;
}

/* ---- MdtContactGetDirection (exported as kd_MdtContactGetDirection, asm label "MdtContactGetDirection") ---- */
void kd_MdtContactGetDirection(MdtContactID c,MeReal *v)

{
  *v = c->direction[0];
  v[1] = c->direction[1];
  v[2] = c->direction[2];
  return;
}

/* ---- MdtContactGetWorldVelocity (exported as kd_MdtContactGetWorldVelocity, asm label "MdtContactGetWorldVelocity") ---- */
void kd_MdtContactGetWorldVelocity(MdtContactID c,MeReal *v)

{
  *v = c->worldVel[0];
  v[1] = c->worldVel[1];
  v[2] = c->worldVel[2];
  return;
}

/* ---- MdtContactGetParams (exported as kd_MdtContactGetParams, asm label "MdtContactGetParams") ---- */
MdtContactParamsID kd_MdtContactGetParams(MdtContactID c)

{
  return &c->params;
}

/* ---- MdtContactGetNext (exported as kd_MdtContactGetNext, asm label "MdtContactGetNext") ---- */
MdtContactID kd_MdtContactGetNext(MdtContactID c)

{
  return c->nextContact;
}

/* ---- MdtContactGetContactGroup (exported as kd_MdtContactGetContactGroup, asm label "MdtContactGetContactGroup") ---- */
MdtContactGroupID kd_MdtContactGetContactGroup(MdtContactID c)

{
  return c->contactGroup;
}

/* ---- MdtContactGetRelativeVelocity (exported as kd_MdtContactGetRelativeVelocity, asm label "MdtContactGetRelativeVelocity") ---- */
void kd_MdtContactGetRelativeVelocity(MdtContactID c,MeReal *v)

{
  void *pvVar1;
  void *pvVar2;
  MeVector3 vel1;
  MeVector3 vel0;
  MeVector3 pos1;
  MeVector3 pos0;

  pvVar1 = MdtConstraintGetBody(c,0);
  pvVar2 = MdtConstraintGetBody(c,1);
  MdtBodyGetCenterOfMassPosition(pvVar1,pos0);
  pos0[0] = c->cpos[0] - pos0[0];
  pos0[1] = c->cpos[1] - pos0[1];
  pos0[2] = c->cpos[2] - pos0[2];
  MdtBodyGetVelocityAtPoint(pvVar1,c->cpos,vel0);
  if (pvVar2 == (void *)0x0) {
    vel1[2] = 0.0;
    vel1[1] = 0.0;
    vel1[0] = 0.0;
  }
  else {
    MdtBodyGetCenterOfMassPosition(pvVar2,pos1);
    pos1[0] = c->cpos[0] - pos1[0];
    pos1[1] = c->cpos[1] - pos1[1];
    pos1[2] = c->cpos[2] - pos1[2];
    MdtBodyGetVelocityAtPoint(pvVar2,c->cpos,vel1);
  }
  *v = vel0[0] - vel1[0];
  v[1] = vel0[1] - vel1[1];
  v[2] = vel0[2] - vel1[2];
  return;
}

/* ---- MdtContactSetPosition (exported as kd_MdtContactSetPosition, asm label "MdtContactSetPosition") ---- */
void kd_MdtContactSetPosition(MdtContactID c,MeReal x,MeReal y,MeReal z)

{
  c->cpos[0] = x;
  c->cpos[1] = y;
  c->cpos[2] = z;
  return;
}

/* ---- MdtContactSetNormal (exported as kd_MdtContactSetNormal, asm label "MdtContactSetNormal") ---- */
void kd_MdtContactSetNormal(MdtContactID c,MeReal x,MeReal y,MeReal z)

{
  c->normal[0] = x;
  c->normal[1] = y;
  c->normal[2] = z;
  return;
}

/* ---- MdtContactSetPenetration (exported as kd_MdtContactSetPenetration, asm label "MdtContactSetPenetration") ---- */
void kd_MdtContactSetPenetration(MdtContactID c,MeReal p)

{
  c->penetration = p;
  return;
}

/* ---- MdtContactSetParams (exported as kd_MdtContactSetParams, asm label "MdtContactSetParams") ---- */
void kd_MdtContactSetParams(MdtContactID c,MdtContactParamsID p)

{
  int iVar1;
  MdtBclContactParams *pMVar2;
  
  pMVar2 = &c->params;
  for (iVar1 = 0x12; iVar1 != 0; iVar1 = iVar1 + -1) {
    pMVar2->type = p->type;
    p = (MdtContactParamsID)&p->model1;
    pMVar2 = (MdtBclContactParams *)&pMVar2->model1;
  }
  return;
}

/* ---- MdtContactSetNext (exported as kd_MdtContactSetNext, asm label "MdtContactSetNext") ---- */
void kd_MdtContactSetNext(MdtContactID c,MdtContactID nc)

{
  c->nextContact = nc;
  return;
}

/* ---- MdtContactSetDirection (exported as kd_MdtContactSetDirection, asm label "MdtContactSetDirection") ---- */
void kd_MdtContactSetDirection(MdtContactID c,MeReal x,MeReal y,MeReal z)

{
  c->direction[0] = x;
  c->direction[1] = y;
  c->direction[2] = z;
  (c->params).options = (c->params).options | 1;
  return;
}

/* ---- MdtContactSetWorldVelocity (exported as kd_MdtContactSetWorldVelocity, asm label "MdtContactSetWorldVelocity") ---- */
void kd_MdtContactSetWorldVelocity(MdtContactID c,MeReal x,MeReal y,MeReal z)

{
  c->worldVel[1] = y;
  c->worldVel[2] = z;
                    
  c->worldVel[0] = x;
  if (c->worldVel[2] * c->worldVel[2] + c->worldVel[1] * c->worldVel[1] + x * x <= 1e-12) {
    (c->params).options = (c->params).options & 0xfffffeff;
  }
  else {
    (c->params).options = (c->params).options | 0x100;
  }
  return;
}
