/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MdtContactGroup.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MdtContactGroup.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- imports needing an explicit declaration --- */
/* BaseConstraintCreate */
extern void * BaseConstraintCreate(void *);

/* BaseConstraintReset */
extern void BaseConstraintReset(void *);

/* BaseConstraintSetAxis */
extern void BaseConstraintSetAxis(void *, float, float, float);

/* BaseConstraintSetBodies */
extern void BaseConstraintSetBodies(void *, void *, void *);

/* ---- forward declarations ---- */
MdtContactGroupID kd_MdtContactGroupCreate(MdtWorldID w) KD_MANGLED("MdtContactGroupCreate");
void kd_MdtContactGroupDestroy(MdtContactGroupID g) KD_MANGLED("MdtContactGroupDestroy");
void kd_MdtContactGroupReset(MdtContactGroupID c) KD_MANGLED("MdtContactGroupReset");
void kd_MdtContactGroupSetGenerator(MdtContactGroupID c,void *generator) KD_MANGLED("MdtContactGroupSetGenerator");
MdtConstraintID kd_MdtContactGroupQuaConstraint(MdtContactGroupID c) KD_MANGLED("MdtContactGroupQuaConstraint");
MdtContactGroupID kd_MdtConstraintDCastContactGroup(MdtConstraintID c) KD_MANGLED("MdtConstraintDCastContactGroup");
MdtContactID kd_MdtContactGroupGetFirstContact(MdtContactGroupID c) KD_MANGLED("MdtContactGroupGetFirstContact");
void * kd_MdtContactGroupGetGenerator(MdtContactGroupID c) KD_MANGLED("MdtContactGroupGetGenerator");
MeBool kd_MdtContactGroupIsSwapped(MdtContactGroupID g) KD_MANGLED("MdtContactGroupIsSwapped");
int kd_MdtContactGroupGetCount(MdtContactGroupID g) KD_MANGLED("MdtContactGroupGetCount");
MdtContactID kd_MdtContactGroupGetNextContact(MdtContactGroupID g,MdtContactID c) KD_MANGLED("MdtContactGroupGetNextContact");
MeReal kd_MdtContactGroupGetNormalForce(MdtContactGroupID g) KD_MANGLED("MdtContactGroupGetNormalForce");
void kd_MdtContactGroupAppendContact(MdtContactGroupID g,MdtContactID c) KD_MANGLED("MdtContactGroupAppendContact");
void kd_MdtContactGroupRemoveContact(MdtContactGroupID g,MdtContactID c) KD_MANGLED("MdtContactGroupRemoveContact");
MdtContactID kd_MdtContactGroupCreateContact(MdtContactGroupID g) KD_MANGLED("MdtContactGroupCreateContact");
void kd_MdtContactGroupDestroyContact(MdtContactGroupID g,MdtContactID c) KD_MANGLED("MdtContactGroupDestroyContact");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MdtContactGroupCreate (exported as kd_MdtContactGroupCreate, asm label "MdtContactGroupCreate") ---- */
MdtContactGroupID kd_MdtContactGroupCreate(MdtWorldID w)

{
  MdtContactGroupID pMVar1;
  int iVar2;
  void *pvVar3;
  MdtContactID pMVar4;
  MdtContactGroupID pMVar5;
  MdtContactID pMVar6;

  pMVar1 = BaseConstraintCreate(w);
  pMVar4 = MdtContactInvalidID;
  pMVar5 = (MdtContactGroupID)0x0;
  if (pMVar1 != (MdtContactGroupID)0x0) {
                    
    (pMVar1->head).tag = 5;
    (pMVar1->head).bclFunction = MdtBclAddContactGroup;
    (pMVar1->head).maxRows = 0;
    (pMVar1->head).setBodyFunc = BaseConstraintSetBodies;
    (pMVar1->head).setAxisFunc = BaseConstraintSetAxis;
    pMVar1->first = pMVar4;
    pMVar1->last = pMVar4;
    iVar2 = MdtConstraintIsEnabled(pMVar1);
    if (iVar2 != 0) {
      MdtConstraintDisable(pMVar1);
    }
    pMVar6 = pMVar1->first;
    if (pMVar6 != pMVar4) {
      do {
        pvVar3 = MdtContactQuaConstraint(pMVar6);
        iVar2 = MdtConstraintIsEnabled(pvVar3);
        if (iVar2 != 0) {
          pvVar3 = MdtContactQuaConstraint(pMVar6);
          MdtConstraintDisable(pvVar3);
        }
        pMVar4 = MdtContactGetNext(pMVar6);
        pvVar3 = MdtContactQuaConstraint(pMVar6);
        MdtConstraintDestroy(pvVar3);
        pMVar6 = pMVar4;
      } while (pMVar4 != MdtContactInvalidID);
    }
    BaseConstraintReset(pMVar1);
    pMVar4 = MdtContactInvalidID;
    pMVar1->first = MdtContactInvalidID;
    pMVar1->last = pMVar4;
    pMVar1->count = 0;
    pMVar1->swapped = 0;
    pMVar1->normalForce = 0.0;
    pMVar1->generator = (void *)0x0;
    pMVar5 = pMVar1;
  }
  return pMVar5;
}

/* ---- MdtContactGroupDestroy (exported as kd_MdtContactGroupDestroy, asm label "MdtContactGroupDestroy") ---- */
void kd_MdtContactGroupDestroy(MdtContactGroupID g)

{
  MdtContactID pMVar1;
  MdtContactGroupDestroyCallbackCBPtr p_Var2;
  MdtContactID pMVar3;
  void *pvVar4;

  pMVar3 = g->first;
  while (pMVar3 != (MdtContactID)0x0) {
    pMVar1 = pMVar3->nextContact;
    pvVar4 = MdtContactQuaConstraint(pMVar3);
    MdtConstraintDestroy(pvVar4);
    pMVar3 = pMVar1;
  }
  p_Var2 = ((g->head).world)->contactGroupDestroyCallback;
  if (p_Var2 != (MdtContactGroupDestroyCallbackCBPtr)0x0) {
    (*p_Var2)(g);
  }
  MdtConstraintDestroy(g);
  return;
}

/* ---- MdtContactGroupReset (exported as kd_MdtContactGroupReset, asm label "MdtContactGroupReset") ---- */
void kd_MdtContactGroupReset(MdtContactGroupID c)

{
  int iVar1;
  void *pvVar2;
  MdtContactID pMVar3;
  MdtContactID pMVar4;

  iVar1 = MdtConstraintIsEnabled(c);
  if (iVar1 != 0) {
    MdtConstraintDisable(c);
  }
  pMVar4 = c->first;
  if (pMVar4 != MdtContactInvalidID) {
    do {
      pvVar2 = MdtContactQuaConstraint(pMVar4);
      iVar1 = MdtConstraintIsEnabled(pvVar2);
      if (iVar1 != 0) {
        pvVar2 = MdtContactQuaConstraint(pMVar4);
        MdtConstraintDisable(pvVar2);
      }
      pMVar3 = MdtContactGetNext(pMVar4);
      pvVar2 = MdtContactQuaConstraint(pMVar4);
      MdtConstraintDestroy(pvVar2);
      pMVar4 = pMVar3;
    } while (pMVar3 != MdtContactInvalidID);
  }
  BaseConstraintReset(c);
  pMVar4 = MdtContactInvalidID;
  c->first = MdtContactInvalidID;
  c->last = pMVar4;
  c->count = 0;
  c->swapped = 0;
  c->normalForce = 0.0;
  c->generator = (void *)0x0;
  return;
}

/* ---- MdtContactGroupSetGenerator (exported as kd_MdtContactGroupSetGenerator, asm label "MdtContactGroupSetGenerator") ---- */
void kd_MdtContactGroupSetGenerator(MdtContactGroupID c,void *generator)

{
  c->generator = generator;
  return;
}

/* ---- MdtContactGroupQuaConstraint (exported as kd_MdtContactGroupQuaConstraint, asm label "MdtContactGroupQuaConstraint") ---- */
MdtConstraintID kd_MdtContactGroupQuaConstraint(MdtContactGroupID c)

{
  return (MdtConstraintID)c;
}

/* ---- MdtConstraintDCastContactGroup (exported as kd_MdtConstraintDCastContactGroup, asm label "MdtConstraintDCastContactGroup") ---- */
MdtContactGroupID kd_MdtConstraintDCastContactGroup(MdtConstraintID c)

{
  return (MdtContactGroupID)(((c->head).tag != 5) - 1 & (kd_uptr)c);
}

/* ---- MdtContactGroupGetFirstContact (exported as kd_MdtContactGroupGetFirstContact, asm label "MdtContactGroupGetFirstContact") ---- */
MdtContactID kd_MdtContactGroupGetFirstContact(MdtContactGroupID c)

{
  return c->first;
}

/* ---- MdtContactGroupGetGenerator (exported as kd_MdtContactGroupGetGenerator, asm label "MdtContactGroupGetGenerator") ---- */
void * kd_MdtContactGroupGetGenerator(MdtContactGroupID c)

{
  return c->generator;
}

/* ---- MdtContactGroupIsSwapped (exported as kd_MdtContactGroupIsSwapped, asm label "MdtContactGroupIsSwapped") ---- */
MeBool kd_MdtContactGroupIsSwapped(MdtContactGroupID g)

{
  return g->swapped;
}

/* ---- MdtContactGroupGetCount (exported as kd_MdtContactGroupGetCount, asm label "MdtContactGroupGetCount") ---- */
int kd_MdtContactGroupGetCount(MdtContactGroupID g)

{
  return g->count;
}

/* ---- MdtContactGroupGetNextContact (exported as kd_MdtContactGroupGetNextContact, asm label "MdtContactGroupGetNextContact") ---- */
MdtContactID
kd_MdtContactGroupGetNextContact(MdtContactGroupID g,MdtContactID c)

{
  return c->nextContact;
}

/* ---- MdtContactGroupGetNormalForce (exported as kd_MdtContactGroupGetNormalForce, asm label "MdtContactGroupGetNormalForce") ---- */
MeReal kd_MdtContactGroupGetNormalForce(MdtContactGroupID g)

{
  return g->normalForce;
}

/* ---- MdtContactGroupAppendContact (exported as kd_MdtContactGroupAppendContact, asm label "MdtContactGroupAppendContact") ---- */
void kd_MdtContactGroupAppendContact(MdtContactGroupID g,MdtContactID c)

{
  MdtContactID pMVar1;
  
  pMVar1 = g->first;
  if (pMVar1 == MdtContactInvalidID) {
    g->last = c;
    g->first = c;
    c->prevContact = pMVar1;
    c->nextContact = pMVar1;
  }
  else {
    c->prevContact = g->last;
    g->last->nextContact = c;
    g->last = c;
  }
  c->contactGroup = g;
  g->count = g->count + 1;
  return;
}

/* ---- MdtContactGroupRemoveContact (exported as kd_MdtContactGroupRemoveContact, asm label "MdtContactGroupRemoveContact") ---- */
void kd_MdtContactGroupRemoveContact(MdtContactGroupID g,MdtContactID c)

{
  MdtContactID pMVar1;
  MdtContactID pMVar2;
  
  if (g->first == c) {
    g->first = c->nextContact;
    pMVar2 = c->prevContact;
  }
  else {
    pMVar2 = c->prevContact;
    pMVar2->nextContact = c->nextContact;
  }
  if (g->last == c) {
    g->last = pMVar2;
  }
  else {
    c->nextContact->prevContact = pMVar2;
  }
  pMVar1 = MdtContactInvalidID;
  c->prevContact = MdtContactInvalidID;
  c->nextContact = pMVar1;
  c->contactGroup = (MdtContactGroupID)0x0;
  g->count = g->count + -1;
  return;
}

/* ---- MdtContactGroupCreateContact (exported as kd_MdtContactGroupCreateContact, asm label "MdtContactGroupCreateContact") ---- */
MdtContactID kd_MdtContactGroupCreateContact(MdtContactGroupID g)

{
  MdtContactID pMVar1;
  MdtContactID pMVar2;
  void *pvVar3;
  MdtBody *pMVar4;
  MdtBody *pMVar5;

  pMVar2 = MdtContactCreate((g->head).world);
  if (pMVar2 != MdtContactInvalidID) {
    pMVar1 = g->first;
    if (pMVar1 == MdtContactInvalidID) {
      g->last = pMVar2;
      g->first = pMVar2;
      pMVar2->prevContact = pMVar1;
      pMVar2->nextContact = pMVar1;
    }
    else {
      pMVar2->prevContact = g->last;
      g->last->nextContact = pMVar2;
      g->last = pMVar2;
    }
    pMVar2->contactGroup = g;
    g->count = g->count + 1;
    pMVar5 = (g->head).mdtbody[1];
    pMVar4 = (g->head).mdtbody[0];
    pvVar3 = MdtContactQuaConstraint(pMVar2);
    MdtConstraintSetBodies(pvVar3,pMVar4,pMVar5);
  }
  return pMVar2;
}

/* ---- MdtContactGroupDestroyContact (exported as kd_MdtContactGroupDestroyContact, asm label "MdtContactGroupDestroyContact") ---- */
void kd_MdtContactGroupDestroyContact(MdtContactGroupID g,MdtContactID c)

{
  MdtContactID pMVar1;
  void *pvVar2;
  MdtContactID pMVar3;
  
  if (g->first == c) {
    g->first = c->nextContact;
    pMVar3 = c->prevContact;
  }
  else {
    pMVar3 = c->prevContact;
    pMVar3->nextContact = c->nextContact;
  }
  if (g->last == c) {
    g->last = pMVar3;
  }
  else {
    c->nextContact->prevContact = pMVar3;
  }
  pMVar1 = MdtContactInvalidID;
  c->prevContact = MdtContactInvalidID;
  c->nextContact = pMVar1;
  c->contactGroup = (MdtContactGroupID)0x0;
  g->count = g->count + -1;
  pvVar2 = MdtContactQuaConstraint(c);
  MdtConstraintDestroy(pvVar2);
  return;
}
