/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MdtContactParams.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MdtContactParams.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
void kd_MdtContactParamsReset(MdtContactParamsID p) KD_MANGLED("MdtContactParamsReset");
MdtContactType kd_MdtContactParamsGetType(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetType");
MdtFrictionModel kd_MdtContactParamsGetPrimaryFrictionModel(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetPrimaryFrictionModel");
MdtFrictionModel kd_MdtContactParamsGetSecondaryFrictionModel(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetSecondaryFrictionModel");
MeReal kd_MdtContactParamsGetRestitution(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetRestitution");
MeReal kd_MdtContactParamsGetRestitutionThreshold(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetRestitutionThreshold");
MeReal kd_MdtContactParamsGetSoftness(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetSoftness");
MeReal kd_MdtContactParamsGetMaxAdhesiveForce(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetMaxAdhesiveForce");
MeReal kd_MdtContactParamsGetPrimaryFriction(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetPrimaryFriction");
MeReal kd_MdtContactParamsGetPrimaryFrictionCoeffecient(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetPrimaryFrictionCoeffecient");
MeReal kd_MdtContactParamsGetPrimarySlip(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetPrimarySlip");
MeReal kd_MdtContactParamsGetPrimarySlide(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetPrimarySlide");
MeReal kd_MdtContactParamsGetSecondaryFriction(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetSecondaryFriction");
MeReal kd_MdtContactParamsGetSecondaryFrictionCoeffecient(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetSecondaryFrictionCoeffecient");
MeReal kd_MdtContactParamsGetSecondarySlip(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetSecondarySlip");
MeReal kd_MdtContactParamsGetSecondarySlide(MdtContactParamsID p) KD_MANGLED("MdtContactParamsGetSecondarySlide");
void kd_MdtContactParamsSetType(MdtContactParamsID p,MdtContactType t) KD_MANGLED("MdtContactParamsSetType");
void kd_MdtContactParamsSetPrimaryFrictionModel(MdtContactParamsID p,MdtFrictionModel m) KD_MANGLED("MdtContactParamsSetPrimaryFrictionModel");
void kd_MdtContactParamsSetSecondaryFrictionModel(MdtContactParamsID p,MdtFrictionModel m) KD_MANGLED("MdtContactParamsSetSecondaryFrictionModel");
void kd_MdtContactParamsSetFrictionModel(MdtContactParamsID p,MdtFrictionModel m) KD_MANGLED("MdtContactParamsSetFrictionModel");
void kd_MdtContactParamsSetRestitution(MdtContactParamsID p,MeReal r) KD_MANGLED("MdtContactParamsSetRestitution");
void kd_MdtContactParamsSetRestitutionThreshold(MdtContactParamsID p,MeReal v) KD_MANGLED("MdtContactParamsSetRestitutionThreshold");
void kd_MdtContactParamsSetSoftness(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetSoftness");
void kd_MdtContactParamsSetMaxAdhesiveForce(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetMaxAdhesiveForce");
void kd_MdtContactParamsSetPrimaryFriction(MdtContactParamsID p,MeReal f) KD_MANGLED("MdtContactParamsSetPrimaryFriction");
void kd_MdtContactParamsSetPrimaryFrictionCoeffecient(MdtContactParamsID p,MeReal f) KD_MANGLED("MdtContactParamsSetPrimaryFrictionCoeffecient");
void kd_MdtContactParamsSetPrimarySlip(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetPrimarySlip");
void kd_MdtContactParamsSetPrimarySlide(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetPrimarySlide");
void kd_MdtContactParamsSetSecondaryFriction(MdtContactParamsID p,MeReal f) KD_MANGLED("MdtContactParamsSetSecondaryFriction");
void kd_MdtContactParamsSetSecondaryFrictionCoeffecient(MdtContactParamsID p,MeReal f) KD_MANGLED("MdtContactParamsSetSecondaryFrictionCoeffecient");
void kd_MdtContactParamsSetSecondarySlip(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetSecondarySlip");
void kd_MdtContactParamsSetSecondarySlide(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetSecondarySlide");
void kd_MdtContactParamsSetSlip(MdtContactParamsID p,MeReal s) KD_MANGLED("MdtContactParamsSetSlip");
void kd_MdtContactParamsSetFriction(MdtContactParamsID p,MeReal f) KD_MANGLED("MdtContactParamsSetFriction");
void kd_MdtContactParamsSetFrictionCoeffecient(MdtContactParamsID p,MeReal f) KD_MANGLED("MdtContactParamsSetFrictionCoeffecient");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MdtContactParamsReset (exported as kd_MdtContactParamsReset, asm label "MdtContactParamsReset") ---- */
void kd_MdtContactParamsReset(MdtContactParamsID p)

{
  p->type = MdtContactTypeFrictionZero;
  p->model1 = MdtFrictionModelBox;
  p->model2 = MdtFrictionModelBox;
  p->options = 0;
  p->restitution = 0.0;
  p->velThreshold = 0.001;
  p->softness = 0.0;
  p->max_adhesive_force = 0.0;
  p->friction1 = 3.4028235e+38;
  p->frictioncoeff1 = 0.0;
  p->slip1 = 0.0;
  p->friction2 = 3.4028235e+38;
  p->frictioncoeff2 = 0.0;
  p->slip2 = 0.0;
  p->slide1 = 0.0;
  p->slide2 = 0.0;
  return;
}

/* ---- MdtContactParamsGetType (exported as kd_MdtContactParamsGetType, asm label "MdtContactParamsGetType") ---- */
MdtContactType kd_MdtContactParamsGetType(MdtContactParamsID p)

{
  return p->type;
}

/* ---- MdtContactParamsGetPrimaryFrictionModel (exported as kd_MdtContactParamsGetPrimaryFrictionModel, asm label "MdtContactParamsGetPrimaryFrictionModel") ---- */
MdtFrictionModel kd_MdtContactParamsGetPrimaryFrictionModel(MdtContactParamsID p)

{
  return p->model1;
}

/* ---- MdtContactParamsGetSecondaryFrictionModel (exported as kd_MdtContactParamsGetSecondaryFrictionModel, asm label "MdtContactParamsGetSecondaryFrictionModel") ---- */
MdtFrictionModel kd_MdtContactParamsGetSecondaryFrictionModel(MdtContactParamsID p)

{
  return p->model2;
}

/* ---- MdtContactParamsGetRestitution (exported as kd_MdtContactParamsGetRestitution, asm label "MdtContactParamsGetRestitution") ---- */
MeReal kd_MdtContactParamsGetRestitution(MdtContactParamsID p)

{
  return p->restitution;
}

/* ---- MdtContactParamsGetRestitutionThreshold (exported as kd_MdtContactParamsGetRestitutionThreshold, asm label "MdtContactParamsGetRestitutionThreshold") ---- */
MeReal kd_MdtContactParamsGetRestitutionThreshold(MdtContactParamsID p)

{
  return p->velThreshold;
}

/* ---- MdtContactParamsGetSoftness (exported as kd_MdtContactParamsGetSoftness, asm label "MdtContactParamsGetSoftness") ---- */
MeReal kd_MdtContactParamsGetSoftness(MdtContactParamsID p)

{
  return p->softness;
}

/* ---- MdtContactParamsGetMaxAdhesiveForce (exported as kd_MdtContactParamsGetMaxAdhesiveForce, asm label "MdtContactParamsGetMaxAdhesiveForce") ---- */
MeReal kd_MdtContactParamsGetMaxAdhesiveForce(MdtContactParamsID p)

{
  return p->max_adhesive_force;
}

/* ---- MdtContactParamsGetPrimaryFriction (exported as kd_MdtContactParamsGetPrimaryFriction, asm label "MdtContactParamsGetPrimaryFriction") ---- */
MeReal kd_MdtContactParamsGetPrimaryFriction(MdtContactParamsID p)

{
  return p->friction1;
}

/* ---- MdtContactParamsGetPrimaryFrictionCoeffecient (exported as kd_MdtContactParamsGetPrimaryFrictionCoeffecient, asm label "MdtContactParamsGetPrimaryFrictionCoeffecient") ---- */
MeReal kd_MdtContactParamsGetPrimaryFrictionCoeffecient(MdtContactParamsID p)

{
  return p->frictioncoeff1;
}

/* ---- MdtContactParamsGetPrimarySlip (exported as kd_MdtContactParamsGetPrimarySlip, asm label "MdtContactParamsGetPrimarySlip") ---- */
MeReal kd_MdtContactParamsGetPrimarySlip(MdtContactParamsID p)

{
  return p->slip1;
}

/* ---- MdtContactParamsGetPrimarySlide (exported as kd_MdtContactParamsGetPrimarySlide, asm label "MdtContactParamsGetPrimarySlide") ---- */
MeReal kd_MdtContactParamsGetPrimarySlide(MdtContactParamsID p)

{
  return p->slide1;
}

/* ---- MdtContactParamsGetSecondaryFriction (exported as kd_MdtContactParamsGetSecondaryFriction, asm label "MdtContactParamsGetSecondaryFriction") ---- */
MeReal kd_MdtContactParamsGetSecondaryFriction(MdtContactParamsID p)

{
  return p->friction2;
}

/* ---- MdtContactParamsGetSecondaryFrictionCoeffecient (exported as kd_MdtContactParamsGetSecondaryFrictionCoeffecient, asm label "MdtContactParamsGetSecondaryFrictionCoeffecient") ---- */
MeReal kd_MdtContactParamsGetSecondaryFrictionCoeffecient(MdtContactParamsID p)

{
  return p->frictioncoeff2;
}

/* ---- MdtContactParamsGetSecondarySlip (exported as kd_MdtContactParamsGetSecondarySlip, asm label "MdtContactParamsGetSecondarySlip") ---- */
MeReal kd_MdtContactParamsGetSecondarySlip(MdtContactParamsID p)

{
  return p->slip2;
}

/* ---- MdtContactParamsGetSecondarySlide (exported as kd_MdtContactParamsGetSecondarySlide, asm label "MdtContactParamsGetSecondarySlide") ---- */
MeReal kd_MdtContactParamsGetSecondarySlide(MdtContactParamsID p)

{
  return p->slide2;
}

/* ---- MdtContactParamsSetType (exported as kd_MdtContactParamsSetType, asm label "MdtContactParamsSetType") ---- */
void kd_MdtContactParamsSetType(MdtContactParamsID p,MdtContactType t)

{
  if (t == MdtContactTypeFriction1D) {
    p->type = MdtContactTypeFriction1D;
  }
  else {
    if (t < MdtContactTypeFriction2D) {
      if (t == MdtContactTypeFrictionZero) {
        p->type = MdtContactTypeFrictionZero;
        return;
      }
    }
    else if (t == MdtContactTypeFriction2D) {
      p->type = MdtContactTypeFriction2D;
      return;
    }
    MeWarning(0xc,"Unknown Contact Type, defaulting to zero friction.");
    p->type = MdtContactTypeFrictionZero;
  }
  return;
}

/* ---- MdtContactParamsSetPrimaryFrictionModel (exported as kd_MdtContactParamsSetPrimaryFrictionModel, asm label "MdtContactParamsSetPrimaryFrictionModel") ---- */
void kd_MdtContactParamsSetPrimaryFrictionModel(MdtContactParamsID p,MdtFrictionModel m)

{
  if (m == MdtFrictionModelBox) {
    p->model1 = MdtFrictionModelBox;
  }
  else if (m == MdtFrictionModelNormalForce) {
    p->model1 = MdtFrictionModelNormalForce;
  }
  else {
    MeWarning(0xc,"Unknown Friction Model, defaulting to box friction.");
    p->model1 = MdtFrictionModelBox;
  }
  return;
}

/* ---- MdtContactParamsSetSecondaryFrictionModel (exported as kd_MdtContactParamsSetSecondaryFrictionModel, asm label "MdtContactParamsSetSecondaryFrictionModel") ---- */
void kd_MdtContactParamsSetSecondaryFrictionModel(MdtContactParamsID p,MdtFrictionModel m)

{
  if (m == MdtFrictionModelBox) {
    p->model2 = MdtFrictionModelBox;
  }
  else if (m == MdtFrictionModelNormalForce) {
    p->model2 = MdtFrictionModelNormalForce;
  }
  else {
    MeWarning(0xc,"Unknown Friction Model, defaulting to box friction.");
    p->model2 = MdtFrictionModelBox;
  }
  return;
}

/* ---- MdtContactParamsSetFrictionModel (exported as kd_MdtContactParamsSetFrictionModel, asm label "MdtContactParamsSetFrictionModel") ---- */
void kd_MdtContactParamsSetFrictionModel(MdtContactParamsID p,MdtFrictionModel m)

{
  if (m != MdtFrictionModelBox) {
    if (m == MdtFrictionModelNormalForce) {
      p->model1 = MdtFrictionModelNormalForce;
      goto LAB_0001029c;
    }
    MeWarning(0xc,"Unknown Friction Model, defaulting to box friction.");
  }
  p->model1 = MdtFrictionModelBox;
LAB_0001029c:
  if (m != MdtFrictionModelBox) {
    if (m == MdtFrictionModelNormalForce) {
      p->model2 = MdtFrictionModelNormalForce;
      return;
    }
    MeWarning(0xc,"Unknown Friction Model, defaulting to box friction.");
  }
  p->model2 = MdtFrictionModelBox;
  return;
}

/* ---- MdtContactParamsSetRestitution (exported as kd_MdtContactParamsSetRestitution, asm label "MdtContactParamsSetRestitution") ---- */
void kd_MdtContactParamsSetRestitution(MdtContactParamsID p,MeReal r)

{
  if (r < 0.0) {
    MeWarning(0xc,
              "MdtContactParamsSetRestitution: Negative restitution not valid - setting to zero.");
    r = 0.0;
  }
  p->restitution = r;
  if (ABS(r) < 1e-06) {
    p->options = p->options & 0xfffffffd;
  }
  else {
    p->options = p->options | 2;
  }
  return;
}

/* ---- MdtContactParamsSetRestitutionThreshold (exported as kd_MdtContactParamsSetRestitutionThreshold, asm label "MdtContactParamsSetRestitutionThreshold") ---- */
void kd_MdtContactParamsSetRestitutionThreshold(MdtContactParamsID p,MeReal v)

{
  p->velThreshold = v;
  return;
}

/* ---- MdtContactParamsSetSoftness (exported as kd_MdtContactParamsSetSoftness, asm label "MdtContactParamsSetSoftness") ---- */
void kd_MdtContactParamsSetSoftness(MdtContactParamsID p,MeReal s)

{
  if (s < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetSoftness: Negative softness not valid - setting to zero.");
    s = 0.0;
  }
  p->softness = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xfffffffb;
  }
  else {
    p->options = p->options | 4;
  }
  return;
}

/* ---- MdtContactParamsSetMaxAdhesiveForce (exported as kd_MdtContactParamsSetMaxAdhesiveForce, asm label "MdtContactParamsSetMaxAdhesiveForce") ---- */
void kd_MdtContactParamsSetMaxAdhesiveForce(MdtContactParamsID p,MeReal s)

{
  p->max_adhesive_force = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xfffffff7;
  }
  else {
    p->options = p->options | 8;
  }
  return;
}

/* ---- MdtContactParamsSetPrimaryFriction (exported as kd_MdtContactParamsSetPrimaryFriction, asm label "MdtContactParamsSetPrimaryFriction") ---- */
void kd_MdtContactParamsSetPrimaryFriction(MdtContactParamsID p,MeReal f)

{
  p->friction1 = f;
  return;
}

/* ---- MdtContactParamsSetPrimaryFrictionCoeffecient (exported as kd_MdtContactParamsSetPrimaryFrictionCoeffecient, asm label "MdtContactParamsSetPrimaryFrictionCoeffecient") ---- */
void kd_MdtContactParamsSetPrimaryFrictionCoeffecient(MdtContactParamsID p,MeReal f)

{
  p->frictioncoeff1 = f;
  return;
}

/* ---- MdtContactParamsSetPrimarySlip (exported as kd_MdtContactParamsSetPrimarySlip, asm label "MdtContactParamsSetPrimarySlip") ---- */
void kd_MdtContactParamsSetPrimarySlip(MdtContactParamsID p,MeReal s)

{
  if (s < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetPrimarySlip: Negative slip not valid - setting to zero.");
    s = 0.0;
  }
  p->slip1 = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xffffffef;
  }
  else {
    p->options = p->options | 0x10;
  }
  return;
}

/* ---- MdtContactParamsSetPrimarySlide (exported as kd_MdtContactParamsSetPrimarySlide, asm label "MdtContactParamsSetPrimarySlide") ---- */
void kd_MdtContactParamsSetPrimarySlide(MdtContactParamsID p,MeReal s)

{
  p->slide1 = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xffffffbf;
  }
  else {
    p->options = p->options | 0x40;
  }
  return;
}

/* ---- MdtContactParamsSetSecondaryFriction (exported as kd_MdtContactParamsSetSecondaryFriction, asm label "MdtContactParamsSetSecondaryFriction") ---- */
void kd_MdtContactParamsSetSecondaryFriction(MdtContactParamsID p,MeReal f)

{
  p->friction2 = f;
  return;
}

/* ---- MdtContactParamsSetSecondaryFrictionCoeffecient (exported as kd_MdtContactParamsSetSecondaryFrictionCoeffecient, asm label "MdtContactParamsSetSecondaryFrictionCoeffecient") ---- */
void kd_MdtContactParamsSetSecondaryFrictionCoeffecient(MdtContactParamsID p,MeReal f)

{
  p->frictioncoeff2 = f;
  return;
}

/* ---- MdtContactParamsSetSecondarySlip (exported as kd_MdtContactParamsSetSecondarySlip, asm label "MdtContactParamsSetSecondarySlip") ---- */
void kd_MdtContactParamsSetSecondarySlip(MdtContactParamsID p,MeReal s)

{
  if (s < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetSecondarySlip: Negative slip not valid - setting to zero.");
    s = 0.0;
  }
  p->slip2 = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xffffffdf;
  }
  else {
    p->options = p->options | 0x20;
  }
  return;
}

/* ---- MdtContactParamsSetSecondarySlide (exported as kd_MdtContactParamsSetSecondarySlide, asm label "MdtContactParamsSetSecondarySlide") ---- */
void kd_MdtContactParamsSetSecondarySlide(MdtContactParamsID p,MeReal s)

{
  p->slide2 = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xffffff7f;
  }
  else {
    p->options = p->options | 0x80;
  }
  return;
}

/* ---- MdtContactParamsSetSlip (exported as kd_MdtContactParamsSetSlip, asm label "MdtContactParamsSetSlip") ---- */
void kd_MdtContactParamsSetSlip(MdtContactParamsID p,MeReal s)

{
  MeReal MVar1;
  
  MVar1 = s;
  if (s < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetPrimarySlip: Negative slip not valid - setting to zero.");
    MVar1 = 0.0;
  }
  p->slip1 = MVar1;
  if (ABS(MVar1) < 1e-06) {
    p->options = p->options & 0xffffffef;
  }
  else {
    p->options = p->options | 0x10;
  }
  if (s < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetSecondarySlip: Negative slip not valid - setting to zero.");
    s = 0.0;
  }
  p->slip2 = s;
  if (ABS(s) < 1e-06) {
    p->options = p->options & 0xffffffdf;
  }
  else {
    p->options = p->options | 0x20;
  }
  return;
}

/* ---- MdtContactParamsSetFriction (exported as kd_MdtContactParamsSetFriction, asm label "MdtContactParamsSetFriction") ---- */
void kd_MdtContactParamsSetFriction(MdtContactParamsID p,MeReal f)

{
  if (f < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetFriction: Negative friction not valid - setting to zero.");
    f = 0.0;
  }
  p->friction1 = f;
  p->friction2 = f;
  return;
}

/* ---- MdtContactParamsSetFrictionCoeffecient (exported as kd_MdtContactParamsSetFrictionCoeffecient, asm label "MdtContactParamsSetFrictionCoeffecient") ---- */
void kd_MdtContactParamsSetFrictionCoeffecient(MdtContactParamsID p,MeReal f)

{
  if (f < 0.0) {
    MeWarning(0xc,"MdtContactParamsSetPrimarySlip: Negative friction not valid - setting to zero.");
    f = 0.0;
  }
  p->frictioncoeff1 = f;
  p->frictioncoeff2 = f;
  return;
}
