/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MdtMainLoop.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MdtMainLoop.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- imports needing an explicit declaration --- */
/* GetCOMTransform */
extern void GetCOMTransform(void *, void *);

/* UpdateBodyTransform */
extern void UpdateBodyTransform(void *, void *);

/* ---- forward declarations ---- */
void kd_MdtAutoDisableLastPartition(MdtPartitionOutput *po,void *pcbdata) KD_MANGLED("MdtAutoDisableLastPartition");
void kd_MdtUpdateBodyForces(MdtBodyID b,MeReal stepSize,MeReal *g) KD_MANGLED("MdtUpdateBodyForces");
uint kd_MdtPackAllPartitions (MdtPartitionOutput *po,MeReal stepSize,MdtWorldParams *params, MdtKeaParameters *keaParams,MdtKeaTransformation *keaTMArray, MdtKeaConstraints *constraints) KD_MANGLED("MdtPackAllPartitions");
uint kd_MdtPackPartition(MdtPartitionOutput *po,uint partitionindex,MeReal stepSize, MdtWorldParams *params,MdtKeaParameters *keaParams, MdtKeaTransformation *keaTMArray,MdtKeaConstraints *constraints) KD_MANGLED("MdtPackPartition");
uint kd_MdtUnpackForces(MdtKeaForcePair *force,uint partitionindex,MdtPartitionOutput *po) KD_MANGLED("MdtUnpackForces");
MdtKeaConstraints * kd_MdtKeaConstraintsCreateFromChunk(MeChunk *chunk,int maxPartitions,int maxKeaConstraints,int maxRows) KD_MANGLED("MdtKeaConstraintsCreateFromChunk");
void kd_MdtDefaultSimErrorCallBack(MdtKeaConstraints *kc,MdtKeaBody **kb,int nBodies,void *secbdata) KD_MANGLED("MdtDefaultSimErrorCallBack");
void kd_MdtUnpackBodies(MdtKeaTransformation *keaTMArray,uint partitionindex,MdtPartitionOutput *po) KD_MANGLED("MdtUnpackBodies");
MeReal kd_MdtPartitionGetSafeTime(MdtPartitionOutput *po,int i) KD_MANGLED("MdtPartitionGetSafeTime");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MdtAutoDisableLastPartition (exported as kd_MdtAutoDisableLastPartition, asm label "MdtAutoDisableLastPartition") ---- */
void kd_MdtAutoDisableLastPartition(MdtPartitionOutput *po,void *pcbdata)

{
  MdtPartitionInfo *pMVar1;
  MdtBody *pMVar2;
  bool bVar3;
  int iVar4;
  int *piVar5;
  int iVar6;
  int iVar7;
  int b;
  MeBool partitionIsMoving;
  void *pcbdata_local;

  bVar3 = false;
  iVar7 = po->nPartitions + -1;
  if (*(int *)pcbdata == 0) {
    bVar3 = true;
  }
  else {
                    
    iVar6 = po->bodiesStart[iVar7];
    if (iVar6 < po->bodiesSize[iVar7] + iVar6) {
      do {
        iVar4 = MdtBodyIsMovingTest(po->bodies[iVar6],pcbdata);
        if (iVar4 != 0) {
          bVar3 = true;
        }
        iVar6 = iVar6 + 1;
        if (po->bodiesSize[iVar7] + po->bodiesStart[iVar7] <= iVar6) goto LAB_000100a5;
      } while (!bVar3);
      goto LAB_0001007a;
    }
  }
LAB_000100a5:
  if (!bVar3) {
    b = po->bodiesStart[iVar7];
    piVar5 = po->bodiesSize;
    if (b < b + piVar5[iVar7]) {
      do {
                    
        pMVar2 = po->bodies[b];
        MdtBodyDisable(pMVar2);
        MdtBodyResetForces(pMVar2);
        MdtBodyResetImpulses(pMVar2);
        b = b + 1;
        piVar5 = po->bodiesSize;
      } while (b < piVar5[iVar7] + po->bodiesStart[iVar7]);
    }
    po->nPartitions = po->nPartitions + -1;
    po->totalBodies = po->totalBodies - piVar5[iVar7];
    pMVar1 = po->info;
    po->totalConstraints = po->totalConstraints - po->constraintsSize[iVar7];
    iVar6 = pMVar1[iVar7].jointCount;
    (po->overallInfo).rowCount = (po->overallInfo).rowCount - pMVar1[iVar7].rowCount;
    iVar7 = pMVar1[iVar7].contactCount;
    (po->overallInfo).jointCount = (po->overallInfo).jointCount - iVar6;
    (po->overallInfo).contactCount = (po->overallInfo).contactCount - iVar7;
    return;
  }
LAB_0001007a:
  if (po->info[iVar7].rowCount <= *(int *)((kd_iptr)pcbdata + 0x18)) {
    return;
  }
  MdtLODLastPartition(po,pcbdata);
  return;
}

/* ---- MdtUpdateBodyForces (exported as kd_MdtUpdateBodyForces, asm label "MdtUpdateBodyForces") ---- */
void kd_MdtUpdateBodyForces(MdtBodyID b,MeReal stepSize,MeReal *g)

{
  float fVar1;
  float fVar2;
  float fVar3;
  float fVar4;
  float fVar5;
  int iVar6;
  float fVar7;

  if ((b->constraintDict).nodecount == 0) {
    (b->keaBody).flags = (b->keaBody).flags & 0xfffffffd;
  }
  else {
    (b->keaBody).flags = (b->keaBody).flags | 2;
  }
  fVar7 = -b->angularDamping;
  iVar6 = b->impulseAdded;
  fVar5 = ((b->keaBody).I1[1] + (b->keaBody).I0[0] + (b->keaBody).I2[2]) * 0.33333334;
  (b->keaBody).torque[0] = fVar7 * (b->keaBody).velrot[0] * fVar5 + (b->keaBody).torque[0];
  fVar1 = (b->keaBody).velrot[1];
  fVar2 = b->mass;
  fVar3 = (b->keaBody).torque[1];
  (b->keaBody).torque[2] = fVar7 * (b->keaBody).velrot[2] * fVar5 + (b->keaBody).torque[2];
  fVar4 = b->damping;
  (b->keaBody).torque[1] = fVar7 * fVar1 * fVar5 + fVar3;
  fVar4 = -fVar4;
  (b->keaBody).force[0] = (fVar4 * (b->keaBody).vel[0] + *g) * fVar2 + (b->keaBody).force[0];
  fVar1 = (b->keaBody).vel[2];
  (b->keaBody).force[1] = (fVar4 * (b->keaBody).vel[1] + g[1]) * fVar2 + (b->keaBody).force[1];
  fVar3 = g[2];
  fVar5 = (b->keaBody).force[2];
  b->enabledTime = b->enabledTime + stepSize;
  (b->keaBody).force[2] = (fVar4 * fVar1 + fVar3) * fVar2 + fVar5;
  if (iVar6 != 0) {
                    
    fVar4 = 1.0 / stepSize;
    b->impulseAdded = 0;
    fVar1 = b->impulseLinear[0];
    b->impulseLinear[0] = 0.0;
    (b->keaBody).force[0] = fVar4 * fVar1 + (b->keaBody).force[0];
    fVar1 = b->impulseAngular[0];
    b->impulseAngular[0] = 0.0;
    (b->keaBody).torque[0] = fVar4 * fVar1 + (b->keaBody).torque[0];
    fVar1 = b->impulseLinear[1];
    b->impulseLinear[1] = 0.0;
    (b->keaBody).force[1] = fVar4 * fVar1 + (b->keaBody).force[1];
    fVar1 = b->impulseAngular[1];
    b->impulseAngular[1] = 0.0;
    (b->keaBody).torque[1] = fVar4 * fVar1 + (b->keaBody).torque[1];
    fVar1 = b->impulseLinear[2];
    b->impulseLinear[2] = 0.0;
    (b->keaBody).force[2] = fVar4 * fVar1 + (b->keaBody).force[2];
    fVar1 = b->impulseAngular[2];
    b->impulseAngular[2] = 0.0;
    (b->keaBody).torque[2] = fVar4 * fVar1 + (b->keaBody).torque[2];
    fVar1 = b->impulseAngular[3];
    b->impulseAngular[3] = 0.0;
    fVar2 = b->impulseLinear[3];
    fVar3 = (b->keaBody).torque[3];
    b->impulseLinear[3] = 0.0;
    (b->keaBody).torque[3] = fVar4 * fVar1 + fVar3;
    (b->keaBody).force[3] = fVar4 * fVar2 + (b->keaBody).force[3];
  }
  return;
}

/* ---- MdtPackAllPartitions (exported as kd_MdtPackAllPartitions, asm label "MdtPackAllPartitions") ---- */
uint kd_MdtPackAllPartitions
               (MdtPartitionOutput *po,MeReal stepSize,MdtWorldParams *params,
               MdtKeaParameters *keaParams,MdtKeaTransformation *keaTMArray,
               MdtKeaConstraints *constraints)

{
  MdtBaseConstraint **ppMVar1;
  MdtBody **ppMVar2;
  MdtBody **ppMVar3;
  MdtBaseConstraint *pMVar4;
  MdtBody *pMVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  int *piVar9;
  MdtBody **ppMVar10;
  int iVar11;
  MdtKeaTransformation *local_50;
  int constraintsSize;
  int bodiesSize;
  MdtKeaBody **keabodyArray;
  MdtBody **blist;
  uint maxPartitionConstraintRows;
  uint partitionConstraintRows;
  int partitionindex;
  int i;
  MdtBclSolverParameters bclParams;

  partitionConstraintRows = 0;
  bclParams.stepsize = stepSize;
  maxPartitionConstraintRows = 0;
  bclParams.epsilon = keaParams->epsilon;
  bclParams.gamma = keaParams->gamma;
  MdtBclInitConstraintRowList(constraints);
  ppMVar3 = po->bodies;
  partitionindex = 0;
  ppMVar10 = ppMVar3;
  if (po->nPartitions < 1) {
    return 0;
  }
  do {
    ppMVar10 = ppMVar10 + po->bodiesStart[partitionindex];
    uVar7 = po->bodiesSize[partitionindex];
    ppMVar1 = po->constraints + po->constraintsStart[partitionindex];
    uVar8 = po->constraintsSize[partitionindex];
    i = 0;
    if (0 < (int)uVar7) {
      local_50 = keaTMArray + po->bodiesStart[partitionindex];
      uVar6 = uVar7 & 3;
      if ((int)uVar7 < 2) {
LAB_00010442:
        kd_MdtUpdateBodyForces(ppMVar10[i],stepSize,params->gravity);
        ppMVar2 = ppMVar10 + i;
        i = i + 1;
        GetCOMTransform(*ppMVar2,local_50);
        local_50 = local_50 + 1;
        if ((int)uVar7 <= i) goto LAB_00010575;
      }
      else if (uVar6 != 0) {
        if (1 < uVar6) {
          if (2 < uVar6) {
            kd_MdtUpdateBodyForces(*ppMVar10,stepSize,params->gravity);
            GetCOMTransform(*ppMVar10,local_50);
            local_50 = local_50 + 1;
          }
          i = (int)(2 < uVar6);
          kd_MdtUpdateBodyForces(ppMVar10[i],stepSize,params->gravity);
          GetCOMTransform(ppMVar10[i],local_50);
          local_50 = local_50 + 1;
          i = i + 1;
        }
        goto LAB_00010442;
      }
      do {
        kd_MdtUpdateBodyForces(ppMVar10[i],stepSize,params->gravity);
        GetCOMTransform(ppMVar10[i],local_50);
        kd_MdtUpdateBodyForces(ppMVar10[i + 1],stepSize,params->gravity);
        GetCOMTransform(ppMVar10[i + 1],local_50 + 1);
        kd_MdtUpdateBodyForces(ppMVar10[i + 2],stepSize,params->gravity);
        GetCOMTransform(ppMVar10[i + 2],local_50 + 2);
        kd_MdtUpdateBodyForces(ppMVar10[i + 3],stepSize,params->gravity);
        GetCOMTransform(ppMVar10[i + 3],local_50 + 3);
        i = i + 4;
        local_50 = local_50 + 4;
      } while (i < (int)uVar7);
    }
LAB_00010575:
    i = 0;
    if (0 < (int)uVar8) {
      uVar7 = uVar8 & 3;
      if ((int)uVar8 < 2) {
LAB_00010594:
        MdtConstraintDCastContactGroup(ppMVar1[i]);
        (ppMVar1[i]->head).bodyindex[0] = (ppMVar1[i]->head).mdtbody[0]->arrayIdWorld;
        pMVar4 = ppMVar1[i];
        pMVar5 = (pMVar4->head).mdtbody[1];
        if (pMVar5 == (MdtBody *)0x0) {
          (pMVar4->head).bodyindex[1] = -1;
        }
        else {
          (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
        }
        i = i + 1;
        if ((int)uVar8 <= i) goto LAB_00010702;
      }
      else if (uVar7 != 0) {
        if (1 < uVar7) {
          if (2 < uVar7) {
                    
            MdtConstraintDCastContactGroup(*ppMVar1);
            ((*ppMVar1)->head).bodyindex[0] = ((*ppMVar1)->head).mdtbody[0]->arrayIdWorld;
            pMVar4 = *ppMVar1;
            pMVar5 = (pMVar4->head).mdtbody[1];
            if (pMVar5 == (MdtBody *)0x0) {
              (pMVar4->head).bodyindex[1] = -1;
            }
            else {
              (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
            }
            i = 1;
          }
          MdtConstraintDCastContactGroup(ppMVar1[i]);
          (ppMVar1[i]->head).bodyindex[0] = (ppMVar1[i]->head).mdtbody[0]->arrayIdWorld;
          pMVar4 = ppMVar1[i];
          pMVar5 = (pMVar4->head).mdtbody[1];
          if (pMVar5 == (MdtBody *)0x0) {
            (pMVar4->head).bodyindex[1] = -1;
          }
          else {
            (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
          }
          i = i + 1;
        }
        goto LAB_00010594;
      }
      do {
        MdtConstraintDCastContactGroup(ppMVar1[i]);
        (ppMVar1[i]->head).bodyindex[0] = (ppMVar1[i]->head).mdtbody[0]->arrayIdWorld;
        pMVar4 = ppMVar1[i];
        pMVar5 = (pMVar4->head).mdtbody[1];
        if (pMVar5 == (MdtBody *)0x0) {
          (pMVar4->head).bodyindex[1] = -1;
        }
        else {
          (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
        }
        iVar11 = i + 1;
        MdtConstraintDCastContactGroup(ppMVar1[iVar11]);
        (ppMVar1[iVar11]->head).bodyindex[0] = (ppMVar1[iVar11]->head).mdtbody[0]->arrayIdWorld;
        pMVar4 = ppMVar1[iVar11];
        pMVar5 = (pMVar4->head).mdtbody[1];
        if (pMVar5 == (MdtBody *)0x0) {
          (pMVar4->head).bodyindex[1] = -1;
        }
        else {
          (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
        }
        iVar11 = i + 2;
        MdtConstraintDCastContactGroup(ppMVar1[iVar11]);
        (ppMVar1[iVar11]->head).bodyindex[0] = (ppMVar1[iVar11]->head).mdtbody[0]->arrayIdWorld;
        pMVar4 = ppMVar1[iVar11];
        pMVar5 = (pMVar4->head).mdtbody[1];
        if (pMVar5 == (MdtBody *)0x0) {
          (pMVar4->head).bodyindex[1] = -1;
        }
        else {
          (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
        }
        iVar11 = i + 3;
        MdtConstraintDCastContactGroup(ppMVar1[iVar11]);
        (ppMVar1[iVar11]->head).bodyindex[0] = (ppMVar1[iVar11]->head).mdtbody[0]->arrayIdWorld;
        pMVar4 = ppMVar1[iVar11];
        pMVar5 = (pMVar4->head).mdtbody[1];
        if (pMVar5 == (MdtBody *)0x0) {
          (pMVar4->head).bodyindex[1] = -1;
        }
        else {
          (pMVar4->head).bodyindex[1] = pMVar5->arrayIdWorld;
        }
        i = i + 4;
      } while (i < (int)uVar8);
    }
LAB_00010702:
    if ((int)uVar8 < 1) {
      piVar9 = params->matrixSizeLog;
      if (piVar9 != (int *)0x0) {
        uVar8 = params->matrixSizeLogSize - 1;
        uVar8 = uVar8 & (0 < (int)uVar8) - 1;
        uVar7 = 0xffffffff - ((int)uVar8 >> 0x1f);
        goto LAB_00010863;
      }
    }
    else {
      MdtBclStartPartition(constraints);
      i = 0;
      if (0 < (int)uVar8) {
        uVar7 = uVar8 & 3;
        if ((int)uVar8 < 2) {
LAB_0001073f:
          (*(ppMVar1[i]->head).bclFunction)
                    (constraints,ppMVar1[i],keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
          i = i + 1;
          if ((int)uVar8 <= i) goto LAB_00010805;
        }
        else if (uVar7 != 0) {
          if (1 < uVar7) {
            if (2 < uVar7) {
              (*((*ppMVar1)->head).bclFunction)
                        (constraints,*ppMVar1,keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
            }
            i = (int)(2 < uVar7);
            (*(ppMVar1[i]->head).bclFunction)
                      (constraints,ppMVar1[i],keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
            i = i + 1;
          }
          goto LAB_0001073f;
        }
        do {
          (*(ppMVar1[i]->head).bclFunction)
                    (constraints,ppMVar1[i],keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
          (*(ppMVar1[i + 1]->head).bclFunction)
                    (constraints,ppMVar1[i + 1],keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
          (*(ppMVar1[i + 2]->head).bclFunction)
                    (constraints,ppMVar1[i + 2],keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
          (*(ppMVar1[i + 3]->head).bclFunction)
                    (constraints,ppMVar1[i + 3],keaTMArray,(MdtKeaBody **)ppMVar3,&bclParams);
          i = i + 4;
        } while (i < (int)uVar8);
      }
LAB_00010805:
      MdtBclEndPartition(constraints);
      partitionConstraintRows =
           constraints->num_rows_exc_padding_partition[constraints->num_partitions + -1];
      piVar9 = params->matrixSizeLog;
      if (piVar9 != (int *)0x0) {
                    
        if ((partitionConstraintRows & 3) == 0) {
          uVar8 = partitionConstraintRows;
          if ((int)partitionConstraintRows < 0) {
            uVar8 = partitionConstraintRows + 3;
          }
        }
        else {
          uVar7 = partitionConstraintRows;
          if ((int)partitionConstraintRows < 0) {
            uVar7 = partitionConstraintRows + 3;
          }
          uVar8 = (uVar7 & 0xfffffffc) + 4;
          if ((int)uVar8 < 0) {
            uVar8 = (uVar7 & 0xfffffffc) + 7;
          }
        }
        uVar7 = params->matrixSizeLogSize - 1;
        if ((int)uVar8 >> 2 < (int)uVar7) {
          uVar7 = (int)uVar8 >> 2;
        }
        uVar8 = 0xffffffff - ((int)uVar7 >> 0x1f);
LAB_00010863:
                    
        piVar9[uVar8 & uVar7] = piVar9[uVar8 & uVar7] + 1;
      }
    }
    if (maxPartitionConstraintRows < partitionConstraintRows) {
      maxPartitionConstraintRows = partitionConstraintRows;
    }
    partitionindex = partitionindex + 1;
    if (po->nPartitions <= partitionindex) {
      return maxPartitionConstraintRows;
    }
    ppMVar10 = po->bodies;
  } while( true );
}

/* ---- MdtPackPartition (exported as kd_MdtPackPartition, asm label "MdtPackPartition") ---- */
uint kd_MdtPackPartition(MdtPartitionOutput *po,uint partitionindex,MeReal stepSize,
                     MdtWorldParams *params,MdtKeaParameters *keaParams,
                     MdtKeaTransformation *keaTMArray,MdtKeaConstraints *constraints)

{
  MdtBody **ppMVar1;
  MdtBaseConstraint **ppMVar2;
  MdtBody **ppMVar3;
  MdtBaseConstraint *pMVar4;
  MdtBody *pMVar5;
  uint uVar6;
  uint uVar7;
  uint uVar8;
  int iVar9;
  int *piVar10;
  int iVar11;
  MeReal (*paMVar12) [4];
  MdtKeaTransformation *pMVar13;
  int constraintsSize;
  int bodiesSize;
  MdtBaseConstraint **clist;
  MdtBody **blist;
  uint partitionConstraintRows;
  int i;
  MdtBclSolverParameters bclParams;

  partitionConstraintRows = 0;
  bclParams.stepsize = stepSize;
  bclParams.epsilon = keaParams->epsilon;
  bclParams.gamma = keaParams->gamma;
  MdtBclInitConstraintRowList(constraints);
  ppMVar1 = po->bodies + po->bodiesStart[partitionindex];
  uVar7 = po->bodiesSize[partitionindex];
  ppMVar2 = po->constraints + po->constraintsStart[partitionindex];
  uVar8 = po->constraintsSize[partitionindex];
  i = 0;
  if (0 < (int)uVar7) {
    uVar6 = uVar7 & 3;
    if ((int)uVar7 < 2) {
LAB_00010b86:
      kd_MdtUpdateBodyForces(ppMVar1[i],stepSize,params->gravity);
      ppMVar3 = ppMVar1 + i;
      pMVar13 = keaTMArray + i;
      i = i + 1;
      paMVar12 = (*ppMVar3)->comTM;
      for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
        pMVar13->R0[0] = (*paMVar12)[0];
        paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
        pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
      }
      if ((int)uVar7 <= i) goto LAB_00010cca;
    }
    else if (uVar6 != 0) {
      if (1 < uVar6) {
        if (2 < uVar6) {
          kd_MdtUpdateBodyForces(*ppMVar1,stepSize,params->gravity);
          paMVar12 = (*ppMVar1)->comTM;
          pMVar13 = keaTMArray;
          for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
            pMVar13->R0[0] = (*paMVar12)[0];
            paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
            pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
          }
          i = 1;
        }
        kd_MdtUpdateBodyForces(ppMVar1[i],stepSize,params->gravity);
        ppMVar3 = ppMVar1 + i;
        pMVar13 = keaTMArray + i;
        i = i + 1;
        paMVar12 = (*ppMVar3)->comTM;
        for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
          pMVar13->R0[0] = (*paMVar12)[0];
          paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
          pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
        }
      }
      goto LAB_00010b86;
    }
    do {
      kd_MdtUpdateBodyForces(ppMVar1[i],stepSize,params->gravity);
      paMVar12 = ppMVar1[i]->comTM;
      pMVar13 = keaTMArray + i;
      for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
        pMVar13->R0[0] = (*paMVar12)[0];
        paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
        pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
      }
      iVar11 = i + 1;
      kd_MdtUpdateBodyForces(ppMVar1[iVar11],stepSize,params->gravity);
      paMVar12 = ppMVar1[iVar11]->comTM;
      pMVar13 = keaTMArray + iVar11;
      for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
        pMVar13->R0[0] = (*paMVar12)[0];
        paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
        pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
      }
      iVar11 = i + 2;
      kd_MdtUpdateBodyForces(ppMVar1[iVar11],stepSize,params->gravity);
      paMVar12 = ppMVar1[iVar11]->comTM;
      pMVar13 = keaTMArray + iVar11;
      for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
        pMVar13->R0[0] = (*paMVar12)[0];
        paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
        pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
      }
      iVar11 = i + 3;
      kd_MdtUpdateBodyForces(ppMVar1[iVar11],stepSize,params->gravity);
      paMVar12 = ppMVar1[iVar11]->comTM;
      pMVar13 = keaTMArray + iVar11;
      for (iVar9 = 0x10; iVar9 != 0; iVar9 = iVar9 + -1) {
        pMVar13->R0[0] = (*paMVar12)[0];
        paMVar12 = (MeReal (*) [4])(*paMVar12 + 1);
        pMVar13 = (MdtKeaTransformation *)(pMVar13->R0 + 1);
      }
      i = i + 4;
    } while (i < (int)uVar7);
  }
LAB_00010cca:
  i = 0;
  if (0 < (int)uVar8) {
    uVar7 = uVar8 & 3;
    if ((int)uVar8 < 2) {
LAB_00010cea:
      MdtConstraintDCastContactGroup(ppMVar2[i]);
      (ppMVar2[i]->head).bodyindex[0] = (ppMVar2[i]->head).mdtbody[0]->arrayIdPartition;
      pMVar4 = ppMVar2[i];
      pMVar5 = (pMVar4->head).mdtbody[1];
      if (pMVar5 == (MdtBody *)0x0) {
        (pMVar4->head).bodyindex[1] = -1;
      }
      else {
        (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
      }
      i = i + 1;
      if ((int)uVar8 <= i) goto LAB_00010e69;
    }
    else if (uVar7 != 0) {
      if (1 < uVar7) {
        if (2 < uVar7) {
                    
          MdtConstraintDCastContactGroup(*ppMVar2);
          ((*ppMVar2)->head).bodyindex[0] = ((*ppMVar2)->head).mdtbody[0]->arrayIdPartition;
          pMVar4 = *ppMVar2;
          pMVar5 = (pMVar4->head).mdtbody[1];
          if (pMVar5 == (MdtBody *)0x0) {
            (pMVar4->head).bodyindex[1] = -1;
          }
          else {
            (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
          }
          i = 1;
        }
        MdtConstraintDCastContactGroup(ppMVar2[i]);
        (ppMVar2[i]->head).bodyindex[0] = (ppMVar2[i]->head).mdtbody[0]->arrayIdPartition;
        pMVar4 = ppMVar2[i];
        pMVar5 = (pMVar4->head).mdtbody[1];
        if (pMVar5 == (MdtBody *)0x0) {
          (pMVar4->head).bodyindex[1] = -1;
        }
        else {
          (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
        }
        i = i + 1;
      }
      goto LAB_00010cea;
    }
    do {
      MdtConstraintDCastContactGroup(ppMVar2[i]);
      (ppMVar2[i]->head).bodyindex[0] = (ppMVar2[i]->head).mdtbody[0]->arrayIdPartition;
      pMVar4 = ppMVar2[i];
      pMVar5 = (pMVar4->head).mdtbody[1];
      if (pMVar5 == (MdtBody *)0x0) {
        (pMVar4->head).bodyindex[1] = -1;
      }
      else {
        (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
      }
      iVar9 = i + 1;
      MdtConstraintDCastContactGroup(ppMVar2[iVar9]);
      (ppMVar2[iVar9]->head).bodyindex[0] = (ppMVar2[iVar9]->head).mdtbody[0]->arrayIdPartition;
      pMVar4 = ppMVar2[iVar9];
      pMVar5 = (pMVar4->head).mdtbody[1];
      if (pMVar5 == (MdtBody *)0x0) {
        (pMVar4->head).bodyindex[1] = -1;
      }
      else {
        (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
      }
      iVar9 = i + 2;
      MdtConstraintDCastContactGroup(ppMVar2[iVar9]);
      (ppMVar2[iVar9]->head).bodyindex[0] = (ppMVar2[iVar9]->head).mdtbody[0]->arrayIdPartition;
      pMVar4 = ppMVar2[iVar9];
      pMVar5 = (pMVar4->head).mdtbody[1];
      if (pMVar5 == (MdtBody *)0x0) {
        (pMVar4->head).bodyindex[1] = -1;
      }
      else {
        (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
      }
      iVar9 = i + 3;
      MdtConstraintDCastContactGroup(ppMVar2[iVar9]);
      (ppMVar2[iVar9]->head).bodyindex[0] = (ppMVar2[iVar9]->head).mdtbody[0]->arrayIdPartition;
      pMVar4 = ppMVar2[iVar9];
      pMVar5 = (pMVar4->head).mdtbody[1];
      if (pMVar5 == (MdtBody *)0x0) {
        (pMVar4->head).bodyindex[1] = -1;
      }
      else {
        (pMVar4->head).bodyindex[1] = pMVar5->arrayIdPartition;
      }
      i = i + 4;
    } while (i < (int)uVar8);
  }
LAB_00010e69:
  if ((int)uVar8 < 1) {
    piVar10 = params->matrixSizeLog;
    if (piVar10 == (int *)0x0) {
      return 0;
    }
    uVar8 = params->matrixSizeLogSize - 1;
    uVar8 = uVar8 & (0 < (int)uVar8) - 1;
    uVar7 = 0xffffffff - ((int)uVar8 >> 0x1f);
    goto LAB_00010fdd;
  }
  MdtBclStartPartition(constraints);
  i = 0;
  if (0 < (int)uVar8) {
    uVar7 = uVar8 & 3;
    if ((int)uVar8 < 2) {
LAB_00010ea6:
      (*(ppMVar2[i]->head).bclFunction)
                (constraints,ppMVar2[i],keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
      i = i + 1;
      if ((int)uVar8 <= i) goto LAB_00010f7f;
    }
    else if (uVar7 != 0) {
      if (1 < uVar7) {
        if (2 < uVar7) {
          (*((*ppMVar2)->head).bclFunction)
                    (constraints,*ppMVar2,keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
        }
        i = (int)(2 < uVar7);
        (*(ppMVar2[i]->head).bclFunction)
                  (constraints,ppMVar2[i],keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
        i = i + 1;
      }
      goto LAB_00010ea6;
    }
    do {
      (*(ppMVar2[i]->head).bclFunction)
                (constraints,ppMVar2[i],keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
      (*(ppMVar2[i + 1]->head).bclFunction)
                (constraints,ppMVar2[i + 1],keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
      (*(ppMVar2[i + 2]->head).bclFunction)
                (constraints,ppMVar2[i + 2],keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
      (*(ppMVar2[i + 3]->head).bclFunction)
                (constraints,ppMVar2[i + 3],keaTMArray,(MdtKeaBody **)ppMVar1,&bclParams);
      i = i + 4;
    } while (i < (int)uVar8);
  }
LAB_00010f7f:
  MdtBclEndPartition(constraints);
  partitionConstraintRows =
       constraints->num_rows_exc_padding_partition[constraints->num_partitions + -1];
  piVar10 = params->matrixSizeLog;
  if (piVar10 == (int *)0x0) {
    return partitionConstraintRows;
  }
                    
  if ((partitionConstraintRows & 3) == 0) {
    uVar8 = partitionConstraintRows;
    if ((int)partitionConstraintRows < 0) {
      uVar8 = partitionConstraintRows + 3;
    }
  }
  else {
    uVar7 = partitionConstraintRows;
    if ((int)partitionConstraintRows < 0) {
      uVar7 = partitionConstraintRows + 3;
    }
    uVar8 = (uVar7 & 0xfffffffc) + 4;
    if ((int)uVar8 < 0) {
      uVar8 = (uVar7 & 0xfffffffc) + 7;
    }
  }
  uVar7 = params->matrixSizeLogSize - 1;
  if ((int)uVar8 >> 2 < (int)uVar7) {
    uVar7 = (int)uVar8 >> 2;
  }
  uVar8 = 0xffffffff - ((int)uVar7 >> 0x1f);
LAB_00010fdd:
                    
  piVar10[uVar8 & uVar7] = piVar10[uVar8 & uVar7] + 1;
  return partitionConstraintRows;
}

/* ---- MdtUnpackForces (exported as kd_MdtUnpackForces, asm label "MdtUnpackForces") ---- */
uint kd_MdtUnpackForces(MdtKeaForcePair *force,uint partitionindex,MdtPartitionOutput *po)

{
  float fVar1;
  float fVar2;
  float fVar3;
  kd_iptr iVar4;
  void *pvVar5;
  MdtKeaForcePair *pMVar6;
  uint uVar7;
  uint uVar8;
  MdtBaseConstraint **local_18;
  int mdtCNum;

  uVar7 = 0;
  mdtCNum = 0;
  local_18 = po->constraints + po->constraintsStart[partitionindex];
  uVar8 = uVar7;
  if (0 < po->constraintsSize[partitionindex]) {
    do {
                    
      pvVar5 = MdtConstraintDCastContactGroup(*local_18);
      if (pvVar5 == (void *)0x0) {
        uVar7 = uVar8 + 1;
        pMVar6 = force + uVar8;
        ((*local_18)->head).resultForce[0][0] = (pMVar6->primary_body).force[0];
        ((*local_18)->head).resultTorque[0][0] = (pMVar6->primary_body).torque[0];
        ((*local_18)->head).resultForce[1][0] = (pMVar6->secondary_body).force[0];
        ((*local_18)->head).resultTorque[1][0] = (pMVar6->secondary_body).torque[0];
        ((*local_18)->head).resultForce[0][1] = (pMVar6->primary_body).force[1];
        ((*local_18)->head).resultTorque[0][1] = (pMVar6->primary_body).torque[1];
        ((*local_18)->head).resultForce[1][1] = (pMVar6->secondary_body).force[1];
        ((*local_18)->head).resultTorque[1][1] = (pMVar6->secondary_body).torque[1];
        ((*local_18)->head).resultForce[0][2] = (pMVar6->primary_body).force[2];
        ((*local_18)->head).resultTorque[0][2] = (pMVar6->primary_body).torque[2];
        ((*local_18)->head).resultForce[1][2] = (pMVar6->secondary_body).force[2];
        ((*local_18)->head).resultTorque[1][2] = (pMVar6->secondary_body).torque[2];
        ((*local_18)->head).resultForce[0][3] = (MeReal)(pMVar6->primary_body).pad0;
        ((*local_18)->head).resultTorque[0][3] = (MeReal)(pMVar6->primary_body).pad1;
        ((*local_18)->head).resultForce[1][3] = (MeReal)(pMVar6->secondary_body).pad0;
        ((*local_18)->head).resultTorque[1][3] = (MeReal)(pMVar6->secondary_body).pad1;
      }
      else {
                    
        iVar4 = *(kd_iptr *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->first - (char *)0)));
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][0] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][0] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][0] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][0] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][1] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][1] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][1] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][1] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][2] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][2] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][2] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][2] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][3] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][3] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][3] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][3] - (char *)0))) = 0;
        *(undefined4 *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->normalForce - (char *)0))) = 0;
        uVar7 = uVar8;
        for (; iVar4 != 0; iVar4 = *(kd_iptr *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->nextContact - (char *)0)))) {
          pMVar6 = force + uVar7;
          fVar1 = (pMVar6->primary_body).force[0];
          *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[0][0] - (char *)0))) = fVar1;
          fVar2 = (pMVar6->primary_body).torque[0];
          *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[0][0] - (char *)0))) = fVar2;
          *(MeReal *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[1][0] - (char *)0))) = (pMVar6->secondary_body).force[0];
          fVar3 = *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][0] - (char *)0)));
          *(MeReal *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[1][0] - (char *)0))) = (pMVar6->secondary_body).torque[0];
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][0] - (char *)0))) = fVar1 + fVar3;
          fVar1 = *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[1][0] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][0] - (char *)0))) = fVar2 + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][0] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][0] - (char *)0))) = fVar1 + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][0] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][0] - (char *)0))) = *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[1][0] - (char *)0))) + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][0] - (char *)0)))
          ;
          fVar1 = (pMVar6->primary_body).force[1];
          *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[0][1] - (char *)0))) = fVar1;
          fVar2 = (pMVar6->primary_body).torque[1];
          *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[0][1] - (char *)0))) = fVar2;
          *(MeReal *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[1][1] - (char *)0))) = (pMVar6->secondary_body).force[1];
          fVar3 = *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][1] - (char *)0)));
          *(MeReal *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[1][1] - (char *)0))) = (pMVar6->secondary_body).torque[1];
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][1] - (char *)0))) = fVar1 + fVar3;
          fVar1 = *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[1][1] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][1] - (char *)0))) = fVar2 + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][1] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][1] - (char *)0))) = fVar1 + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][1] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][1] - (char *)0))) = *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[1][1] - (char *)0))) + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][1] - (char *)0)))
          ;
          fVar1 = (pMVar6->primary_body).force[2];
          *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[0][2] - (char *)0))) = fVar1;
          fVar2 = (pMVar6->primary_body).torque[2];
          *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[0][2] - (char *)0))) = fVar2;
          *(MeReal *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[1][2] - (char *)0))) = (pMVar6->secondary_body).force[2];
          fVar3 = *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][2] - (char *)0)));
          *(MeReal *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[1][2] - (char *)0))) = (pMVar6->secondary_body).torque[2];
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[0][2] - (char *)0))) = fVar1 + fVar3;
          fVar1 = *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[1][2] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][2] - (char *)0))) = fVar2 + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[0][2] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][2] - (char *)0))) = fVar1 + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultForce[1][2] - (char *)0)));
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][2] - (char *)0))) = *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultTorque[1][2] - (char *)0))) + *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->head.resultTorque[1][2] - (char *)0)))
          ;
          *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->normalForce - (char *)0))) =
               *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->normal[2] - (char *)0))) * *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[0][2] - (char *)0))) +
               *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->normal[1] - (char *)0))) * *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[0][1] - (char *)0))) +
               *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->normal[0] - (char *)0))) * *(float *)(iVar4 + ((int)((char *)&((struct MdtContact *)0)->head.resultForce[0][0] - (char *)0))) +
               *(float *)((kd_iptr)pvVar5 + ((int)((char *)&((struct MdtContactGroup *)0)->normalForce - (char *)0)));
          uVar7 = uVar7 + 1;
        }
      }
      local_18 = local_18 + 1;
      mdtCNum = mdtCNum + 1;
      uVar8 = uVar7;
    } while (mdtCNum < po->constraintsSize[partitionindex]);
  }
  return uVar7;
}

/* ---- MdtKeaConstraintsCreateFromChunk (exported as kd_MdtKeaConstraintsCreateFromChunk, asm label "MdtKeaConstraintsCreateFromChunk") ---- */
MdtKeaConstraints *
kd_MdtKeaConstraintsCreateFromChunk(MeChunk *chunk,int maxPartitions,int maxKeaConstraints,int maxRows)

{
  int iVar1;
  int iVar2;
  MdtKeaConstraints *pMVar3;
  int iVar4;
  MeReal *pMVar5;
  MdtKeaForcePair *pMVar6;
  MdtKeaBodyIndexPair *paiVar7;
  int *piVar8;
  int xiSize;
  int cSize;
  int loSize;
  int hiSize;
  int lambdaSize;
  int forceSize;
  int slipfactorSize;
  int xgammaSize;
  int jsizeSize;
  int jofsSize;
  int jbodySize;
  int maxRowsIncPadding;

  iVar1 = maxRows + (maxPartitions + maxKeaConstraints) * 4;
  iVar2 = maxPartitions * 0xc + (int)sizeof(MdtKeaConstraints);
  if (0 < maxKeaConstraints) {
    jbodySize = maxKeaConstraints * 8;
    if ((jbodySize & 0x3fU) != 0) {
      jbodySize = (jbodySize - (jbodySize & 0x3fU)) + 0x40;
    }
    jsizeSize = maxKeaConstraints * 4;
    xgammaSize = maxRows * 4;
    if ((xgammaSize & 0x3fU) != 0) {
      xgammaSize = (xgammaSize - (xgammaSize & 0x3fU)) + 0x40;
    }
    slipfactorSize = maxRows * 4;
    if ((slipfactorSize & 0x3fU) != 0) {
      slipfactorSize = (slipfactorSize - (slipfactorSize & 0x3fU)) + 0x40;
    }
    lambdaSize = maxRows * 4;
    forceSize = maxKeaConstraints * 0x40;
    if ((lambdaSize & 0x3fU) != 0) {
      lambdaSize = (lambdaSize - (lambdaSize & 0x3fU)) + 0x40;
    }
    hiSize = maxRows * 4;
    if ((hiSize & 0x3fU) != 0) {
      hiSize = (hiSize - (hiSize & 0x3fU)) + 0x40;
    }
    loSize = maxRows * 4;
    if ((loSize & 0x3fU) != 0) {
      loSize = (loSize - (loSize & 0x3fU)) + 0x40;
    }
    cSize = maxRows * 4;
    if ((cSize & 0x3fU) != 0) {
      cSize = (cSize - (cSize & 0x3fU)) + 0x40;
    }
    xiSize = maxRows * 4;
    if ((xiSize & 0x3fU) != 0) {
      xiSize = (xiSize - (xiSize & 0x3fU)) + 0x40;
    }
    iVar4 = iVar1;
    if (iVar1 < 0) {
      iVar4 = iVar1 + 3;
    }
    iVar2 = jbodySize + maxKeaConstraints * 0x48 + xgammaSize + slipfactorSize + lambdaSize + hiSize
            + loSize + cSize + xiSize + (iVar4 >> 2) * 0xc0 + 0x280 + iVar2;
    jofsSize = jsizeSize;
  }
  pMVar3 = MeChunkGetMem(chunk,iVar2);
  pMVar3->max_partitions = maxPartitions;
  pMVar3->max_constraints = maxKeaConstraints;
  pMVar3->num_rows_exc_padding_partition = &pMVar3[1].num_partitions;
  piVar8 = &pMVar3[1].num_partitions + maxPartitions;
  pMVar3->num_rows_inc_padding_partition = piVar8;
  pMVar3->num_constraints_partition = piVar8 + maxPartitions;
  if (maxKeaConstraints < 1) {
    pMVar3->max_rows_exc_padding = 0;
    pMVar3->max_rows_inc_padding = 0;
    pMVar3->Jbody = (MdtKeaBodyIndexPair *)0x0;
    pMVar3->Jofs = (int *)0x0;
    pMVar3->Jsize = (int *)0x0;
    pMVar3->xgamma = (MeReal *)0x0;
    pMVar3->slipfactor = (MeReal *)0x0;
    pMVar3->force = (MdtKeaForcePair *)0x0;
    pMVar3->lambda = (MeReal *)0x0;
    pMVar3->hi = (MeReal *)0x0;
    pMVar3->lo = (MeReal *)0x0;
    pMVar3->c = (MeReal *)0x0;
    pMVar3->xi = (MeReal *)0x0;
    pMVar3->Jstore = (MdtKeaJBlockPair *)0x0;
  }
  else {
    pMVar3->max_rows_exc_padding = maxRows;
    pMVar3->max_rows_inc_padding = iVar1;
    paiVar7 = (MdtKeaBodyIndexPair *)
              (maxPartitions * 4 + 0x3f + (kd_iptr)(piVar8 + maxPartitions) & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->Jbody = paiVar7;
    piVar8 = (int *)((kd_iptr)*paiVar7 + jbodySize);
    pMVar3->Jofs = piVar8;
    piVar8 = (int *)((kd_iptr)piVar8 + jofsSize);
    pMVar3->Jsize = piVar8;
    pMVar5 = (MeReal *)(jsizeSize + 0x3f + (kd_iptr)piVar8 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->xgamma = pMVar5;
    pMVar5 = (MeReal *)(xgammaSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->slipfactor = pMVar5;
    pMVar6 = (MdtKeaForcePair *)(slipfactorSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->force = pMVar6;
    pMVar5 = (MeReal *)((kd_iptr)(pMVar6->secondary_body).torque + forceSize + 0xf & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->lambda = pMVar5;
    pMVar5 = (MeReal *)(lambdaSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->hi = pMVar5;
    pMVar5 = (MeReal *)(hiSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->lo = pMVar5;
    pMVar5 = (MeReal *)(loSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->c = pMVar5;
    pMVar5 = (MeReal *)(cSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
    pMVar3->xi = pMVar5;
    pMVar3->Jstore = (MdtKeaJBlockPair *)(xiSize + 0x3f + (kd_iptr)pMVar5 & (0xffffffc0 | ~(kd_uptr)0xffffffffU));
  }
  return pMVar3;
}

/* ---- MdtDefaultSimErrorCallBack (exported as kd_MdtDefaultSimErrorCallBack, asm label "MdtDefaultSimErrorCallBack") ---- */
void kd_MdtDefaultSimErrorCallBack(MdtKeaConstraints *kc,MdtKeaBody **kb,int nBodies,void *secbdata)

{
  MdtKeaBody *pMVar1;
  int iVar2;
  int iVar3;

  iVar2 = 0;
  if (0 < nBodies) {
    if ((nBodies < 2) || ((nBodies & 1U) != 0)) {
                    
      pMVar1 = *kb;
      pMVar1->force[0] = 0.0;
      pMVar1->force[1] = 0.0;
      pMVar1->force[2] = 0.0;
      pMVar1->torque[0] = 0.0;
      pMVar1->torque[1] = 0.0;
      pMVar1->torque[2] = 0.0;
      pMVar1->accel[0] = 0.0;
      pMVar1->accel[1] = 0.0;
      pMVar1->accel[2] = 0.0;
      pMVar1->accelrot[0] = 0.0;
      pMVar1->accelrot[1] = 0.0;
      pMVar1->accelrot[2] = 0.0;
      pMVar1->vel[0] = 0.0;
      pMVar1->vel[1] = 0.0;
      pMVar1->vel[2] = 0.0;
      pMVar1->velrot[0] = 0.0;
      pMVar1->velrot[1] = 0.0;
      pMVar1->velrot[2] = 0.0;
      iVar2 = 1;
      if (nBodies < 2) goto LAB_00011a82;
    }
    do {
      pMVar1 = kb[iVar2];
      pMVar1->force[0] = 0.0;
      pMVar1->force[1] = 0.0;
      pMVar1->force[2] = 0.0;
      pMVar1->torque[0] = 0.0;
      pMVar1->torque[1] = 0.0;
      pMVar1->torque[2] = 0.0;
      pMVar1->accel[0] = 0.0;
      pMVar1->accel[1] = 0.0;
      pMVar1->accel[2] = 0.0;
      pMVar1->accelrot[0] = 0.0;
      pMVar1->accelrot[1] = 0.0;
      pMVar1->accelrot[2] = 0.0;
      pMVar1->vel[0] = 0.0;
      pMVar1->vel[1] = 0.0;
      pMVar1->vel[2] = 0.0;
      pMVar1->velrot[0] = 0.0;
      pMVar1->velrot[1] = 0.0;
      pMVar1->velrot[2] = 0.0;
      pMVar1 = kb[iVar2 + 1];
      iVar2 = iVar2 + 2;
      pMVar1->force[0] = 0.0;
      pMVar1->force[1] = 0.0;
      pMVar1->force[2] = 0.0;
      pMVar1->torque[0] = 0.0;
      pMVar1->torque[1] = 0.0;
      pMVar1->torque[2] = 0.0;
      pMVar1->accel[0] = 0.0;
      pMVar1->accel[1] = 0.0;
      pMVar1->accel[2] = 0.0;
      pMVar1->accelrot[0] = 0.0;
      pMVar1->accelrot[1] = 0.0;
      pMVar1->accelrot[2] = 0.0;
      pMVar1->vel[0] = 0.0;
      pMVar1->vel[1] = 0.0;
      pMVar1->vel[2] = 0.0;
      pMVar1->velrot[0] = 0.0;
      pMVar1->velrot[1] = 0.0;
      pMVar1->velrot[2] = 0.0;
    } while (iVar2 < nBodies);
  }
LAB_00011a82:
  iVar2 = 0;
  if (0 < kc->num_constraints) {
    do {
      iVar3 = iVar2 + 1;
      kc->force[iVar2].primary_body.force[0] = 0.0;
      kc->force[iVar2].primary_body.force[1] = 0.0;
      kc->force[iVar2].primary_body.force[2] = 0.0;
      kc->force[iVar2].primary_body.torque[0] = 0.0;
      kc->force[iVar2].primary_body.torque[1] = 0.0;
      kc->force[iVar2].primary_body.torque[2] = 0.0;
      kc->force[iVar2].secondary_body.force[0] = 0.0;
      kc->force[iVar2].secondary_body.force[1] = 0.0;
      kc->force[iVar2].secondary_body.force[2] = 0.0;
      kc->force[iVar2].secondary_body.torque[0] = 0.0;
      kc->force[iVar2].secondary_body.torque[1] = 0.0;
      kc->force[iVar2].secondary_body.torque[2] = 0.0;
      iVar2 = iVar3;
    } while (iVar3 < kc->num_constraints);
  }
  MeWarning(0,"MdtDefaultSimErrorCallBack: Error in simulation.");
  return;
}

/* ---- MdtUnpackBodies (exported as kd_MdtUnpackBodies, asm label "MdtUnpackBodies") ---- */
void kd_MdtUnpackBodies(MdtKeaTransformation *keaTMArray,uint partitionindex,MdtPartitionOutput *po)

{
  MdtBody **ppMVar1;
  int iVar2;
  int iVar3;
  int iVar4;
  MdtBody **blist;

  ppMVar1 = po->bodies;
  iVar2 = po->bodiesStart[partitionindex];
  if (0 < po->bodiesSize[partitionindex]) {
    iVar4 = 0;
    do {
      iVar3 = iVar2 + iVar4;
      iVar4 = iVar4 + 1;
      UpdateBodyTransform(ppMVar1[iVar3],keaTMArray);
      keaTMArray = keaTMArray + 1;
    } while (iVar4 < po->bodiesSize[partitionindex]);
  }
  return;
}

/* ---- MdtPartitionGetSafeTime (exported as kd_MdtPartitionGetSafeTime, asm label "MdtPartitionGetSafeTime") ---- */
MeReal kd_MdtPartitionGetSafeTime(MdtPartitionOutput *po,int i)

{
  int iVar1;
  float fVar2;
  MdtBody **ppMVar3;
  int iVar4;
  uint uVar5;

  fVar2 = 3.4028235e+38;
  iVar4 = po->bodiesStart[i];
  iVar1 = po->bodiesSize[i] + iVar4;
  if (iVar1 <= iVar4) {
    return 3.4028235e+38;
  }
  ppMVar3 = po->bodies;
  uVar5 = iVar1 - iVar4 & 3;
  if (iVar4 + 1 < iVar1) {
    if (uVar5 == 0) goto LAB_00011c08;
    if (1 < uVar5) {
      if (2 < uVar5) {
        fVar2 = ppMVar3[iVar4]->safeTime;
        if (3.4028235e+38 <= fVar2) {
          fVar2 = 3.4028235e+38;
        }
        iVar4 = iVar4 + 1;
      }
      if (ppMVar3[iVar4]->safeTime < fVar2) {
        fVar2 = ppMVar3[iVar4]->safeTime;
      }
      iVar4 = iVar4 + 1;
    }
  }
  if (ppMVar3[iVar4]->safeTime < fVar2) {
    fVar2 = ppMVar3[iVar4]->safeTime;
  }
  iVar4 = iVar4 + 1;
  if (iVar1 <= iVar4) {
    return fVar2;
  }
LAB_00011c08:
  do {
    if (ppMVar3[iVar4]->safeTime < fVar2) {
      fVar2 = ppMVar3[iVar4]->safeTime;
    }
    if (ppMVar3[iVar4 + 1]->safeTime < fVar2) {
      fVar2 = ppMVar3[iVar4 + 1]->safeTime;
    }
    if (ppMVar3[iVar4 + 2]->safeTime < fVar2) {
      fVar2 = ppMVar3[iVar4 + 2]->safeTime;
    }
    if (ppMVar3[iVar4 + 3]->safeTime < fVar2) {
      fVar2 = ppMVar3[iVar4 + 3]->safeTime;
    }
    iVar4 = iVar4 + 4;
  } while (iVar4 < iVar1);
  return fVar2;
}
