/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/MdtSpring.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for MdtSpring.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- imports needing an explicit declaration --- */
/* BaseConstraintCreate */
extern void * BaseConstraintCreate(void *);

/* BaseConstraintReset */
extern void BaseConstraintReset(void *);

/* BaseConstraintSetAxis */
extern void BaseConstraintSetAxis(void *, float, float, float);

/* BaseConstraintSetBodies */
extern void BaseConstraintSetBodies(void *, void *, void *);

/* ConvertCOMPositionVector */
extern void ConvertCOMPositionVector(void *, void *, void *, void *);

/* ---- forward declarations ---- */
MdtSpringID kd_MdtSpringCreate(MdtWorldID w) KD_MANGLED("MdtSpringCreate");
void kd_MdtSpringReset(MdtSpringID j) KD_MANGLED("MdtSpringReset");
MdtConstraintID kd_MdtSpringQuaConstraint(MdtSpringID j) KD_MANGLED("MdtSpringQuaConstraint");
MdtSpringID kd_MdtConstraintDCastSpring(MdtConstraintID c) KD_MANGLED("MdtConstraintDCastSpring");
void kd_MdtSpringGetPosition(MdtSpringID j,MeReal *v,uint bodyindex) KD_MANGLED("MdtSpringGetPosition");
MdtLimitID kd_MdtSpringGetLimit(MdtSpringID j) KD_MANGLED("MdtSpringGetLimit");
void kd_MdtSpringSetPosition(MdtSpringID j,uint bodyindex,MeReal x,MeReal y,MeReal z) KD_MANGLED("MdtSpringSetPosition");
void kd_MdtSpringSetLimit(MdtSpringID j,MdtLimitID NewLimit) KD_MANGLED("MdtSpringSetLimit");
void kd_MdtSpringSetNaturalLength(MdtSpringID j,MeReal NewNaturalLength) KD_MANGLED("MdtSpringSetNaturalLength");
void kd_MdtSpringSetStiffness(MdtSpringID j,MeReal NewStiffness) KD_MANGLED("MdtSpringSetStiffness");
void kd_MdtSpringSetDamping(MdtSpringID j,MeReal NewDamping) KD_MANGLED("MdtSpringSetDamping");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- MdtSpringCreate (exported as kd_MdtSpringCreate, asm label "MdtSpringCreate") ---- */
MdtSpringID kd_MdtSpringCreate(MdtWorldID w)

{
  MdtSpringID pMVar1;
  int iVar2;
  MdtSpringID pMVar3;

  pMVar1 = BaseConstraintCreate(w);
  pMVar3 = (MdtSpringID)0x0;
  if (pMVar1 != (MdtSpringID)0x0) {
                    
    (pMVar1->head).tag = 0xe;
    (pMVar1->head).bclFunction = MdtBclAddSpring;
    (pMVar1->head).maxRows = 1;
    (pMVar1->head).setBodyFunc = BaseConstraintSetBodies;
    (pMVar1->head).setAxisFunc = BaseConstraintSetAxis;
    iVar2 = MdtConstraintIsEnabled(pMVar1);
    if (iVar2 != 0) {
      MdtConstraintDisable(pMVar1);
    }
    pMVar1->pos2[0] = 0.0;
    pMVar1->pos1[0] = 0.0;
    pMVar1->pos2[1] = 0.0;
    pMVar1->pos1[1] = 0.0;
    pMVar1->pos2[2] = 0.0;
    pMVar1->pos1[2] = 0.0;
    MdtLimitReset(&pMVar1->limit);
                    
    (pMVar1->limit).limit[0].stiffness = 1.0;
    (pMVar1->limit).limit[1].stiffness = 1.0;
    MdtLimitActivateLimits(&pMVar1->limit,1);
    BaseConstraintReset(pMVar1);
    pMVar3 = pMVar1;
  }
  return pMVar3;
}

/* ---- MdtSpringReset (exported as kd_MdtSpringReset, asm label "MdtSpringReset") ---- */
void kd_MdtSpringReset(MdtSpringID j)

{
  int iVar1;

  iVar1 = MdtConstraintIsEnabled(j);
  if (iVar1 != 0) {
    MdtConstraintDisable(j);
  }
  j->pos2[0] = 0.0;
  j->pos1[0] = 0.0;
  j->pos2[1] = 0.0;
  j->pos1[1] = 0.0;
  j->pos2[2] = 0.0;
  j->pos1[2] = 0.0;
  MdtLimitReset(&j->limit);
                    
  (j->limit).limit[0].stiffness = 1.0;
  (j->limit).limit[1].stiffness = 1.0;
  MdtLimitActivateLimits(&j->limit,1);
  BaseConstraintReset(j);
  return;
}

/* ---- MdtSpringQuaConstraint (exported as kd_MdtSpringQuaConstraint, asm label "MdtSpringQuaConstraint") ---- */
MdtConstraintID kd_MdtSpringQuaConstraint(MdtSpringID j)

{
  return (MdtConstraintID)j;
}

/* ---- MdtConstraintDCastSpring (exported as kd_MdtConstraintDCastSpring, asm label "MdtConstraintDCastSpring") ---- */
MdtSpringID kd_MdtConstraintDCastSpring(MdtConstraintID c)

{
  return (MdtSpringID)(((c->head).tag != 0xe) - 1 & (kd_uptr)c);
}

/* ---- MdtSpringGetPosition (exported as kd_MdtSpringGetPosition, asm label "MdtSpringGetPosition") ---- */
void kd_MdtSpringGetPosition(MdtSpringID j,MeReal *v,uint bodyindex)

{
  MdtBody *pMVar1;
  MeReal *pMVar2;
  
  if (bodyindex == 0) {
    pMVar2 = j->pos1;
    pMVar1 = (j->head).mdtbody[0];
  }
  else {
    pMVar2 = j->pos2;
    pMVar1 = (j->head).mdtbody[1];
  }
  ConvertCOMPositionVector(pMVar1,pMVar2,(void *)0x0,v);
  return;
}

/* ---- MdtSpringGetLimit (exported as kd_MdtSpringGetLimit, asm label "MdtSpringGetLimit") ---- */
MdtLimitID kd_MdtSpringGetLimit(MdtSpringID j)

{
  return &j->limit;
}

/* ---- MdtSpringSetPosition (exported as kd_MdtSpringSetPosition, asm label "MdtSpringSetPosition") ---- */
void kd_MdtSpringSetPosition(MdtSpringID j,uint bodyindex,MeReal x,MeReal y,MeReal z)

{
  MdtBody *pMVar1;
  MeReal *pMVar2;
  MeVector3 tmp;
  
  tmp[0] = x;
  tmp[1] = y;
  tmp[2] = z;
  if (bodyindex == 0) {
    pMVar2 = j->pos1;
    pMVar1 = (j->head).mdtbody[0];
  }
  else {
    pMVar2 = j->pos2;
    pMVar1 = (j->head).mdtbody[1];
  }
  ConvertCOMPositionVector((void *)0x0,tmp,pMVar1,pMVar2);
  MdtConstraintBodySetPosition(j,bodyindex,x,y,z);
  return;
}

/* ---- MdtSpringSetLimit (exported as kd_MdtSpringSetLimit, asm label "MdtSpringSetLimit") ---- */
void kd_MdtSpringSetLimit(MdtSpringID j,MdtLimitID NewLimit)

{
  void *pvVar1;
  int iVar2;
  MdtBclLimit *pMVar3;
  float fVar4;
  float fVar5;

  pMVar3 = &j->limit;
  MdtLimitReset(pMVar3);
  pvVar1 = MdtLimitGetLowerLimit(NewLimit);
  MdtLimitSetLowerLimit(pMVar3,pvVar1);
  pvVar1 = MdtLimitGetUpperLimit(NewLimit);
  MdtLimitSetUpperLimit(pMVar3,pvVar1);
  iVar2 = MdtLimitIsActive(NewLimit);
  MdtLimitActivateLimits(pMVar3,iVar2);
  fVar4 = MdtLimitGetMotorMaxForce(NewLimit);
  fVar5 = MdtLimitGetMotorDesiredVelocity(NewLimit);
  MdtLimitSetLimitedForceMotor(pMVar3,fVar5,fVar4);
  iVar2 = MdtLimitIsMotorized(NewLimit);
  MdtLimitActivateMotor(pMVar3,iVar2);
  return;
}

/* ---- MdtSpringSetNaturalLength (exported as kd_MdtSpringSetNaturalLength, asm label "MdtSpringSetNaturalLength") ---- */
void kd_MdtSpringSetNaturalLength(MdtSpringID j,MeReal NewNaturalLength)

{
                    
  (j->limit).limit[0].stop = NewNaturalLength;
  (j->limit).limit[1].stop = NewNaturalLength;
  return;
}

/* ---- MdtSpringSetStiffness (exported as kd_MdtSpringSetStiffness, asm label "MdtSpringSetStiffness") ---- */
void kd_MdtSpringSetStiffness(MdtSpringID j,MeReal NewStiffness)

{
                    
  (j->limit).limit[0].stiffness = NewStiffness;
  (j->limit).limit[1].stiffness = NewStiffness;
  return;
}

/* ---- MdtSpringSetDamping (exported as kd_MdtSpringSetDamping, asm label "MdtSpringSetDamping") ---- */
void kd_MdtSpringSetDamping(MdtSpringID j,MeReal NewDamping)

{
                    
  (j->limit).limit[0].damping = NewDamping;
  (j->limit).limit[1].damping = NewDamping;
  return;
}
