/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/McdConvexRegistration.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for McdConvexRegistration.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
MeBool kd_McdConvexMeshPrimitivesRegisterInteractions(McdFramework *frame) KD_MANGLED("McdConvexMeshPrimitivesRegisterInteractions");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- McdConvexMeshPrimitivesRegisterInteractions (exported as kd_McdConvexMeshPrimitivesRegisterInteractions, asm label "McdConvexMeshPrimitivesRegisterInteractions") ---- */
MeBool kd_McdConvexMeshPrimitivesRegisterInteractions(McdFramework *frame)

{
  McdConvexMeshConvexMeshRegisterInteraction(frame);
  McdBoxConvexMeshRegisterInteraction(frame);
  McdSphereConvexMeshRegisterInteraction(frame);
  McdCylinderConvexMeshRegisterInteraction(frame);
  McdConvexMeshTriangleListRegisterInteraction(frame);
  McdConvexMeshPlaneRegisterInteraction(frame);
  McdConvexMeshLineSegmentRegisterInteraction(frame);
  McdSphylConvexMeshRegisterInteraction(frame);
  return 1;
}
