/* Generated by make_shadow_metoolkit.sh -- do not edit. */
#define KD_RECOVERED_LIST(X) \
    X(McdBoxBoxIntersect) \
    X(McdBoxSphereIntersect) \
    X(McdCylinderPlaneIntersect) \
    X(McdSpherePlaneIntersect) \
    X(McdSphereSphereIntersect) \
    X(McdSphereTriangleListIntersect) \

