/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/keaLCP_new.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for keaLCP_new.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* --- imports needing an explicit declaration --- */
/* keaPopPoolFrame() */
extern void keaPopPoolFrame(void)
    KD_MANGLED("_Z15keaPopPoolFramev");

/* keaPushPoolFrame() */
extern void keaPushPoolFrame(void)
    KD_MANGLED("_Z16keaPushPoolFramev");

/* keaLCPSolver::commonPivot(int, int*, int*, int*, int*) */
extern int keaLCPSolver__commonPivot(void *, int, void *, void *, void *, void *)
    KD_MANGLED("_ZN12keaLCPSolver11commonPivotEiPiS0_S0_S0_");

/* keaLCPSolver::getClampIndices(int*, int*) */
extern void keaLCPSolver__getClampIndices(void *, void *, void *)
    KD_MANGLED("_ZN12keaLCPSolver15getClampIndicesEPiS0_");

/* keaLCPSolver::getFirstBadIndex() */
extern int keaLCPSolver__getFirstBadIndex(void *)
    KD_MANGLED("_ZN12keaLCPSolver16getFirstBadIndexEv");

/* keaLCPSolver::setClampedValues(int*, int*, int*, int*, int const*, int const*) */
extern void keaLCPSolver__setClampedValues(void *, void *, void *, void *, void *, void *, void *)
    KD_MANGLED("_ZN12keaLCPSolver16setClampedValuesEPiS0_S0_S0_PKiS2_");

/* keaLCPSolver::copyXtoInitialSolve() */
extern void keaLCPSolver__copyXtoInitialSolve(void *)
    KD_MANGLED("_ZN12keaLCPSolver19copyXtoInitialSolveEv");

/* keaLCPSolver::blockMurtyChooseNewIndices(int*, int*, int const*, int const*, int, int) */
extern int keaLCPSolver__blockMurtyChooseNewIndices(void *, void *, void *, void *, void *, int, int)
    KD_MANGLED("_ZN12keaLCPSolver26blockMurtyChooseNewIndicesEPiS0_PKiS2_ii");

/* keaLCPSolver::setLower(float*) */
extern void keaLCPSolver__setLower(void *, void *)
    KD_MANGLED("_ZN12keaLCPSolver8setLowerEPf");

/* keaLCPSolver::setUpper(float*) */
extern void keaLCPSolver__setUpper(void *, void *)
    KD_MANGLED("_ZN12keaLCPSolver8setUpperEPf");

/* keaLCPSolver::makeXandW(float*, int*, int, int*, int) */
extern void keaLCPSolver__makeXandW(void *, void *, void *, int, void *, int)
    KD_MANGLED("_ZN12keaLCPSolver9makeXandWEPfPiiS1_i");

/* ---- forward declarations ---- */
int kd_checkForCycles(int *I,int *C,int *hilohere,int *clampedhere,int iteration,int n) KD_MANGLED("_Z14checkForCyclesPKiS0_S0_S0_ii");
int __thiscall kd_keaLCPSolver__solveLCP (keaLCPSolver *this,keaMatrix *A,MeReal *b,MeReal *lower,MeReal *upper,int max_iterations, MeCPUResources cpuType,MeReal velocityZeroTol) KD_MANGLED("_ZN12keaLCPSolver8solveLCPEP9keaMatrixPfS2_S2_iP15_MeCPUResourcesf");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- checkForCycles (exported as kd_checkForCycles, asm label "kd_checkForCycles") ---- */
int kd_checkForCycles(int *I,int *C,int *hilohere,int *clampedhere,int iteration,int n)

{
  int iVar1;
  uint uVar2;
  uint uVar3;
  int iVar4;

  iVar4 = 0;
  uVar3 = 0x7fffffff >> (0x1eU - (char)iteration & 0x1f);
  if (0 < n) {
    uVar2 = n & 3;
    if (1 < n) {
      if (uVar2 == 0) goto LAB_00010055;
      if (1 < uVar2) {
        if (2 < uVar2) {
          if (*I == 0) {
            uVar3 = uVar3 & (*clampedhere ^ 0xffffffffU);
          }
          else {
            if ((uVar3 & *clampedhere) == 0) {
              return 0;
            }
            uVar3 = uVar3 & *clampedhere & (*C & *hilohere | (*C | *hilohere) ^ 0xffffffffU);
          }
          if (uVar3 == 0) {
            return 0;
          }
          iVar4 = 1;
        }
        if (I[iVar4] == 0) {
          uVar3 = uVar3 & (clampedhere[iVar4] ^ 0xffffffffU);
        }
        else {
          if ((uVar3 & clampedhere[iVar4]) == 0) {
            return 0;
          }
          uVar3 = uVar3 & clampedhere[iVar4] &
                  (C[iVar4] & hilohere[iVar4] | (C[iVar4] | hilohere[iVar4]) ^ 0xffffffffU);
        }
        if (uVar3 == 0) {
          return 0;
        }
        iVar4 = iVar4 + 1;
      }
    }
    if (I[iVar4] == 0) {
      uVar3 = uVar3 & (clampedhere[iVar4] ^ 0xffffffffU);
    }
    else {
      if ((uVar3 & clampedhere[iVar4]) == 0) {
        return 0;
      }
      uVar3 = uVar3 & clampedhere[iVar4] &
              (C[iVar4] & hilohere[iVar4] | (C[iVar4] | hilohere[iVar4]) ^ 0xffffffffU);
    }
    if ((uVar3 != 0) && (iVar4 = iVar4 + 1, iVar4 < n)) {
LAB_00010055:
      while( true ) {
        if (I[iVar4] == 0) {
          uVar3 = uVar3 & (clampedhere[iVar4] ^ 0xffffffffU);
        }
        else {
          if ((uVar3 & clampedhere[iVar4]) == 0) {
            return 0;
          }
          uVar3 = uVar3 & clampedhere[iVar4] &
                  (C[iVar4] & hilohere[iVar4] | (C[iVar4] | hilohere[iVar4]) ^ 0xffffffffU);
        }
        if (uVar3 == 0) {
          return 0;
        }
        iVar1 = iVar4 + 1;
        if (I[iVar1] == 0) {
          uVar3 = uVar3 & (clampedhere[iVar1] ^ 0xffffffffU);
        }
        else {
          if ((uVar3 & clampedhere[iVar1]) == 0) {
            return 0;
          }
          uVar3 = uVar3 & clampedhere[iVar1] &
                  (C[iVar1] & hilohere[iVar1] | (C[iVar1] | hilohere[iVar1]) ^ 0xffffffffU);
        }
        if (uVar3 == 0) {
          return 0;
        }
        iVar1 = iVar4 + 2;
        if (I[iVar1] == 0) {
          uVar3 = uVar3 & (clampedhere[iVar1] ^ 0xffffffffU);
        }
        else {
          if ((uVar3 & clampedhere[iVar1]) == 0) {
            return 0;
          }
          uVar3 = uVar3 & clampedhere[iVar1] &
                  (C[iVar1] & hilohere[iVar1] | (C[iVar1] | hilohere[iVar1]) ^ 0xffffffffU);
        }
        if (uVar3 == 0) {
          return 0;
        }
        iVar1 = iVar4 + 3;
        if (I[iVar1] == 0) {
          uVar3 = uVar3 & (clampedhere[iVar1] ^ 0xffffffffU);
        }
        else {
          if ((uVar3 & clampedhere[iVar1]) == 0) {
            return 0;
          }
          uVar3 = uVar3 & clampedhere[iVar1] &
                  (C[iVar1] & hilohere[iVar1] | (C[iVar1] | hilohere[iVar1]) ^ 0xffffffffU);
        }
        if (uVar3 == 0) break;
        iVar4 = iVar4 + 4;
        if (n <= iVar4) {
          return uVar3;
        }
      }
      return 0;
    }
  }
  return uVar3;
}

/* ---- solveLCP (exported as kd_keaLCPSolver__solveLCP, asm label "kd_keaLCPSolver__solveLCP") ---- */
int __thiscall
kd_keaLCPSolver__solveLCP
          (keaLCPSolver *this,keaMatrix *A,MeReal *b,MeReal *lower,MeReal *upper,int max_iterations,
          MeCPUResources cpuType,MeReal velocityZeroTol)

{
  int *piVar1;
  int iVar2;
  uint uVar3;
  int iVar4;
  uint uVar5;
  undefined4 extraout_EDX;
  uint uVar6;
  int *piVar7;
  MeReal *pMVar8;
  uint *puVar9;
  undefined4 *puVar10;
  int aiStackY_60 [3];
  undefined4 uStackY_54;
  int iStackY_50;
  uint uStack_40;
  int *unclamped;
  int *clamped;
  int *C;
  int *I;
  int inCycle;
  int iteration;
  int numClamped;
  int numUnclamped;

  this->velocityZeroTol = velocityZeroTol;
  this->A = A;
  this->cpuType = cpuType;
  iStackY_50 = 0x1024c;
  (**(void (**)(keaMatrix *, MeReal *, const MeReal *))(*(kd_iptr *)A + (4 * (int)sizeof(void *))))(A,this->x,b);
  iStackY_50 = 0x1025b;
  keaLCPSolver__setUpper(this,upper);
  iStackY_50 = 0x1026a;
  keaLCPSolver__setLower(this,lower);
  iStackY_50 = 0x10274;
  iVar2 = keaLCPSolver__getFirstBadIndex(this);
  if (iVar2 != this->n) {
                    
    uVar6 = this->n * 4 + 0xfU & 0xfffffff0;
  char *kd_frame = (char *)alloca(uVar6 * 6 + 48 * (int)(sizeof(void *) / 4));
  uint *auStack_3c = (uint *)(kd_frame + uVar6 * 6 + 36 * (int)(sizeof(void *) / 4));  /* KD_MATERIALISED_BASE(auStack_3c) */
    I = (int *)((kd_iptr)auStack_3c - uVar6);
    C = (int *)((kd_iptr)auStack_3c + (kd_uptr)uVar6 * -2);
    clamped = (int *)((kd_iptr)auStack_3c + (kd_uptr)uVar6 * -5);
    unclamped = (int *)((kd_iptr)auStack_3c + (kd_uptr)uVar6 * -6);
    *(keaLCPSolver **)((kd_frame + (5 * (int)sizeof(void *)))) = this;
    *(undefined4 *)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = 0x102b4;
    keaLCPSolver__copyXtoInitialSolve(*(void **)((kd_frame + (5 * (int)sizeof(void *)))));
    piVar7 = I;
    *(int **)((kd_frame + (7 * (int)sizeof(void *)))) = C;
    *(int **)((kd_frame + (6 * (int)sizeof(void *)))) = piVar7;
    *(keaLCPSolver **)((kd_frame + (5 * (int)sizeof(void *)))) = this;
    *(undefined4 *)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = 0x102c8;
    keaLCPSolver__getClampIndices
              (*(void **)((kd_frame + (5 * (int)sizeof(void *)))),*(void **)((kd_frame + (6 * (int)sizeof(void *)))),
               *(void **)((kd_frame + (7 * (int)sizeof(void *)))));
    piVar7 = this->cached;
    for (uVar5 = this->n & 0x3fffffff; uVar5 != 0; uVar5 = uVar5 - 1) {
      *piVar7 = 0;
      piVar7 = piVar7 + 1;
    }
    pMVar8 = this->clampedValues;
    for (uVar5 = this->c16c12n & 0x3fffffff; uVar5 != 0; uVar5 = uVar5 - 1) {
      *pMVar8 = 0.0;
      pMVar8 = pMVar8 + 1;
    }
    puVar9 = auStack_3c + -(kd_uptr)uVar6;
    for (uVar5 = this->n & 0x3fffffff; uVar5 != 0; uVar5 = uVar5 - 1) {
      *puVar9 = 0;
      puVar9 = puVar9 + 1;
    }
    puVar10 = (undefined4 *)((kd_iptr)auStack_3c + (kd_uptr)uVar6 * -3);
    for (uVar5 = this->n & 0x3fffffff; uVar5 != 0; uVar5 = uVar5 - 1) {
      *puVar10 = 0;
      puVar10 = puVar10 + 1;
    }
    iteration = 0;
    iVar2 = max_iterations;
    while (iVar2 != 0) {
      inCycle = 0;
      iVar2 = 0;
      *(undefined4 *)((kd_iptr)(kd_frame + (8 * (int)sizeof(void *)))) = 0x1032a;
      keaPushPoolFrame();
      uVar5 = this->n;
      auStack_3c[2] = uVar5;
      if (0 < (int)uVar5) {
        uVar3 = uVar5 & 3;
        if ((int)uVar5 < 2) {
LAB_00010348:
          *(uint *)((kd_iptr)auStack_3c + iVar2 * 4 + (kd_uptr)uVar6 * -3) =
               (I[iVar2] & 1U) + *(int *)((kd_iptr)auStack_3c + iVar2 * 4 + (kd_uptr)uVar6 * -3) * 2;
          uVar5 = auStack_3c[(kd_uptr)iVar2 - uVar6];
          auStack_3c[(kd_uptr)iVar2 - uVar6] = (C[iVar2] & 1U) + uVar5 * 2;
          iVar2 = iVar2 + 1;
          if ((int)auStack_3c[2] <= iVar2) goto LAB_0001041b;
        }
        else if (uVar3 != 0) {
          if (1 < uVar3) {
            if (2 < uVar3) {
              *(uint *)((kd_iptr)auStack_3c + (kd_uptr)uVar6 * -3) =
                   (*I & 1U) + *(int *)((kd_iptr)auStack_3c + (kd_uptr)uVar6 * -3) * 2;
              auStack_3c[-(kd_uptr)uVar6] = (*C & 1U) + auStack_3c[-(kd_uptr)uVar6] * 2;
            }
            uVar5 = (uint)(2 < uVar3);
            *(uint *)((kd_iptr)auStack_3c + uVar5 * 4 + (kd_uptr)uVar6 * -3) =
                 (I[uVar5] & 1U) + *(int *)((kd_iptr)auStack_3c + uVar5 * 4 + (kd_uptr)uVar6 * -3) * 2;
            auStack_3c[(kd_uptr)uVar5 - uVar6] = (C[uVar5] & 1U) + auStack_3c[(kd_uptr)uVar5 - uVar6] * 2;
            iVar2 = uVar5 + 1;
          }
          goto LAB_00010348;
        }
        do {
          *(uint *)((kd_iptr)auStack_3c + iVar2 * 4 + (kd_uptr)uVar6 * -3) =
               (I[iVar2] & 1U) + *(int *)((kd_iptr)auStack_3c + iVar2 * 4 + (kd_uptr)uVar6 * -3) * 2;
          auStack_3c[(kd_uptr)iVar2 - uVar6] = (C[iVar2] & 1U) + auStack_3c[(kd_uptr)iVar2 - uVar6] * 2;
          iVar4 = iVar2 + 1;
          *(uint *)((kd_iptr)auStack_3c + iVar4 * 4 + (kd_uptr)uVar6 * -3) =
               (I[iVar4] & 1U) + *(int *)((kd_iptr)auStack_3c + iVar4 * 4 + (kd_uptr)uVar6 * -3) * 2;
          auStack_3c[(kd_uptr)iVar4 - uVar6] = (C[iVar4] & 1U) + auStack_3c[(kd_uptr)iVar4 - uVar6] * 2;
          iVar4 = iVar2 + 2;
          *(uint *)((kd_iptr)auStack_3c + iVar4 * 4 + (kd_uptr)uVar6 * -3) =
               (I[iVar4] & 1U) + *(int *)((kd_iptr)auStack_3c + iVar4 * 4 + (kd_uptr)uVar6 * -3) * 2;
          auStack_3c[(kd_uptr)iVar4 - uVar6] = (C[iVar4] & 1U) + auStack_3c[(kd_uptr)iVar4 - uVar6] * 2;
          iVar4 = iVar2 + 3;
          iVar2 = iVar2 + 4;
          *(uint *)((kd_iptr)auStack_3c + iVar4 * 4 + (kd_uptr)uVar6 * -3) =
               (I[iVar4] & 1U) + *(int *)((kd_iptr)auStack_3c + iVar4 * 4 + (kd_uptr)uVar6 * -3) * 2;
          uVar5 = auStack_3c[(kd_uptr)iVar4 - uVar6];
          auStack_3c[(kd_uptr)iVar4 - uVar6] = (C[iVar4] & 1U) + uVar5 * 2;
        } while (iVar2 < (int)auStack_3c[2]);
      }
LAB_0001041b:
      piVar7 = C;
      *(uint *)((kd_iptr)(kd_frame + (8 * (int)sizeof(void *)))) = uVar5;
      piVar1 = I;
      *(int **)((kd_frame + (7 * (int)sizeof(void *)))) = piVar7;
      *(int **)((kd_frame + (6 * (int)sizeof(void *)))) = piVar1;
      *(int **)((kd_frame + (5 * (int)sizeof(void *)))) = &numUnclamped;
      piVar7 = unclamped;
      *(int **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = &numClamped;
      piVar1 = clamped;
      *(int **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))) = piVar7;
      *(int **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))) = piVar1;
      *(keaLCPSolver **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))) = this;
      numClamped = 0;
      numUnclamped = 0;
      *(undefined4 *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *)))) = 0x1044b;
      keaLCPSolver__setClampedValues
                (*(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))),
                 *(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))),
                 *(void **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))),*(void **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *))))
                 ,*(void **)((kd_frame + (5 * (int)sizeof(void *)))),
                 *(void **)((kd_frame + (6 * (int)sizeof(void *)))),*(void **)((kd_frame + (7 * (int)sizeof(void *))))
                );
      piVar7 = clamped;
      *(int *)((kd_frame + (6 * (int)sizeof(void *)))) = numClamped;
      iVar2 = numUnclamped;
      *(int **)((kd_frame + (5 * (int)sizeof(void *)))) = piVar7;
      piVar7 = unclamped;
      *(int *)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = iVar2;
      *(int **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))) = piVar7;
      *(MeReal **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))) = b;
      *(keaLCPSolver **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))) = this;
      *(undefined4 *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *)))) = 0x1046b;
      keaLCPSolver__makeXandW
                (*(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))),
                 *(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))),
                 *(void **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))),*(int *)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))),
                 *(void **)((kd_frame + (5 * (int)sizeof(void *)))),*(int *)((kd_frame + (6 * (int)sizeof(void *)))));
      iVar2 = numClamped;
      *(int *)((kd_frame + (7 * (int)sizeof(void *)))) = numUnclamped;
      piVar7 = unclamped;
      *(int *)((kd_frame + (6 * (int)sizeof(void *)))) = iVar2;
      piVar1 = clamped;
      *(int **)((kd_frame + (5 * (int)sizeof(void *)))) = piVar7;
      piVar7 = C;
      *(int **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = piVar1;
      piVar1 = I;
      *(int **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))) = piVar7;
      *(int **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))) = piVar1;
      *(keaLCPSolver **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))) = this;
      *(undefined4 *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *)))) = 0x1048f;
      iVar2 = keaLCPSolver__blockMurtyChooseNewIndices
                        (*(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))),
                         *(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))),
                         *(void **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))),
                         *(void **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))),
                         *(void **)((kd_frame + (5 * (int)sizeof(void *)))),
                         *(int *)((kd_frame + (6 * (int)sizeof(void *)))),
                         *(int *)((kd_frame + (7 * (int)sizeof(void *)))));
      if (iVar2 != 0) {
        *(int *)((kd_iptr)(kd_frame + (8 * (int)sizeof(void *)))) = iVar2;
        *(int *)((kd_frame + (7 * (int)sizeof(void *)))) = iVar2;
        iVar4 = iteration;
        piVar1 = I;
        *(int *)((kd_frame + (6 * (int)sizeof(void *)))) = this->n;
        piVar7 = C;
        *(int *)((kd_frame + (5 * (int)sizeof(void *)))) = iVar4;
        *(uint *)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = (kd_iptr)auStack_3c + (kd_uptr)uVar6 * -3;
        *(uint **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))) = auStack_3c + -(kd_uptr)uVar6;
        *(int **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))) = piVar7;
        *(int **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))) = piVar1;
        *(undefined4 *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *)))) = 0x104e2;
        iVar4 = kd_checkForCycles(*(int **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))),
                               *(int **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))),
                               *(int **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))),
                               *(int **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))),
                               *(int *)((kd_frame + (5 * (int)sizeof(void *)))),
                               *(int *)((kd_frame + (6 * (int)sizeof(void *)))));
        inCycle = iVar4;
        if (iVar4 != 0) {
          *(undefined4 *)((kd_iptr)(kd_frame + (8 * (int)sizeof(void *)))) = extraout_EDX;
          *(undefined4 *)((kd_frame + (7 * (int)sizeof(void *)))) = extraout_EDX;
          piVar7 = C;
          *(uint **)((kd_frame + (6 * (int)sizeof(void *)))) = auStack_3c + -(kd_uptr)uVar6;
          piVar1 = I;
          *(uint *)((kd_frame + (5 * (int)sizeof(void *)))) = (kd_iptr)auStack_3c + (kd_uptr)uVar6 * -3;
          *(int **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))) = piVar7;
          *(int **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))) = piVar1;
          *(int *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))) = iVar4;
          *(keaLCPSolver **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))) = this;
          *(undefined4 *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *)))) = 0x10502;
          inCycle = keaLCPSolver__commonPivot
                              (*(void **)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (1 * (int)sizeof(void *))),
                               *(int *)((kd_iptr)(kd_frame + (0 * (int)sizeof(void *))) + (2 * (int)sizeof(void *))),
                               *(void **)((kd_iptr)(kd_frame + (3 * (int)sizeof(void *)))),
                               *(void **)((kd_iptr)(kd_frame + (4 * (int)sizeof(void *)))),
                               *(void **)((kd_frame + (5 * (int)sizeof(void *)))),
                               *(void **)((kd_frame + (6 * (int)sizeof(void *)))));
        }
      }
      *(undefined4 *)((kd_iptr)(kd_frame + (8 * (int)sizeof(void *)))) = 0x1049d;
      keaPopPoolFrame();
      iteration = iteration + 1;
      if (iteration == max_iterations) {
        return iteration;
      }
      if (inCycle != 0) {
        return iteration;
      }
    }
  }
  return iteration;
}
