/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/keaMakejlenandbl2body.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for keaMakejlenandbl2body.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
void kd_singPartmakejlenandbl2body (int *next_constraint,int *jlen,int (*bl2body) [8],int (*bl2cony) [8], int (*jbody) [2],int *jsize,int num_strips_inc_padding,int num_strips, int num_constraints) KD_MANGLED("_Z26singPartmakejlenandbl2bodyPiS_PA8_iS1_PA2_KiPS2_iii");
void __thiscall kd_keaFunctions__makejlenandbl2body (keaFunctions *this,int *jlen_12padded,int *jlen,int (*bl2body_12padded) [8], int (*bl2body) [8],int (*bl2cbody) [8],int (*Jbody) [2],int *Jsize, int *num_rows_inc_padding_partition,int *num_rows_exc_padding_partition, int *num_constraints_partition,int num_constraints,int num_partitions) KD_MANGLED("_ZN12keaFunctions18makejlenandbl2bodyEPiS0_PA8_iS2_S2_PA2_KiPS3_S6_S6_S6_ii");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- singPartmakejlenandbl2body (exported as kd_singPartmakejlenandbl2body, asm label "int") ---- */
void kd_singPartmakejlenandbl2body
               (int *next_constraint,int *jlen,int (*bl2body) [8],int (*bl2cony) [8],
               int (*jbody) [2],int *jsize,int num_strips_inc_padding,int num_strips,
               int num_constraints)

{
  int iVar1;
  int iVar2;
  int *pbl2conybase;
  int *pbl2bodybase;
  int body1;
  int body0;
  int offs;
  int i;

  offs = 0;
  *jlen = 0;
  body0 = jbody[*next_constraint][0];
  body1 = jbody[*next_constraint][1];
  pbl2bodybase = *bl2body;
  i = 0;
  pbl2conybase = *bl2cony;
  if (num_strips_inc_padding != 0) {
    do {
      *jlen = *jlen + 2;
      (*bl2body)[0] = body0;
      *(int *)((kd_iptr)bl2body + 4) = body1;
      bl2body = (int (*) [8])((kd_iptr)bl2body + 8);
      (*bl2cony)[0] = *next_constraint * 2;
      *(int *)((kd_iptr)bl2cony + 4) = *next_constraint * 2 + 1;
      bl2cony = (int (*) [8])((kd_iptr)bl2cony + 8);
      iVar1 = *next_constraint;
      iVar2 = offs + jsize[iVar1];
      if (iVar2 < 5) {
        if (iVar2 == 4) {
          jlen = jlen + 1;
          offs = 0;
          *jlen = 0;
          bl2cony = (int (*) [8])(pbl2conybase + 8);
          bl2body = (int (*) [8])(pbl2bodybase + 8);
          pbl2conybase = (int *)bl2cony;
          pbl2bodybase = (int *)bl2body;
          if (*next_constraint < num_constraints + -1) {
            iVar1 = *next_constraint + 1;
            *next_constraint = iVar1;
            body0 = jbody[iVar1][0];
            body1 = jbody[iVar1][1];
          }
        }
        else {
          offs = iVar2;
          if (iVar1 < num_constraints + -1) {
            iVar1 = iVar1 + 1;
            *next_constraint = iVar1;
            body0 = jbody[iVar1][0];
            body1 = jbody[iVar1][1];
          }
        }
      }
      else {
        jlen = jlen + 1;
        *jlen = 0;
        bl2body = (int (*) [8])(pbl2bodybase + 8);
        bl2cony = (int (*) [8])(pbl2conybase + 8);
        pbl2conybase = (int *)bl2cony;
        pbl2bodybase = (int *)bl2body;
        offs = offs + -4;
      }
      i = i + 1;
    } while (i != num_strips_inc_padding);
  }
  return;
}

/* ---- makejlenandbl2body (exported as kd_keaFunctions__makejlenandbl2body, asm label "int") ---- */
void __thiscall
kd_keaFunctions__makejlenandbl2body
          (keaFunctions *this,int *jlen_12padded,int *jlen,int (*bl2body_12padded) [8],
          int (*bl2body) [8],int (*bl2cbody) [8],int (*Jbody) [2],int *Jsize,
          int *num_rows_inc_padding_partition,int *num_rows_exc_padding_partition,
          int *num_constraints_partition,int num_constraints,int num_partitions)

{
  uint uVar1;
  int num_strips_00;
  int iVar2;
  int iVar3;
  uint uVar4;
  uint uVar5;
  int (*paiVar6) [8];
  int iVar7;
  int iVar8;
  int num_rows;
  int ceil3_num_strips;
  int num_strips_inc_padding;
  int num_strips;
  int partition;
  int constraint;

  partition = 0;
  constraint = 0;
  if (num_partitions != 0) {
    do {
      if (0 < num_constraints_partition[partition]) {
        uVar5 = num_rows_exc_padding_partition[partition];
        if ((uVar5 & 3) == 0) {
          uVar1 = uVar5;
          if ((int)uVar5 < 0) {
            uVar1 = uVar5 + 3;
          }
        }
        else {
          uVar4 = uVar5;
          if ((int)uVar5 < 0) {
            uVar4 = uVar5 + 3;
          }
          uVar1 = (uVar4 & 0xfffffffc) + 4;
          if ((int)uVar1 < 0) {
            uVar1 = (uVar4 & 0xfffffffc) + 7;
          }
        }
        num_strips_00 = (int)uVar1 >> 2;
        iVar3 = num_rows_inc_padding_partition[partition];
        if (iVar3 < 0) {
          iVar3 = iVar3 + 3;
        }
        if ((int)uVar5 % 0xc == 0) {
          if ((int)uVar5 < 0) {
            uVar5 = uVar5 + 3;
          }
        }
        else {
          iVar2 = uVar5 - (int)uVar5 % 0xc;
          uVar5 = iVar2 + 0xc;
          if ((int)uVar5 < 0) {
            uVar5 = iVar2 + 0xf;
          }
        }
        iVar2 = (int)uVar5 >> 2;
        iVar7 = 0;
        if (iVar2 != 0) {
          do {
            paiVar6 = bl2body_12padded + iVar7;
            jlen_12padded[iVar7] = 0;
            iVar7 = iVar7 + 1;
            (*paiVar6)[0] = -3;
            (*paiVar6)[1] = -3;
            (*paiVar6)[2] = -3;
            (*paiVar6)[3] = -3;
            (*paiVar6)[4] = -3;
            (*paiVar6)[5] = -3;
            (*paiVar6)[6] = -3;
            (*paiVar6)[7] = -3;
          } while (iVar7 != iVar2);
        }
        if (num_strips_00 != 0) {
          iVar7 = 0;
          do {
            jlen[iVar7] = 0;
            iVar8 = iVar7 + 1;
            bl2body[iVar7][0] = -3;
            bl2cbody[iVar7][0] = -1;
            bl2body[iVar7][1] = -3;
            bl2cbody[iVar7][1] = -1;
            bl2body[iVar7][2] = -3;
            bl2cbody[iVar7][2] = -1;
            bl2body[iVar7][3] = -3;
            bl2cbody[iVar7][3] = -1;
            bl2body[iVar7][4] = -3;
            bl2cbody[iVar7][4] = -1;
            bl2body[iVar7][5] = -3;
            bl2cbody[iVar7][5] = -1;
            bl2body[iVar7][6] = -3;
            bl2cbody[iVar7][6] = -1;
            bl2body[iVar7][7] = -3;
            bl2cbody[iVar7][7] = -1;
            iVar7 = iVar8;
          } while (iVar8 != num_strips_00);
        }
        kd_singPartmakejlenandbl2body
                  (&constraint,jlen,bl2body,bl2cbody,Jbody,Jsize,iVar3 >> 2,num_strips_00,
                   num_constraints);
        iVar3 = 0;
        if (num_strips_00 != 0) {
          do {
            jlen_12padded[iVar3] = jlen[iVar3];
            iVar7 = iVar3 + 1;
            bl2body_12padded[iVar3][0] = bl2body[iVar3][0];
            bl2body_12padded[iVar3][1] = bl2body[iVar3][1];
            bl2body_12padded[iVar3][2] = bl2body[iVar3][2];
            bl2body_12padded[iVar3][3] = bl2body[iVar3][3];
            bl2body_12padded[iVar3][4] = bl2body[iVar3][4];
            bl2body_12padded[iVar3][5] = bl2body[iVar3][5];
            bl2body_12padded[iVar3][6] = bl2body[iVar3][6];
            bl2body_12padded[iVar3][7] = bl2body[iVar3][7];
            iVar3 = iVar7;
          } while (iVar7 != num_strips_00);
        }
        jlen_12padded = jlen_12padded + iVar2;
        bl2body_12padded = bl2body_12padded + iVar2;
        jlen = jlen + num_strips_00;
        bl2cbody = bl2cbody + num_strips_00;
        bl2body = bl2body + num_strips_00;
      }
      partition = partition + 1;
    } while (partition != num_partitions);
  }
  return;
}
