/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/McdInteractions.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for McdInteractions.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
MeBool kd_McdNearby(McdModelPair *p) KD_MANGLED("McdNearby");
void kd_McdHello(McdModelPair *p) KD_MANGLED("McdHello");
void kd_McdGoodbye(McdModelPair *p) KD_MANGLED("McdGoodbye");
MeBool kd_McdIntersect(McdModelPair *p,McdIntersectResult *result) KD_MANGLED("McdIntersect");
MeBool kd_McdIntersectAt(McdModelPair *p,McdIntersectResult *result,MeReal time) KD_MANGLED("McdIntersectAt");
MeBool kd_McdSafeTime(McdModelPair *p,MeReal maxTime,McdSafeTimeResult *result) KD_MANGLED("McdSafeTime");
uint kd_McdLineSegIntersect(McdModelID cm,MeReal *inOrig,MeReal *inDest, McdLineSegIntersectResult *outOverlap) KD_MANGLED("McdLineSegIntersect");
void kd_McdSetHelloCallback(McdFramework *frame,McdHelloCallbackFnPtr f) KD_MANGLED("_Z19McdSetHelloCallbackP13_McdFrameworkPFvP13_McdModelPairE");
McdHelloCallbackFnPtr kd_McdGetHelloCallback(McdFramework *frame) KD_MANGLED("_Z19McdGetHelloCallbackP13_McdFramework");
void kd_McdHelloEach(McdModelPairContainer *pairs) KD_MANGLED("McdHelloEach");
void kd_McdGoodbyeEach(McdModelPairContainer *pairs) KD_MANGLED("McdGoodbyeEach");
MeBool kd_McdIntersectEach(McdModelPairContainer *pairs,McdModelPairContainerIterator *pairsIter, McdIntersectResult *resultArray,int resultArraySize,int *resultCount, McdContact *contactArray,int contactArraySize,int *contactCount) KD_MANGLED("McdIntersectEach");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- McdNearby (exported as kd_McdNearby, asm label "McdNearby") ---- */
MeBool kd_McdNearby(McdModelPair *p)

{
  uint uVar1;
  uint uVar2;
  MeReal maxCorner2 [3];
  MeReal minCorner2 [3];
  MeReal maxCorner1 [3];
  MeReal minCorner1 [3];

  McdModelGetAABB(p->model1,minCorner1,maxCorner1);
  McdModelGetAABB(p->model2,minCorner2,maxCorner2);
  if (minCorner2[0] <= maxCorner1[0]) {
    uVar1 = (maxCorner2[0] < minCorner1[0]) - 1 & 1;
  }
  else {
    uVar1 = 0;
  }
  uVar2 = 0;
  if (uVar1 != 0) {
    if (minCorner2[1] <= maxCorner1[1]) {
      uVar1 = uVar1 & (maxCorner2[1] < minCorner1[1]) - 1;
    }
    else {
      uVar1 = 0;
    }
    uVar2 = 0;
    if (uVar1 != 0) {
      if (minCorner2[2] <= maxCorner1[2]) {
        uVar2 = uVar1 & (maxCorner2[2] < minCorner1[2]) - 1;
      }
      else {
        uVar2 = 0;
      }
    }
  }
  return uVar2;
}

/* ---- McdHello (exported as kd_McdHello, asm label "McdHello") ---- */
void kd_McdHello(McdModelPair *p)

{
  McdModelID pMVar1;
  McdFramework *pMVar2;
  McdHelloCallbackFnPtr p_Var3;
  undefined4 *puVar4;
  McdRequest *pMVar5;

  pMVar1 = p->model1;
  pMVar2 = pMVar1->frame;
  puVar4 = McdFrameworkGetInteractions
                     (pMVar1->frame,(uint)(byte)((pMVar1->mInstance).mGeometry)->mRefCtAndID,
                      (uint)(byte)((p->model2->mInstance).mGeometry)->mRefCtAndID);
  if (*(undefined4 *)((kd_iptr)puVar4 + ((int)((char *)&((struct _McdInteractions *)0)->swap - (char *)0))) != 0) {
                    
    pMVar1 = p->model1;
    p->model1 = p->model2;
    p->model2 = pMVar1;
  }
  pMVar5 = McdFrameworkGetDefaultRequestPtr(pMVar2);
  p->request = pMVar5;
  p_Var3 = pMVar2->mHelloCallbackFnPtr;
  if (p_Var3 != (McdHelloCallbackFnPtr)0x0) {
    (*p_Var3)(p);
  }
  if ((code *)*(kd_uptr *)puVar4 != (code *)0x0) {
    (**(MeBool (**)(McdModelPair *))(puVar4))(p);
  }
  return;
}

/* ---- McdGoodbye (exported as kd_McdGoodbye, asm label "McdGoodbye") ---- */
void kd_McdGoodbye(McdModelPair *p)

{
  short sVar1;
  int iVar2;
  void *pvVar3;

  sVar1 = McdModelGetGeometryType(p->model2);
  iVar2 = (int)sVar1;
  sVar1 = McdModelGetGeometryType(p->model1);
  pvVar3 = McdFrameworkGetInteractions(p->model1->frame,(int)sVar1,iVar2);
  if (*(code **)((kd_iptr)pvVar3 + ((int)((char *)&((struct _McdInteractions *)0)->goodbyeFn - (char *)0))) != (code *)0x0) {
    (**(void (**)(McdModelPair *))((kd_iptr)pvVar3 + ((int)((char *)&((struct _McdInteractions *)0)->goodbyeFn - (char *)0))))(p);
  }
  return;
}

/* ---- McdIntersect (exported as kd_McdIntersect, asm label "McdIntersect") ---- */
MeBool kd_McdIntersect(McdModelPair *p,McdIntersectResult *result)

{
  code *pcVar1;
  McdRequest *pMVar2;
  short sVar3;
  void *pvVar4;
  void *pvVar5;
  McdContact *pMVar6;
  undefined1 kd_argarea_pMVar6 [36 * (int)(sizeof(void *) / 4)];
  int iVar7;
  McdContact aMStackY_501c [511];
  undefined4 uStackY_40;
  int type1;
  McdFramework *frame;
  McdContact *outContacts;

  frame = p->model1->frame;
  sVar3 = McdModelGetGeometryType(p->model1);
  type1 = (int)sVar3;
  sVar3 = McdModelGetGeometryType(p->model2);
  result->pair = p;
  iVar7 = (int)sVar3;
  pvVar4 = McdFrameworkGetInteractions(frame,type1,iVar7);
  pvVar5 = pvVar4;
  if ((*(kd_iptr *)((kd_iptr)pvVar4 + ((int)((char *)&((struct _McdInteractions *)0)->intersectFn - (char *)0))) == 0) &&
     (pvVar5 = (void *)McdFrameworkGetInteractionsWarned(frame,type1,iVar7), pvVar5 == (void *)0x0))
  {
    McdFrameworkGetTypeName(frame,iVar7);
    McdFrameworkGetTypeName(frame,type1);
    MeWarning(1,"No test registered between %s and %s");
    uStackY_40 = 0x102e8;
    McdFrameworkSetInteractionsWarned(frame,type1,iVar7,1);
    result->touch = 0;
    result->contactCount = 0;
    return 0;
  }
  pMVar6 = (McdContact *)(kd_argarea_pMVar6 + (9 * (int)sizeof(void *)));
  if (*(int *)((kd_iptr)pvVar4 + ((int)((char *)&((struct _McdInteractions *)0)->cull - (char *)0))) != 0) {
    outContacts = result->contacts;
    pMVar6 = (McdContact *)(kd_argarea_pMVar6 + (9 * (int)sizeof(void *)));
    result->contacts = aMStackY_501c;
  }
  *(void **)((kd_iptr)pMVar6 + (-1 * (int)sizeof(void *))) = pvVar5;
  *(void **)((kd_iptr)pMVar6 + (-2 * (int)sizeof(void *))) = pvVar5;
  *(McdIntersectResult **)((kd_iptr)pMVar6 + (-3 * (int)sizeof(void *))) = result;
  *(McdModelPair **)((kd_iptr)pMVar6 + (-4 * (int)sizeof(void *))) = p;
  pcVar1 = *(code **)((kd_iptr)pvVar4 + ((int)((char *)&((struct _McdInteractions *)0)->intersectFn - (char *)0)));
  *(undefined4 *)((kd_iptr)pMVar6 + (-5 * (int)sizeof(void *))) = 0x10232;
  iVar7 = (*(McdIntersectFn)pcVar1)(*(McdModelPair **)((kd_iptr)pMVar6 + (-4 * (int)sizeof(void *))),
                 *(McdIntersectResult **)((kd_iptr)pMVar6 + (-3 * (int)sizeof(void *))));
  result->touch = iVar7;
  if (*(int *)((kd_iptr)pvVar4 + ((int)((char *)&((struct _McdInteractions *)0)->cull - (char *)0))) != 0) {
    *(McdModelPair **)((kd_iptr)pMVar6 + (-1 * (int)sizeof(void *))) = p;
    *(MeReal *)((kd_iptr)pMVar6 + (-2 * (int)sizeof(void *))) = frame->mScale;
    pMVar2 = p->request;
    *(int *)((kd_iptr)pMVar6 + (-3 * (int)sizeof(void *))) = pMVar2->faceNormalsFirst;
    *(int *)((kd_iptr)pMVar6 + (-4 * (int)sizeof(void *))) = pMVar2->contactMaxCount;
    *(McdContact **)((kd_iptr)pMVar6 + (-5 * (int)sizeof(void *))) = outContacts;
    *(int *)((kd_iptr)pMVar6 + (-6 * (int)sizeof(void *))) = result->contactCount;
    *(McdContact **)((kd_iptr)pMVar6 + (-7 * (int)sizeof(void *))) = result->contacts;
    *(MeReal **)((kd_iptr)pMVar6 + (-8 * (int)sizeof(void *))) = result->normal;
    *(undefined4 *)((kd_iptr)pMVar6 + (-9 * (int)sizeof(void *))) = 0x1027d;
    iVar7 = McdContactSimplify(*(void **)((kd_iptr)pMVar6 + (-8 * (int)sizeof(void *))),*(void **)((kd_iptr)pMVar6 + (-7 * (int)sizeof(void *))),
                               *(int *)((kd_iptr)pMVar6 + (-6 * (int)sizeof(void *))),*(void **)((kd_iptr)pMVar6 + (-5 * (int)sizeof(void *))),
                               *(int *)((kd_iptr)pMVar6 + (-4 * (int)sizeof(void *))),*(int *)((kd_iptr)pMVar6 + (-3 * (int)sizeof(void *))),
                               *(float *)((kd_iptr)pMVar6 + (-2 * (int)sizeof(void *))));
    result->contactCount = iVar7;
    result->contacts = outContacts;
  }
  return 1;
}

/* ---- McdIntersectAt (exported as kd_McdIntersectAt, asm label "McdIntersectAt") ---- */
MeBool kd_McdIntersectAt(McdModelPair *p,McdIntersectResult *result,MeReal time)

{
  McdModelID pMVar1;
  McdModelID pMVar2;
  void *pvVar3;
  void *pvVar4;
  MeBool MVar5;
  MeMatrix4Ptr tm2save;
  MeMatrix4Ptr tm1save;
  MeReal tm2 [4] [4];
  MeReal tm1 [4] [4];

  pMVar1 = p->model1;
  pMVar2 = p->model2;
  pvVar3 = McdModelGetTransformPtr(pMVar1);
  pvVar4 = McdModelGetTransformPtr(pMVar2);
  MeMatrix4TMUpdateFromVelocities
            (tm1,0.0001,time,pMVar1->linearVelocity,pMVar1->angularVelocity,pvVar3);
  MeMatrix4TMUpdateFromVelocities
            (tm2,0.0001,time,pMVar2->linearVelocity,pMVar2->angularVelocity,pvVar4);
  McdModelSetTransformPtr(pMVar1,tm1);
  McdModelSetTransformPtr(pMVar2,tm2);
  MVar5 = kd_McdIntersect(p,result);
  McdModelSetTransformPtr(pMVar1,pvVar3);
  McdModelSetTransformPtr(pMVar2,pvVar4);
  return MVar5;
}

/* ---- McdSafeTime (exported as kd_McdSafeTime, asm label "McdSafeTime") ---- */
MeBool kd_McdSafeTime(McdModelPair *p,MeReal maxTime,McdSafeTimeResult *result)

{
  MeReal *pMVar1;
  void *pvVar2;

  pvVar2 = McdFrameworkGetInteractions
                     (p->model1->frame,(uint)(byte)((p->model1->mInstance).mGeometry)->mRefCtAndID,
                      (uint)(byte)((p->model2->mInstance).mGeometry)->mRefCtAndID);
  if ((((*(code **)((kd_iptr)pvVar2 + ((int)((char *)&((struct _McdInteractions *)0)->safetimeFn - (char *)0))) == (code *)0x0) ||
       (p->model1->linearVelocity == (MeReal *)0x0)) || (p->model2->linearVelocity == (MeReal *)0x0)
      ) || ((p->model1->angularVelocity == (MeReal *)0x0 ||
            (pMVar1 = p->model2->angularVelocity, pMVar1 == (MeReal *)0x0)))) {
    result->time = maxTime;
  }
  else {
    (**(int (**)(McdModelPair *, MeReal, McdSafeTimeResult *))((kd_iptr)pvVar2 + ((int)((char *)&((struct _McdInteractions *)0)->safetimeFn - (char *)0))))(p,maxTime,result);
  }
  return (uint)(*(kd_iptr *)((kd_iptr)pvVar2 + ((int)((char *)&((struct _McdInteractions *)0)->safetimeFn - (char *)0))) != 0);
}

/* ---- McdLineSegIntersect (exported as kd_McdLineSegIntersect, asm label "McdLineSegIntersect") ---- */
uint kd_McdLineSegIntersect(McdModelID cm,MeReal *inOrig,MeReal *inDest,
                        McdLineSegIntersectResult *outOverlap)

{
  void *pvVar1;
  code *pcVar2;
  int iVar3;
  uint uVar4;

  uVar4 = 0;
  outOverlap->model = cm;
  pvVar1 = McdModelGetGeometry(cm);
  pcVar2 = McdGeometryGetLineSegIntersectFnPtr(pvVar1);
  if (pcVar2 != (code *)0x0) {
    iVar3 = (*pcVar2)(cm,inOrig,inDest,outOverlap);
    if (iVar3 != 0) {
      uVar4 = 1;
    }
  }
  return uVar4;
}

/* ---- McdSetHelloCallback (exported as kd_McdSetHelloCallback, asm label "kd_McdSetHelloCallback") ---- */
void kd_McdSetHelloCallback(McdFramework *frame,McdHelloCallbackFnPtr f)

{
  frame->mHelloCallbackFnPtr = f;
  return;
}

/* ---- McdGetHelloCallback (exported as kd_McdGetHelloCallback, asm label "kd_McdGetHelloCallback") ---- */
McdHelloCallbackFnPtr kd_McdGetHelloCallback(McdFramework *frame)

{
  return frame->mHelloCallbackFnPtr;
}

/* ---- McdHelloEach (exported as kd_McdHelloEach, asm label "McdHelloEach") ---- */
void kd_McdHelloEach(McdModelPairContainer *pairs)

{
  McdModelPair **ppMVar1;
  int iVar2;

  iVar2 = pairs->helloFirst;
  if (iVar2 < pairs->helloEndStayingFirst) {
    do {
      ppMVar1 = pairs->array + iVar2;
      iVar2 = iVar2 + 1;
      kd_McdHello(*ppMVar1);
    } while (iVar2 < pairs->helloEndStayingFirst);
  }
  return;
}

/* ---- McdGoodbyeEach (exported as kd_McdGoodbyeEach, asm label "McdGoodbyeEach") ---- */
void kd_McdGoodbyeEach(McdModelPairContainer *pairs)

{
  McdModelPair *pMVar1;
  short sVar2;
  int iVar3;
  void *pvVar4;
  int iVar5;

  iVar5 = 0;
  if (0 < pairs->goodbyeEnd) {
    do {
                    
      pMVar1 = pairs->array[iVar5];
      sVar2 = McdModelGetGeometryType(pMVar1->model2);
      iVar3 = (int)sVar2;
      sVar2 = McdModelGetGeometryType(pMVar1->model1);
      pvVar4 = McdFrameworkGetInteractions(pMVar1->model1->frame,(int)sVar2,iVar3);
      if (*(code **)((kd_iptr)pvVar4 + ((int)((char *)&((struct _McdInteractions *)0)->goodbyeFn - (char *)0))) != (code *)0x0) {
        (**(void (**)(McdModelPair *))((kd_iptr)pvVar4 + ((int)((char *)&((struct _McdInteractions *)0)->goodbyeFn - (char *)0))))(pMVar1);
      }
      iVar5 = iVar5 + 1;
    } while (iVar5 < pairs->goodbyeEnd);
  }
  return;
}

/* ---- McdIntersectEach (exported as kd_McdIntersectEach, asm label "McdIntersectEach") ---- */
MeBool kd_McdIntersectEach(McdModelPairContainer *pairs,McdModelPairContainerIterator *pairsIter,
                       McdIntersectResult *resultArray,int resultArraySize,int *resultCount,
                       McdContact *contactArray,int contactArraySize,int *contactCount)

{
  McdModelPair *p;
  int iVar1;
  int iVar2;
  int freeContactCount;
  MeBool overflow;
  int resultIndex;

  iVar2 = 0;
  resultIndex = 0;
  overflow = 0;
  iVar1 = pairsIter->count;
  if (iVar1 < pairs->stayingEnd) {
    do {
      p = pairs->array[iVar1];
      if ((contactArraySize - iVar2 < p->request->contactMaxCount) ||
         (resultArraySize <= resultIndex)) {
        overflow = 1;
        break;
      }
      iVar1 = iVar1 + 1;
      resultArray->contacts = contactArray + iVar2;
      resultArray->contactMaxCount = contactArraySize - iVar2;
      kd_McdIntersect(p,resultArray);
      resultIndex = resultIndex + 1;
      iVar2 = iVar2 + resultArray->contactCount;
      resultArray = resultArray + 1;
    } while (iVar1 < pairs->stayingEnd);
  }
  pairsIter->count = iVar1;
  *resultCount = resultIndex;
  *contactCount = iVar2;
  return overflow;
}
