/* Generated by decomp/tools/ghidra_clean.py — do not edit by hand.
 * source object: lab/allobj/McdModel.o
 */
#include "kd_compat.h"
#include "kd_karma.h"
#include "kd_types.h"
#include <stdbool.h>
#include <stdarg.h>

/* ---- hand-written prelude ---- */
/*  Prelude for McdModel.o — generated by tools/gen_prelude.py.
 *
 *  Values below were READ from the object, not inferred. Anything the tool
 *  could not determine is marked TODO and needs a human.
 */

/* ---- forward declarations ---- */
McdModelID kd_McdModelCreate(McdGeometryID g) KD_MANGLED("McdModelCreate");
void kd_McdModelDestroy(McdModelID cm) KD_MANGLED("McdModelDestroy");
void kd_McdModelReset(McdModelID obj) KD_MANGLED("McdModelReset");
McdGeometryType kd_McdModelGetGeometryType(McdModelID cm) KD_MANGLED("McdModelGetGeometryType");
McdSpaceID kd_McdModelGetSpace(McdModelID cm) KD_MANGLED("McdModelGetSpace");
void kd_McdModelSetContactTolerance(McdModelID m,MeReal tol) KD_MANGLED("McdModelSetContactTolerance");
MeReal kd_McdModelGetContactTolerance(McdModelID m) KD_MANGLED("McdModelGetContactTolerance");
void kd_McdModelGetBSphere(McdModelID m,MeReal *center,MeReal *radius) KD_MANGLED("McdModelGetBSphere");
void kd_McdModelUpdate(McdModelID cm) KD_MANGLED("McdModelUpdate");
void kd_McdModelUpdatePath(McdModelID cm,MeReal motionDuration) KD_MANGLED("McdModelUpdatePath");
void kd_McdModelUpdatePathCompatible(McdModelID cm,MeReal param_2) KD_MANGLED("McdModelUpdatePathCompatible");
void kd_McdModelGetAABB(McdModelID cm,MeReal *minCorner,MeReal *maxCorner) KD_MANGLED("McdModelGetAABB");
McdGeometryInstanceID kd_McdModelGetGeometryInstance(McdModelID cm) KD_MANGLED("McdModelGetGeometryInstance");
MeMatrix4Ptr kd_McdModelGetTransformPtr(McdModelID cm) KD_MANGLED("McdModelGetTransformPtr");
void kd_McdModelSetTransformPtr(McdModelID cm,MeMatrix4Ptr geometryTM) KD_MANGLED("McdModelSetTransformPtr");
void kd_McdModelSetLinearVelocityPtr(McdModelID cm,MeReal *linVelocity) KD_MANGLED("McdModelSetLinearVelocityPtr");
MeReal * kd_McdModelGetLinearVelocityPtr(McdModelID cm) KD_MANGLED("McdModelGetLinearVelocityPtr");
void kd_McdModelSetAngularVelocityPtr(McdModelID cm,MeReal *angVelocity) KD_MANGLED("McdModelSetAngularVelocityPtr");
MeReal * kd_McdModelGetAngularVelocityPtr(McdModelID cm) KD_MANGLED("McdModelGetAngularVelocityPtr");
void kd_McdModelSetUserData(McdModelID cm,void *data) KD_MANGLED("McdModelSetUserData");
void * kd_McdModelGetUserData(McdModelID cm) KD_MANGLED("McdModelGetUserData");
void kd_McdModelSetGeometry(McdModelID cm,McdGeometryID g) KD_MANGLED("McdModelSetGeometry");
McdGeometryID kd_McdModelGetGeometry(McdModelID cm) KD_MANGLED("McdModelGetGeometry");
void * kd_McdModelGetBodyData(McdModelID cm) KD_MANGLED("McdModelGetBodyData");
void kd_McdModelSetBodyData(McdModelID cm,void *body) KD_MANGLED("McdModelSetBodyData");
void kd_McdModelSetRelativeTransformPtrs (McdModelID cm,MeVector4 *relativeTM,MeVector4 *referenceTM, MeVector4 *compoundTM,MeBool own) KD_MANGLED("McdModelSetRelativeTransformPtrs");
void kd_McdModelGetRelativeTransformPtrs (McdModelID cm,MeMatrix4Ptr *relativeTM,MeMatrix4Ptr *referenceTM) KD_MANGLED("McdModelGetRelativeTransformPtrs");
void kd_McdModelSetRelativeTransform(McdModelID cm,MeMatrix4Ptr relTM,MeMatrix4Ptr refTM) KD_MANGLED("_Z28McdModelSetRelativeTransformP9_McdModelPA4_fS2_");
MeMatrix4Ptr kd_McdModelGetRelativeTransform(McdModelID cm) KD_MANGLED("McdModelGetRelativeTransform");
void kd_McdModelCompoundTransforms(McdModelID cm) KD_MANGLED("McdModelCompoundTransforms");
void kd_McdModelSetMaterial(McdModelID cm,int material) KD_MANGLED("McdModelSetMaterial");
uint kd_McdModelGetMaterial(McdModelID cm) KD_MANGLED("McdModelGetMaterial");
void kd_McdModelSetRequestID(McdModelID cm,int requestId) KD_MANGLED("McdModelSetRequestID");
int kd_McdModelGetRequestID(McdModelID cm) KD_MANGLED("McdModelGetRequestID");
void kd_McdModelSetUpdateCallback(McdModelID cm,McdModelUpdateFnPtr f) KD_MANGLED("McdModelSetUpdateCallback");
McdModelUpdateFnPtr kd_McdModelGetUpdateCallback(McdModelID cm) KD_MANGLED("McdModelGetUpdateCallback");
void kd_McdModelSetIntersectCallback(McdModelID cm,McdModelIntersectFnPtr fn) KD_MANGLED("McdModelSetIntersectCallback");
McdModelIntersectFnPtr kd_McdModelGetIntersectCallback(McdModelID cm) KD_MANGLED("McdModelGetIntersectCallback");
MeI16 kd_McdModelGetSortKey(McdModelID cm) KD_MANGLED("McdModelGetSortKey");
void kd_McdModelSetSortKey(McdModelID cm,MeI16 key) KD_MANGLED("McdModelSetSortKey");

/* ---- C++ ABI data (needs the declarations above) ---- */
/* no C++ ABI data in this object */

/* ---- exported data symbols (need the declarations above) ---- */


/* ---- McdModelCreate (exported as kd_McdModelCreate, asm label "McdModelCreate") ---- */
McdModelID kd_McdModelCreate(McdGeometryID g)

{
  McdModelID pMVar1;
  McdFramework *pMVar2;
  McdModelID pMVar3;

  pMVar2 = McdGeometryGetFramework(g);
  pMVar3 = (MePoolAPI.getStruct)(&pMVar2->modelPool);
  if (pMVar3 != (McdModelID)0x0) {
    pMVar2->modelCount = pMVar2->modelCount + 1;
    pMVar3->mRelTM = (MeMatrix4Ptr)0x0;
    pMVar3->mRefTM = (MeMatrix4Ptr)0x0;
    pMVar3->mBody = (void *)0x0;
    pMVar3->mRequestID = 0;
    pMVar3->mSpace = (McdSpaceID)0x0;
    pMVar3->mSpaceID = -1;
    pMVar3->mData = (void *)0x0;
    pMVar3->linearVelocity = (MeReal *)0x0;
    pMVar3->angularVelocity = (MeReal *)0x0;
    pMVar3->mTransformUpdateFn = (McdModelUpdateFnPtr)0x0;
    pMVar3->sortKey = 0;
    pMVar3->mIntersectFn = (McdModelIntersectFnPtr)0x0;
    pMVar3->flags = 0;
    McdGeometryInstanceReset(&pMVar3->mInstance);
    pMVar3->mPadding = pMVar2->mDefaultPadding;
    pMVar3->frame = pMVar2;
    McdGeometryInstanceSetGeometry(&pMVar3->mInstance,g);
    if (pMVar2->firstModel == (McdModelID)0x0) {
      pMVar3->prev = pMVar3;
      pMVar3->next = pMVar3;
    }
    else {
      pMVar1 = pMVar2->firstModel->prev;
      pMVar3->prev = pMVar1;
      pMVar3->next = pMVar2->firstModel;
      pMVar1->next = pMVar3;
      pMVar3->next->prev = pMVar3;
    }
    pMVar2->firstModel = pMVar3;
  }
  return pMVar3;
}

/* ---- McdModelDestroy (exported as kd_McdModelDestroy, asm label "McdModelDestroy") ---- */
void kd_McdModelDestroy(McdModelID cm)

{
  McdFramework *pMVar1;
  McdModelID pMVar2;
  void *pvVar3;
  McdFramework *pMVar4;

  if ((cm->flags & 1U) != 0) {
    (MeMemoryAPI.destroyAligned)(cm->mRelTM);
    pvVar3 = McdGeometryInstanceGetTransformPtr(&cm->mInstance);
    (MeMemoryAPI.destroyAligned)(pvVar3);
    cm->flags = cm->flags & 0xfffffffe;
  }
  McdGeometryInstanceSetGeometry(&cm->mInstance,(void *)0x0);
  pMVar1 = cm->frame;
  pMVar4 = pMVar1;
  if (pMVar1->firstModel == cm) {
    pMVar1->firstModel = (McdModelID)((kd_uptr)cm->next & (cm->next == cm) - 1);
    pMVar4 = cm->frame;
  }
  pMVar2 = cm->next;
  pMVar2->prev = cm->prev;
  cm->prev->next = pMVar2;
  (MePoolAPI.putStruct)(&pMVar4->modelPool,cm);
  pMVar1->modelCount = pMVar1->modelCount + -1;
  return;
}

/* ---- McdModelReset (exported as kd_McdModelReset, asm label "McdModelReset") ---- */
void kd_McdModelReset(McdModelID obj)

{
  obj->mRelTM = (MeMatrix4Ptr)0x0;
  obj->mRefTM = (MeMatrix4Ptr)0x0;
  obj->mBody = (void *)0x0;
  obj->mRequestID = 0;
  obj->mSpace = (McdSpaceID)0x0;
  obj->mSpaceID = -1;
  obj->mData = (void *)0x0;
  obj->linearVelocity = (MeReal *)0x0;
  obj->angularVelocity = (MeReal *)0x0;
  obj->mTransformUpdateFn = (McdModelUpdateFnPtr)0x0;
  obj->sortKey = 0;
  obj->mIntersectFn = (McdModelIntersectFnPtr)0x0;
  obj->flags = 0;
  McdGeometryInstanceReset(&obj->mInstance);
  return;
}

/* ---- McdModelGetGeometryType (exported as kd_McdModelGetGeometryType, asm label "McdModelGetGeometryType") ---- */
McdGeometryType kd_McdModelGetGeometryType(McdModelID cm)

{
  return (McdGeometryType)(byte)((cm->mInstance).mGeometry)->mRefCtAndID;
}

/* ---- McdModelGetSpace (exported as kd_McdModelGetSpace, asm label "McdModelGetSpace") ---- */
McdSpaceID kd_McdModelGetSpace(McdModelID cm)

{
  return cm->mSpace;
}

/* ---- McdModelSetContactTolerance (exported as kd_McdModelSetContactTolerance, asm label "McdModelSetContactTolerance") ---- */
void kd_McdModelSetContactTolerance(McdModelID m,MeReal tol)

{
  m->mPadding = tol;
  return;
}

/* ---- McdModelGetContactTolerance (exported as kd_McdModelGetContactTolerance, asm label "McdModelGetContactTolerance") ---- */
MeReal kd_McdModelGetContactTolerance(McdModelID m)

{
  return m->mPadding;
}

/* ---- McdModelGetBSphere (exported as kd_McdModelGetBSphere, asm label "McdModelGetBSphere") ---- */
void kd_McdModelGetBSphere(McdModelID m,MeReal *center,MeReal *radius)

{
  McdGeometryInstanceGetBSphere(&m->mInstance,center,radius);
  return;
}

/* ---- McdModelUpdate (exported as kd_McdModelUpdate, asm label "McdModelUpdate") ---- */
void kd_McdModelUpdate(McdModelID cm)

{
  float fVar1;
  float fVar2;
  
  if (cm->mTransformUpdateFn != (McdModelUpdateFnPtr)0x0) {
    (*cm->mTransformUpdateFn)(cm);
  }
  if (cm->mRelTM != (MeMatrix4Ptr)0x0) {
    MeMatrix4TMCompound((cm->mInstance).mTM,cm->mRelTM,cm->mRefTM);
  }
  McdGeometryInstanceUpdateAABB(&cm->mInstance,(void *)0x0,0);
  fVar1 = cm->mPadding;
  (cm->mInstance).min[0] = (cm->mInstance).min[0] - fVar1;
  (cm->mInstance).min[1] = (cm->mInstance).min[1] - fVar1;
  (cm->mInstance).min[2] = (cm->mInstance).min[2] - fVar1;
  (cm->mInstance).max[0] = (cm->mInstance).max[0] + fVar1;
  fVar2 = (cm->mInstance).max[2];
  (cm->mInstance).max[1] = (cm->mInstance).max[1] + fVar1;
  (cm->mInstance).max[2] = fVar1 + fVar2;
  return;
}

/* ---- McdModelUpdatePath (exported as kd_McdModelUpdatePath, asm label "McdModelUpdatePath") ---- */
void kd_McdModelUpdatePath(McdModelID cm,MeReal motionDuration)

{
  MeReal (*paMVar1) [4];
  MeReal tmEnd [4] [4];

  if (cm->mTransformUpdateFn != (McdModelUpdateFnPtr)0x0) {
    (*cm->mTransformUpdateFn)(cm);
  }
  if (cm->mRelTM != (MeMatrix4Ptr)0x0) {
    MeMatrix4TMCompound((cm->mInstance).mTM,cm->mRelTM,cm->mRefTM);
  }
  paMVar1 = (MeReal (*) [4])0x0;
  if ((cm->linearVelocity != (MeReal *)0x0) && (cm->angularVelocity != (MeReal *)0x0)) {
                    
    paMVar1 = tmEnd;
    MeMatrix4TMUpdateFromVelocities
              (paMVar1,0.0001,motionDuration,cm->linearVelocity,cm->angularVelocity,
               (cm->mInstance).mTM);
  }
  McdGeometryInstanceUpdateAABB(&cm->mInstance,paMVar1,0);
  return;
}

/* ---- McdModelUpdatePathCompatible (exported as kd_McdModelUpdatePathCompatible, asm label "McdModelUpdatePathCompatible") ---- */
void kd_McdModelUpdatePathCompatible(McdModelID cm,MeReal param_2)

{
  kd_McdModelUpdate(cm);
  return;
}

/* ---- McdModelGetAABB (exported as kd_McdModelGetAABB, asm label "McdModelGetAABB") ---- */
void kd_McdModelGetAABB(McdModelID cm,MeReal *minCorner,MeReal *maxCorner)

{
  McdGeometryInstanceGetAABB(&cm->mInstance,minCorner,maxCorner);
  return;
}

/* ---- McdModelGetGeometryInstance (exported as kd_McdModelGetGeometryInstance, asm label "McdModelGetGeometryInstance") ---- */
McdGeometryInstanceID kd_McdModelGetGeometryInstance(McdModelID cm)

{
  return &cm->mInstance;
}

/* ---- McdModelGetTransformPtr (exported as kd_McdModelGetTransformPtr, asm label "McdModelGetTransformPtr") ---- */
MeMatrix4Ptr kd_McdModelGetTransformPtr(McdModelID cm)

{
  MeMatrix4Ptr paMVar1;
  
  paMVar1 = McdGeometryInstanceGetTransformPtr(&cm->mInstance);
  return paMVar1;
}

/* ---- McdModelSetTransformPtr (exported as kd_McdModelSetTransformPtr, asm label "McdModelSetTransformPtr") ---- */
void kd_McdModelSetTransformPtr(McdModelID cm,MeMatrix4Ptr geometryTM)

{
  McdGeometryInstanceSetTransformPtr(&cm->mInstance,geometryTM);
  return;
}

/* ---- McdModelSetLinearVelocityPtr (exported as kd_McdModelSetLinearVelocityPtr, asm label "McdModelSetLinearVelocityPtr") ---- */
void kd_McdModelSetLinearVelocityPtr(McdModelID cm,MeReal *linVelocity)

{
  cm->linearVelocity = linVelocity;
  return;
}

/* ---- McdModelGetLinearVelocityPtr (exported as kd_McdModelGetLinearVelocityPtr, asm label "McdModelGetLinearVelocityPtr") ---- */
MeReal * kd_McdModelGetLinearVelocityPtr(McdModelID cm)

{
  return cm->linearVelocity;
}

/* ---- McdModelSetAngularVelocityPtr (exported as kd_McdModelSetAngularVelocityPtr, asm label "McdModelSetAngularVelocityPtr") ---- */
void kd_McdModelSetAngularVelocityPtr(McdModelID cm,MeReal *angVelocity)

{
  cm->angularVelocity = angVelocity;
  return;
}

/* ---- McdModelGetAngularVelocityPtr (exported as kd_McdModelGetAngularVelocityPtr, asm label "McdModelGetAngularVelocityPtr") ---- */
MeReal * kd_McdModelGetAngularVelocityPtr(McdModelID cm)

{
  return cm->angularVelocity;
}

/* ---- McdModelSetUserData (exported as kd_McdModelSetUserData, asm label "McdModelSetUserData") ---- */
void kd_McdModelSetUserData(McdModelID cm,void *data)

{
  cm->mData = data;
  return;
}

/* ---- McdModelGetUserData (exported as kd_McdModelGetUserData, asm label "McdModelGetUserData") ---- */
void * kd_McdModelGetUserData(McdModelID cm)

{
  return cm->mData;
}

/* ---- McdModelSetGeometry (exported as kd_McdModelSetGeometry, asm label "McdModelSetGeometry") ---- */
void kd_McdModelSetGeometry(McdModelID cm,McdGeometryID g)

{
  if (((char)g->mRefCtAndID == '\0') && (cm->mSpace != (McdSpaceID)0x0)) {
    MeFatalError(MeFatalErrorLevel,
                 "Please Remove your model from the space before changinge geometry to Null");
  }
  McdGeometryInstanceSetGeometry(&cm->mInstance,g);
  return;
}

/* ---- McdModelGetGeometry (exported as kd_McdModelGetGeometry, asm label "McdModelGetGeometry") ---- */
McdGeometryID kd_McdModelGetGeometry(McdModelID cm)

{
  McdGeometryID pMVar1;
  
  pMVar1 = McdGeometryInstanceGetGeometry(&cm->mInstance);
  return pMVar1;
}

/* ---- McdModelGetBodyData (exported as kd_McdModelGetBodyData, asm label "McdModelGetBodyData") ---- */
void * kd_McdModelGetBodyData(McdModelID cm)

{
  return cm->mBody;
}

/* ---- McdModelSetBodyData (exported as kd_McdModelSetBodyData, asm label "McdModelSetBodyData") ---- */
void kd_McdModelSetBodyData(McdModelID cm,void *body)

{
  cm->mBody = body;
  return;
}

/* ---- McdModelSetRelativeTransformPtrs (exported as kd_McdModelSetRelativeTransformPtrs, asm label "McdModelSetRelativeTransformPtrs") ---- */
void kd_McdModelSetRelativeTransformPtrs
               (McdModelID cm,MeVector4 *relativeTM,MeVector4 *referenceTM,
               MeVector4 *compoundTM,MeBool own)

{
  void *pvVar1;
  MeBool own_local;
  MeVector4 *compoundTM_local;
  MeVector4 *referenceTM_local;
  
  if ((cm->flags & 1U) != 0) {
    (MeMemoryAPI.destroyAligned)(cm->mRelTM);
    pvVar1 = McdGeometryInstanceGetTransformPtr(&cm->mInstance);
    (MeMemoryAPI.destroyAligned)(pvVar1);
    cm->flags = cm->flags & 0xfffffffe;
  }
  cm->mRelTM = relativeTM;
  cm->mRefTM = referenceTM;
  if (relativeTM == (MeVector4 *)0x0) {
    McdGeometryInstanceSetTransformPtr(&cm->mInstance,referenceTM);
    return;
  }
  McdGeometryInstanceSetTransformPtr(&cm->mInstance,compoundTM);
  if (own == 0) {
    cm->flags = cm->flags & 0xfffffffe;
  }
  else {
    cm->flags = cm->flags | 1;
  }
  return;
}

/* ---- McdModelGetRelativeTransformPtrs (exported as kd_McdModelGetRelativeTransformPtrs, asm label "McdModelGetRelativeTransformPtrs") ---- */
void kd_McdModelGetRelativeTransformPtrs
               (McdModelID cm,MeMatrix4Ptr *relativeTM,MeMatrix4Ptr *referenceTM)

{
  *relativeTM = cm->mRelTM;
  *referenceTM = cm->mRefTM;
  return;
}

/* ---- McdModelSetRelativeTransform (exported as kd_McdModelSetRelativeTransform, asm label "kd_McdModelSetRelativeTransform") ---- */
void kd_McdModelSetRelativeTransform(McdModelID cm,MeMatrix4Ptr relTM,MeMatrix4Ptr refTM)

{
  MeVector4 *compoundTM;
  MeVector4 *relativeTM;
  
  if (relTM == (MeMatrix4Ptr)0x0) {
    compoundTM = (MeVector4 *)0x0;
    relativeTM = (MeVector4 *)0x0;
  }
  else {
                    
    compoundTM = (MeMemoryAPI.createAligned)((4) * (int)sizeof(*(MeVector4 *)0),0x10);
    relativeTM = (MeMemoryAPI.createAligned)((4) * (int)sizeof(*(MeVector4 *)0),0x10);
    (*relativeTM)[0] = (*relTM)[0];
    (*relativeTM)[1] = (*relTM)[1];
    (*relativeTM)[2] = (*relTM)[2];
    (*relativeTM)[3] = (*relTM)[3];
    relativeTM[1][0] = relTM[1][0];
    relativeTM[1][1] = relTM[1][1];
    relativeTM[1][2] = relTM[1][2];
    relativeTM[1][3] = relTM[1][3];
    relativeTM[2][0] = relTM[2][0];
    relativeTM[2][1] = relTM[2][1];
    relativeTM[2][2] = relTM[2][2];
    relativeTM[2][3] = relTM[2][3];
    relativeTM[3][0] = relTM[3][0];
    relativeTM[3][1] = relTM[3][1];
    relativeTM[3][2] = relTM[3][2];
    relativeTM[3][3] = relTM[3][3];
  }
  kd_McdModelSetRelativeTransformPtrs
            (cm,relativeTM,refTM,compoundTM,(uint)(relTM != (MeMatrix4Ptr)0x0));
  return;
}

/* ---- McdModelGetRelativeTransform (exported as kd_McdModelGetRelativeTransform, asm label "McdModelGetRelativeTransform") ---- */
MeMatrix4Ptr kd_McdModelGetRelativeTransform(McdModelID cm)

{
  return cm->mRelTM;
}

/* ---- McdModelCompoundTransforms (exported as kd_McdModelCompoundTransforms, asm label "McdModelCompoundTransforms") ---- */
void kd_McdModelCompoundTransforms(McdModelID cm)

{
  MeMatrix4TMCompound((cm->mInstance).mTM,cm->mRelTM,cm->mRefTM);
  return;
}

/* ---- McdModelSetMaterial (exported as kd_McdModelSetMaterial, asm label "McdModelSetMaterial") ---- */
void kd_McdModelSetMaterial(McdModelID cm,int material)

{
  McdGeometryInstanceSetMaterial(&cm->mInstance,material);
  return;
}

/* ---- McdModelGetMaterial (exported as kd_McdModelGetMaterial, asm label "McdModelGetMaterial") ---- */
uint kd_McdModelGetMaterial(McdModelID cm)

{
  uint uVar1;
  
  uVar1 = McdGeometryInstanceGetMaterial(&cm->mInstance);
  return uVar1;
}

/* ---- McdModelSetRequestID (exported as kd_McdModelSetRequestID, asm label "McdModelSetRequestID") ---- */
void kd_McdModelSetRequestID(McdModelID cm,int requestId)

{
  cm->mRequestID = requestId;
  return;
}

/* ---- McdModelGetRequestID (exported as kd_McdModelGetRequestID, asm label "McdModelGetRequestID") ---- */
int kd_McdModelGetRequestID(McdModelID cm)

{
  return cm->mRequestID;
}

/* ---- McdModelSetUpdateCallback (exported as kd_McdModelSetUpdateCallback, asm label "McdModelSetUpdateCallback") ---- */
void kd_McdModelSetUpdateCallback(McdModelID cm,McdModelUpdateFnPtr f)

{
  cm->mTransformUpdateFn = f;
  return;
}

/* ---- McdModelGetUpdateCallback (exported as kd_McdModelGetUpdateCallback, asm label "McdModelGetUpdateCallback") ---- */
McdModelUpdateFnPtr kd_McdModelGetUpdateCallback(McdModelID cm)

{
  return cm->mTransformUpdateFn;
}

/* ---- McdModelSetIntersectCallback (exported as kd_McdModelSetIntersectCallback, asm label "McdModelSetIntersectCallback") ---- */
void kd_McdModelSetIntersectCallback(McdModelID cm,McdModelIntersectFnPtr fn)

{
  cm->mIntersectFn = fn;
  return;
}

/* ---- McdModelGetIntersectCallback (exported as kd_McdModelGetIntersectCallback, asm label "McdModelGetIntersectCallback") ---- */
McdModelIntersectFnPtr kd_McdModelGetIntersectCallback(McdModelID cm)

{
  return cm->mIntersectFn;
}

/* ---- McdModelGetSortKey (exported as kd_McdModelGetSortKey, asm label "McdModelGetSortKey") ---- */
MeI16 kd_McdModelGetSortKey(McdModelID cm)

{
  return cm->sortKey;
}

/* ---- McdModelSetSortKey (exported as kd_McdModelSetSortKey, asm label "McdModelSetSortKey") ---- */
void kd_McdModelSetSortKey(McdModelID cm,MeI16 key)

{
  cm->sortKey = key;
  return;
}
